### ISSUE TITLE
Terraform crashes during destroy (it's trying to upgrade azurerm_log_analytics_workspace state from v1 to v2)

### ISSUE THREAD

**Issue by myhau** [hashicorp/terraform-provider-azurerm#11338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 0.14.10 (upgrading from 0.14.7)
Terraform azurerm version: 2.55 (upgrading from 2.37.0)

### Affected Resource(s)

* `azurerm_log_analytics_workspace`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "monitoring_resource_group" {
  name     = local.monitoring.resource_group_name
  location = var.location

  tags = local.tags
}

resource "azurerm_log_analytics_workspace" "monitoring_log_analytics_workspace" {
  name                = local.monitoring.log_analytics_workspace_name
  location            = azurerm_resource_group.monitoring_resource_group.location
  resource_group_name = azurerm_resource_group.monitoring_resource_group.name
  sku                 = "PerGB2018"
  retention_in_days   = 30

  tags = local.tags
}

```

### Debug Output

```
2021-04-15T10:18:16.7540888Z !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
2021-04-15T10:18:16.7541141Z 
2021-04-15T10:18:16.7541529Z Terraform crashed! This is always indicative of a bug within Terraform.
2021-04-15T10:18:16.7542027Z A crash log has been placed at "crash.log" relative to your current
2021-04-15T10:18:16.7542520Z working directory. It would be immensely helpful if you could please
2021-04-15T10:18:16.7543001Z report the crash with Terraform[1] so that we can fix this.
2021-04-15T10:18:16.7543216Z 
2021-04-15T10:18:16.7543588Z When reporting bugs, please include your terraform version. That
2021-04-15T10:18:16.7544075Z information is available on the first line of crash.log. You can also
2021-04-15T10:18:16.7544795Z get it by running 'terraform --version' on the command line.
2021-04-15T10:18:16.7545021Z 
2021-04-15T10:18:16.7545416Z SECURITY WARNING: the "crash.log" file that was created may contain 
2021-04-15T10:18:16.7545922Z sensitive information that must be redacted before it is safe to share 
2021-04-15T10:18:16.7546349Z on the issue tracker.
2021-04-15T10:18:16.7546502Z 
2021-04-15T10:18:16.7546856Z [1]: https://github.com/hashicorp/terraform/issues
2021-04-15T10:18:16.7547073Z 
2021-04-15T10:18:16.7547456Z !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

```
2021-04-15T10:18:16.7306554Z panic: interface conversion: interface {} is nil, not *clients.Client
2021-04-15T10:18:16.7307412Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: 
2021-04-15T10:18:16.7308297Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: goroutine 29 [running]:
2021-04-15T10:18:16.7309639Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/loganalytics/migration.workspaceUpgradeV1ToV2(0xc001b6e4e0, 0x0, 0x0, 0xc0013220b0, 0x4fa75e0, 0xc001294018)
2021-04-15T10:18:16.7311225Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/loganalytics/migration/workspace_v1_to_v2.go:22 +0x3d0
2021-04-15T10:18:16.7312818Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).upgradeJSONState(0xc00014f280, 0x1, 0xc001b6e4e0, 0xc000b0e900, 0xc001294018, 0x0, 0x0)
2021-04-15T10:18:16.7314623Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:395 +0xb7
2021-04-15T10:18:16.7317653Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).UpgradeResourceState(0xc00014f280, 0x5fe2c10, 0xc001b6e060, 0xc001046880, 0xc00014f280, 0xc001b6e060, 0xc000f9aba0)
2021-04-15T10:18:16.7319389Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:270 +0x28f
2021-04-15T10:18:16.7321118Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_UpgradeResourceState_Handler(0x562f700, 0xc00014f280, 0x5fe2c10, 0xc001b6e060, 0xc000970360, 0x0, 0x5fe2c10, 0xc001b6e060, 0xc000165680, 0x46c)
2021-04-15T10:18:16.7322780Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3233 +0x214
2021-04-15T10:18:16.7329176Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00062e540, 0x6025918, 0xc001095980, 0xc0000b0d00, 0xc000f7f6e0, 0x924d4e0, 0x0, 0x0, 0x0)
2021-04-15T10:18:16.7330861Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1180 +0x52b
2021-04-15T10:18:16.7332274Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc00062e540, 0x6025918, 0xc001095980, 0xc0000b0d00, 0x0)
2021-04-15T10:18:16.7333665Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1503 +0xd0c
2021-04-15T10:18:16.7335274Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0007e28c0, 0xc00062e540, 0x6025918, 0xc001095980, 0xc0000b0d00)
2021-04-15T10:18:16.7336669Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:843 +0xab
2021-04-15T10:18:16.7337885Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-15T10:18:16.7339362Z 2021-04-15T10:18:16.694Z [DEBUG] plugin.terraform-provider-azurerm_v2.55.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:841 +0x1fd
2021-04-15T10:18:16.7340291Z 2021/04/15 10:18:16 [TRACE] vertex "azurerm_log_analytics_workspace.monitoring_log_analytics_workspace": visit complete
```

### Panic Output

[crash-1.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/6317303/crash-1.log)

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
