### ISSUE TITLE
"azurerm_cosmosdb_account" data source - panic: runtime error: index out of range [6] with length 6

### ISSUE THREAD

**Issue by AONunan** [hashicorp/terraform-provider-azurerm#12210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.63.0
```

### Affected Resource(s)

* `azurerm_cosmosdb_account` (data source)

### Terraform Configuration Files

```hcl
data "azurerm_cosmosdb_account" "cosmosdb" {
  name                = "cosmosdbname"
  resource_group_name = "cosmosdbrg"
}
```

### Panic Output

```
Stack trace from the terraform-provider-azurerm_v2.63.0_x5 plugin:

panic: runtime error: index out of range [6] with length 6

goroutine 129 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos.dataSourceCosmosDbAccountRead(0xc00042c460, 0x5478c20, 0xc0015a0e00, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos/cosmosdb_account_data_source.go:271 +0x1e52
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc00060c500, 0xc001914420, 0x5478c20, 0xc0015a0e00, 0xc000d2cf38, 0x1, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:413 +0x91
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc000129580, 0xc001531af8, 0xc001914420, 0xc001914420, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:451 +0x8f
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00011f938, 0x6370830, 0xc00019b770, 0xc001a920c0, 0xc00011f938, 0xc00019b770, 0xc001aa0ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:1046 +0x42d
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x595f720, 0xc00011f938, 0x6370830, 0xc00019b770, 0xc001a96060, 0x0, 0x6370830, 0xc00019b770, 0xc001aa4000, 0x24b)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3341 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002dd880, 0x63b7b78, 0xc0005ca300, 0xc00188a000, 0xc001212e70, 0x97b8a70, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002dd880, 0x63b7b78, 0xc0005ca300, 0xc00188a000, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000de8e50, 0xc0002dd880, 0x63b7b78, 0xc0005ca300, 0xc00188a000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:857 +0x1fd

Error: The terraform-provider-azurerm_v2.63.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
### Expected Behaviour

Terraform should be able to find the CosmosDB account using the data source.

### Actual Behaviour

Terraform crashes with the above message.

### Steps to Reproduce

1. `terraform plan`

**Comment by lonegunmanb** [comment]
Steps to Reproduce:

```hcl
resource "azurerm_cosmosdb_account" "db" {
  name                = "fx12210"
  location            = "East Asia"
  resource_group_name = "fx12210" # change to your res group name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  enable_automatic_failover = true

  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "MongoDBv3.4"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 300
    max_staleness_prefix    = 100000
  }

  geo_location {
    location          = "Japan East"
    failover_priority = 5 // NO VALIDATION HERE
  }

  geo_location {
    location          = "East Asia"
    failover_priority = 0
  }
}

data "azurerm_cosmosdb_account" "db" {
  depends_on = [azurerm_cosmosdb_account.db]
  name                = "fix12210"
  resource_group_name = "fx12210"
}
```

The root cause is we don't check whether `geo_location.failover_priority` meets the requirement:

>The failover priority of the region. A failover priority of 0 indicates a write region. The maximum value for a failover priority = (total number of regions - 1). Failover priority values must be unique for each of the regions in which the database account exists.

And in `cosmosdb_account_data_source.go` we just trust `FailoverPriority` we retrieved from Azure and use it as index of slice:

```go
locations := make([]map[string]interface{}, len(*props.FailoverPolicies))
		for _, l := range *props.FailoverPolicies {
			locations[*l.FailoverPriority] = map[string]interface{}{
				"id":                *l.ID,
				"location":          azure.NormalizeLocation(*l.LocationName),
				"failover_priority": int(*l.FailoverPriority),
			}
		}
```
It caused panic.
