### ISSUE TITLE
`azurerm_databricks_workspace` crashes in 2.71.0

### ISSUE THREAD

**Issue by favoretti** [hashicorp/terraform-provider-azurerm#12878]
```
Stack trace from the terraform-provider-azurerm_v2.71.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56bfe91]

goroutine 1694 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/databricks.resourceDatabricksWorkspaceRead(0xc0015f0d00, 0x63df5e0, 0xc0017abc00, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/databricks/databricks_workspace_resource.go:567 +0x9f1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00046dce0, 0x7386588, 0xc00172dc00, 0xc0015f0d00, 0x63df5e0, 0xc0017abc00, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00046dce0, 0x7386588, 0xc00172dc00, 0xc0017a35e0, 0x63df5e0, 0xc0017abc00, 0xc001e05678, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000de00, 0x7386588, 0xc00172dc00, 0xc00172dc40, 0xc00172dc00, 0x100b705, 0x67093a0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001d568c0, 0x7386630, 0xc00172dc00, 0xc00186ac60, 0xc001d568c0, 0xc00075a570, 0xc000b75ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x68c7aa0, 0xc001d568c0, 0x7386630, 0xc00075a570, 0xc00186ac00, 0x0, 0x7386630, 0xc00075a570, 0xc001c0a000, 0x5d7)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000242a80, 0x73d2ed8, 0xc000703b00, 0xc001ca06c0, 0xc0017c8ab0, 0xa980130, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000242a80, 0x73d2ed8, 0xc000703b00, 0xc001ca06c0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005ec7f0, 0xc000242a80, 0x73d2ed8, 0xc000703b00, 0xc001ca06c0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.71.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by favoretti** [comment]
// cc @WodansSon

**Comment by WodansSon** [comment]
@favoretti thank you for opening this issue, can you please supply the terraform HCL configuration to reproduce this issue? The line of code causing this issue is:

```
_, pubSubAssoc, priSubAssoc := expandWorkspaceCustomParameters(customParamsRaw, *cmkEnabled, *infraEnabled, "", "")
```

I am just guessing, but I suspect in your configuration file you have not define any `custom parameters`. I may just need to add a `nil` check around this line of code to fix this.

**Comment by favoretti** [comment]
@WodansSon we actually do, that's the weird thing.
```
resource "azurerm_databricks_workspace" "this" {
  # /^[a-z0-9][a-z0-9][a-z0-9_-]{0,27}[a-z0-9]$/
  name                        = var.workspace_name == "" ? module.labels.id_with_suffix.dbw : var.workspace_name
  resource_group_name         = var.resource_group_name
  managed_resource_group_name = var.managed_resource_group_name == "" ? module.labels.ids_with_suffix[join("-", compact([var.name, "dbrks-managed"]))].rg : var.managed_resource_group_name
  location                    = module.labels.location
  sku                         = "premium"
  tags                        = module.labels.tags

  custom_parameters {
    no_public_ip        = var.no_public_ip
    virtual_network_id  = var.vnet.id
    public_subnet_name  = var.vnet.public_subnet_name
    private_subnet_name = var.vnet.private_subnet_name
  }
}
```

It's a part of the module.

**Comment by smitp11** [comment]
```
terraform 0.14.9
azurerm 2.72.0
```

Seeing the same issue:

```
##[error]panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4ae1206]

goroutine 1994 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/databricks.resourceDatabricksWorkspaceRead(0xc00308a800, 0x580f2c0, 0xc0017c7880, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/internal/services/databricks/databricks_workspace_resource.go:567 +0x9e6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000840e00, 0x67b0388, 0xc001405e40, 0xc00308a800, 0x580f2c0, 0xc0017c7880, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000840e00, 0x67b0388, 0xc001405e40, 0xc000b92230, 0x580f2c0, 0xc0017c7880, 0xc001eb19f0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00118a420, 0x67b0388, 0xc001405e40, 0xc001405e80, 0xc001405e40, 0x40b965, 0x5b34620)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00102b6e0, 0x67b0430, 0xc001405e40, 0xc001304600, 0xc00102b6e0, 0xc000df1ba0, 0x46d107)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x5cf39c0, 0xc00102b6e0, 0x67b0430, 0xc001170990, 0xc0013045a0, 0x0, 0x67b0430, 0xc001170990, 0xc00294aa00, 0x658)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000c9e380, 0x67fd1b8, 0xc000299e00, 0xc002baf320, 0xc000c13110, 0x9d780f0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000c9e380, 0x67fd1b8, 0xc000299e00, 0xc002baf320, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00118db50, 0xc000c9e380, 0x67fd1b8, 0xc000299e00, 0xc002baf320)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd
```

HCL

```
resource "azurerm_databricks_workspace" "dbricks-dap-workspace" {
  name                = var.databricks_workspace_suffix
  resource_group_name = azurerm_resource_group.databricks-resource-group.name
  location            = var.azure_region
  sku                 = var.db_ws_sku

  managed_resource_group_name = var.dbks-managed-rg
  custom_parameters {
    public_subnet_name  = var.snet_pub
    private_subnet_name = var.snet_prv
    virtual_network_id  = azurerm_virtual_network.dap_dev_core.id
  }

  tags = merge(map(          
          "deviceType", "Microsoft.Databricks/workspaces"
           ), var.tags_dataPlatform_project_default) 

  depends_on = [azurerm_subnet_network_security_group_association.dbricks-nsg-pub]
}
```

**Comment by swedishstyle** [comment]
`Terraform v1.0.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.72.0`

Seeing the same issue here when attempting a Terraform import:

`Stack trace from the terraform-provider-azurerm_v2.72.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4edb8c6]

goroutine 91 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/databricks.resourceDatabricksWorkspaceRead(0xc000139400, 0x5c18fe0, 0xc0010e6e00, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/internal/services/databricks/databricks_workspace_resource.go:567 +0x9e6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0001a9ce0, 0x6bbc968, 0xc00167b080, 0xc000139400, 0x5c18fe0, 0xc0010e6e00, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001a9ce0, 0x6bbc968, 0xc00167b080, 0xc0010ca7e0, 0x5c18fe0, 0xc0010e6e00, 0xc001dae570, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00020fb48, 0x6bbc968, 0xc00167b080, 0xc00167b0c0, 0xc00167b080, 0x72beca, 0x5f3d900)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x45b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001a92aa0, 0x6bbca10, 0xc00167b080, 0xc0016b6000, 0xc001a92aa0, 0xc001562540, 0xc0019f7ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x108
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x60fd240, 0xc001a92aa0, 0x6bbca10, 0xc001562540, 0xc001659f80, 0x0, 0x6bbca10, 0xc001562540, 0xc000b2ea80, 0x312)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001aa8c0, 0x6c09ff8, 0xc000077800, 0xc000a6c5a0, 0xc000244ae0, 0xa195030, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001aa8c0, 0x6c09ff8, 0xc000077800, 0xc000a6c5a0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000f46870, 0xc0001aa8c0, 0x6c09ff8, 0xc000077800, 0xc000a6c5a0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.72.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

Works on some databricks instances, but not others. I'm not familiar enough with databricks to pinpoint why at this stage, but will try to do some investigation

**Comment by m7medcs** [comment]
I am facing the same issue

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
