### ISSUE TITLE
Additional resources which are crashing with Error: Plugin did not respond

### ISSUE THREAD

**Issue by AlNistor** [hashicorp/terraform-provider-azurerm#12874]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem description

Resources fail with Error: Plugin did not respond.
On Monday 2nd August 2021, eveything was working fine. We were working on some new stuff in our infrastructure and on Tuesday morning (3rd August) when we ran the deployments they started to fail with the Error: Plugin did not respond. We did not update the version of AzureRM nor Terraform. We were using TF 1.0.3 and Azurerm 2.64.0. 
We looked into the existing issues and we found that multiple resources are affected by this and we waiting for the 2.71.0 release hoping this would fix the raised issues.
We updated to Azurerm 2.71.0 and there are still some resources affected by this error (see the list below).

### Terraform (and AzureRM Provider) Version
* Terraform v1.0.4
* AzureRM v2.71.0

### Affected Resource(s)

* `azurerm_api_management `
*  `azurerm_monitor_diagnostic_setting`
* `azurerm_storage_account_sas`
* `azurerm_key_vault`
* `azurerm_kubernetes_cluster`
* `azurerm_servicebus_topic`

### Azure DevOps Agent output

```
Stack trace from the terraform-provider-azurerm_v2.71.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a09ac5]

goroutine 225 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers.resourceKubernetesClusterUpdate(0xc001acd780, 0x57e1000, 0xc0013ef880, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers/kubernetes_cluster_resource.go:1168 +0x685
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000732d20, 0x6787328, 0xc001cb4240, 0xc001acd780, 0x57e1000, 0xc0013ef880, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:352 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000732d20, 0x6787328, 0xc001cb4240, 0xc00060f6c0, 0xc001b3f120, 0x57e1000, 0xc0013ef880, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0010b0438, 0x6787328, 0xc001cb4240, 0xc001790ff0, 0xc001cb4240, 0x5cc9180, 0xc001ff4100)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001cb82e0, 0x67873d0, 0xc001cb4240, 0xc00060f490, 0xc001cb82e0, 0xc001ff4180, 0xc001203ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5cc9180, 0xc001cb82e0, 0x67873d0, 0xc001ff4180, 0xc00009bb60, 0x0, 0x67873d0, 0xc001ff4180, 0xc001880000, 0xe1bd)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000170540, 0x67d3ab8, 0xc000511500, 0xc0013f4480, 0xc000c8da40, 0x9d7cfa0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000170540, 0x67d3ab8, 0xc000511500, 0xc0013f4480, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000c79410, 0xc000170540, 0x67d3ab8, 0xc000511500, 0xc0013f4480)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.71.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Example of Terraform Error log
```
│ Error: Plugin did not respond
│ 
│   with module.apimanagement.azurerm_api_management.ignis[0],
│   on Modules/ApiManagement/main.tf line 1, in resource "azurerm_api_management" "name":
│    1: resource "azurerm_api_management" "name" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.

╷
│ Error: Request cancelled
│ 
│   with module.databasebackupstorage.data.azurerm_storage_account_sas.db_backup_uploader_shared_access_signature,
│   on Modules/DBBackupStorageAccount/main.tf line 55, in data "azurerm_storage_account_sas" "db_backup_uploader_shared_access_signature":
│   55: data "azurerm_storage_account_sas" "db_backup_uploader_shared_access_signature" {
│ 
│ The plugin.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by AlNistor** [comment]
Hei @jackofallops,

I don't think that the fix which was done for this issue is the final solution.
I updated to v2.72.0 and the deployments are still failing:

here's the logs:

```
Stack trace from the terraform-provider-azurerm_v2.72.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a2cfea]

goroutine 289 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/containers.resourceKubernetesClusterUpdate(0xc0021d0a00, 0x580f2c0, 0xc00161b880, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/internal/services/containers/kubernetes_cluster_resource.go:1170 +0x3b8a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000786d20, 0x67b0388, 0xc0022940c0, 0xc0021d0a00, 0x580f2c0, 0xc00161b880, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:352 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000786d20, 0x67b0388, 0xc0022940c0, 0xc00228e230, 0xc001cf60e0, 0x580f2c0, 0xc00161b880, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0010f8438, 0x67b0388, 0xc0022940c0, 0xc0022a40a0, 0xc0022940c0, 0x5cf39c0, 0xc001894300)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001b4adc0, 0x67b0430, 0xc0022940c0, 0xc00228e000, 0xc001b4adc0, 0xc001894300, 0xc00066bba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5cf39c0, 0xc001b4adc0, 0x67b0430, 0xc001894300, 0xc00166a420, 0x0, 0x67b0430, 0xc001894300, 0xc00061e000, 0xe1bd)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003e01c0, 0x67fd1b8, 0xc0016d8000, 0xc00228c000, 0xc000a0b890, 0x9d78120, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0003e01c0, 0x67fd1b8, 0xc0016d8000, 0xc00228c000, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005ef900, 0xc0003e01c0, 0x67fd1b8, 0xc0016d8000, 0xc00228c000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.72.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by tombuildsstuff** [comment]
this line needs fixing: https://github.com/hashicorp/terraform-provider-azurerm/blob/8b8b5710bb4576e58fdeceda1dbad811d8eb9ef8/internal/services/containers/kubernetes_cluster_resource.go#L1168

**Comment by brownoxford** [comment]
I'm seeing this issue for many resources (not just k8s related), I get both `Error: Request cancelled` and `Error: Plugin did not respond`. The final panic trace is:

```Stack trace from the terraform-provider-azurerm_v2.72.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56dfe46]

goroutine 5198 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/databricks.resourceDatabricksWorkspaceRead(0xc0027b7480, 0x640dd80, 0xc001279c00, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/internal/services/databricks/databricks_workspace_resource.go:567 +0x9e6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000497ce0, 0x73afae8, 0xc001bcb240, 0xc0027b7480, 0x640dd80, 0xc001279c00, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000497ce0, 0x73afae8, 0xc001bcb240, 0xc000c3cd20, 0x640dd80, 0xc001279c00, 0xc002573958, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0011c8468, 0x73afae8, 0xc001bcb240, 0xc001bcb280, 0xc001bcb240, 0x100b665, 0x67334c0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001af1120, 0x73afb90, 0xc001bcb240, 0xc002622d20, 0xc001af1120, 0xc0011b0c30, 0xc0005d4ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x68f27e0, 0xc001af1120, 0x73afb90, 0xc0011b0c30, 0xc002622cc0, 0x0, 0x73afb90, 0xc0011b0c30, 0xc003542000, 0x55c)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002268c0, 0x73fcad8, 0xc000642480, 0xc001b7e240, 0xc001584b10, 0xa97b2b0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002268c0, 0x73fcad8, 0xc000642480, 0xc001b7e240, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000597310, 0xc0002268c0, 0x73fcad8, 0xc000642480, 0xc001b7e240)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.72.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by brownoxford** [comment]
Also note that this works with provider version 2.70.0, but breaks in 2.71.0 and 2.72.0 - I am using Terraform v1.0.4

**Comment by jackofallops** [comment]
Hi @brownoxford - That's different crash which we'll need to look into, I've open a separate issue to track it (13024).

**Comment by jackofallops** [comment]
Hi @AlNistor - Can you describe what is being changed on the resource at the point the crash happens? Are you attempting to remove the AAD Profile? Are you able to provide a plan output from that step?

**Comment by AlNistor** [comment]
@jackofallops  I wasn't doing anything special, I have had the same configuration of the cluster for 7 months now. I was doing some updates in the post Terraform Apply jobs when this started to happen.
This is the plan output that I get in the pipelines.
```
# module.kubernetes.azurerm_kubernetes_cluster.****  will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "****" {
        id                              = "/subscriptions/*****/resourcegroups/rg-***-sb1/providers/Microsoft.ContainerService/managedClusters/aks-***-sb1"
        name                            = "aks-***-sb1"
        tags                            = {
            "environment" = "rg-***-sb1"
        }
        # (15 unchanged attributes hidden)

      ~ addon_profile {
          - aci_connector_linux {
              - enabled = false -> null
            }

          - azure_policy {
              - enabled = false -> null
            }

          - http_application_routing {
              - enabled = false -> null
            }

          - ingress_application_gateway {
              - enabled                              = false -> null
              - ingress_application_gateway_identity = [] -> null
            }

          - kube_dashboard {
              - enabled = false -> null
            }

            # (1 unchanged block hidden)
        }

      ~ role_based_access_control {
            # (1 unchanged attribute hidden)

          - azure_active_directory {
              - admin_group_object_ids = [] -> null
              - azure_rbac_enabled     = false -> null
              - managed                = true -> null
              - tenant_id              = "***" -> null
            }
        }
        # (4 unchanged blocks hidden)
```

**Comment by jackofallops** [comment]
Thanks @AlNistor - That helps a lot.

**Comment by jackofallops** [comment]
Hi @AlNistor - I'm still struggling to reproduce this in a valid way. Based on your plan output you're attempting to remove the `azure_active_directory` config from the RBAC block? Given you didn't change Terraform or Provider versions, did the module you are using change at all? Such as a dynamic block for `azure_active_directory` that is now not provided, (along with some other values I can see to be removed)?

The service supports changing/updating this block, but does not support removing it, so we cannot satisfy the plan output here. I'll be pushing a change later today to prevent the crash happening, but I suspect your config will result in a permanent diff.

**Comment by AlNistor** [comment]
Hi @jackofallops,
Thanks for being persistent in fixing this issue.
In my terraform configuration I don't have the `azure_active_directory` block at all. So I think it adds something by default if it is not specified, right?
And regarding the other values which seem to be removed, for example the `addon_profile` we added it 2 weeks ago to configure an `oms_agent`, but other than that nothing else is specified, so I would assume that again some default values are being assigned and when we run the pipeline it tries to remove them because the specification is not there.

Regarding RBAC config, with terraform we are just providing the fact that we want the RBAC to be enabled and the rest of RBACs are being created through manifests files (based on the needs of the different components we are using, like cert-manager, nginx, etc.).

The cluster config is pretty slim in terraform.

I have a test environment, do you think that by deleting the cluster and recreating it could provide some additional info to you if I share the logs?

**Comment by jackofallops** [comment]
> Regarding RBAC config, with terraform we are just providing the fact that we want the RBAC to be enabled and the rest of RBACs are being created through manifests files (based on the needs of the different components we are using, like cert-manager, nginx, etc.).

Hi @AlNistor - This clears things up. The fix I've just pushed for review should avoid the crash so your runs will complete, but I suspect you'll need to employ `ignore_changes` on the items that are changed / updated outside of Terraform's control or you'll end up with a permanent diff as Terraform has an understanding of these properties and expects to control them. For as many configuration items as you can, I'd probably recommend you include them in your Terraform configuration to reduce the potential for change that you do not expect.
