### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by AmudaPalani** [hashicorp/terraform-provider-azurerm#13219]
```shell-session
Error: rpc error: code = Unavailable desc = transport is closing


panic: interface conversion: interface {} is []interface {}, not string
2021-09-02T16:54:56.000Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 
2021-09-02T16:54:56.000Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: goroutine 452 [running]:
2021-09-02T16:54:56.000Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: github.com/hashicorp/terraform-provider-azurerm/internal/services/frontdoor.flattenRoutingRuleForwardingConfiguration(0x6811ba8, 0xc001455640, 0x56e3a40, 0xc0022feed0, 0x4, 0xc0017bf1e0, 0xa9)
2021-09-02T16:54:56.000Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/frontdoor/frontdoor_resource.go:2005 +0xe7f
2021-09-02T16:54:56.000Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: github.com/hashicorp/terraform-provider-azurerm/internal/services/frontdoor.flattenSingleFrontDoorRoutingRule(0xc0021e7260, 0xc00224b0e0, 0xc00224b0f0, 0xc00224b0d0, 0x56e3a40, 0xc0022feed0, 0xc00178b20f, 0x24, 0xc00178b243, 0x11, ...)
2021-09-02T16:54:56.000Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/frontdoor/frontdoor_resource.go:1916 +0x7ad
2021-09-02T16:54:56.001Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: github.com/hashicorp/terraform-provider-azurerm/internal/services/frontdoor.flattenFrontDoorRoutingRule(0xc000ec51a0, 0x56e3a40, 0xc0022feed0, 0xc00178b20f, 0x24, 0xc00178b243, 0x11, 0xc00178b27c, 0x12, 0x9e97160, ...)
2021-09-02T16:54:56.001Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/frontdoor/frontdoor_resource.go:1884 +0x2e5
2021-09-02T16:54:56.001Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: github.com/hashicorp/terraform-provider-azurerm/internal/services/frontdoor.resourceFrontDoorRead(0xc001b27c00, 0x588e0c0, 0xc00122bc00, 0x0, 0x0)
2021-09-02T16:54:56.001Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/frontdoor/frontdoor_resource.go:717 +0x131e
2021-09-02T16:54:56.001Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000a44700, 0x6844cc8, 0xc002176d00, 0xc001b27c00, 0x588e0c0, 0xc00122bc00, 0x0, 0x0, 0x0)
2021-09-02T16:54:56.001Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
2021-09-02T16:54:56.002Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a44700, 0x6844cc8, 0xc002176d00, 0xc0010ebc70, 0x588e0c0, 0xc00122bc00, 0xc001b245f0, 0x0, 0x0, 0x0)
2021-09-02T16:54:56.002Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
2021-09-02T16:54:56.002Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc001152510, 0x6844cc8, 0xc002176d00, 0xc002176d40, 0xc002176d00, 0x40b965, 0x5bb9260)
2021-09-02T16:54:56.002Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
2021-09-02T16:54:56.002Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001e01820, 0x6844d70, 0xc002176d00, 0xc0019fa960, 0xc001e01820, 0xc001b375c0, 0xc000dcaba0)
2021-09-02T16:54:56.002Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
2021-09-02T16:54:56.003Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x5d7a940, 0xc001e01820, 0x6844d70, 0xc001b375c0, 0xc0019fa900, 0x0, 0x6844d70, 0xc001b375c0, 0xc000138a00, 0x3354)
2021-09-02T16:54:56.003Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2021-09-02T16:54:56.003Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006f41c0, 0x6892598, 0xc001e3cf00, 0xc001b33560, 0xc000abc9f0, 0x9e56110, 0x0, 0x0, 0x0)
2021-09-02T16:54:56.003Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
2021-09-02T16:54:56.003Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc0006f41c0, 0x6892598, 0xc001e3cf00, 0xc001b33560, 0x0)
2021-09-02T16:54:56.003Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
2021-09-02T16:54:56.003Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000630b20, 0xc0006f41c0, 0x6892598, 0xc001e3cf00, 0xc001b33560)
2021-09-02T16:54:56.004Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
2021-09-02T16:54:56.004Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-09-02T16:54:56.004Z [DEBUG] plugin.terraform-provider-azurerm_v2.73.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd
2021-09-02T16:54:56.007Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
Error: /02 16:54:56 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
Error: /02 16:54:56 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/09/02 16:54:56 [TRACE] [walkRefresh] Exiting eval tree: azurerm_frontdoor.frontdoor[0]
2021/09/02 16:54:56 [TRACE] vertex "azurerm_frontdoor.frontdoor[0]": visit complete
2021/09/02 16:54:56 [TRACE] vertex "azurerm_frontdoor.frontdoor": dynamic subgraph encountered errors
2021/09/02 16:54:56 [TRACE] vertex "azurerm_frontdoor.frontdoor": visit complete
2021/09/02 16:54:56 [TRACE] vertex "azurerm_frontdoor.frontdoor (expand)": dynamic subgraph encountered errors
2021/09/02 16:54:56 [TRACE] vertex "azurerm_frontdoor.frontdoor (expand)": visit complete
2021/09/02 16:54:56 [TRACE] dag/walk: upstream of "data.azurerm_monitor_diagnostic_categories.diagnostic_categories (expand)" errored, so skipping
2021/09/02 16:54:56 [TRACE] dag/walk: upstream of "azurerm_monitor_diagnostic_setting.diagnostic_setting (expand)" errored, so skipping
2021/09/02 16:54:56 [TRACE] dag/walk: upstream of "azurerm_monitor_metric_alert.fdAlertBackendHealth (expand)" errored, so skipping
2021/09/02 16:54:56 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" errored, so skipping
2021/09/02 16:54:56 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021-09-02T16:54:56.013Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/azurerm/2.73.0/linux_amd64/terraform-provider-azurerm_v2.73.0_x5 pid=1033544 error="exit status 2"
2021-09-02T16:54:56.031Z [DEBUG] plugin: plugin exited
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Core version: 0.13.7
AzureRM Provider version: 2.73.0

### Affected Resource(s)

* `azurerm_fronttdoor`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by mbfrahry** [comment]
Hey @AmudaPalani, looks like this was fixed with #13338 and released with Version 2.77.0 of the provider. Feel free to reopen this issue if you continue to see this crash
