### ISSUE TITLE
Crash (null-reference) when reading app_service_managed_certificate_resource

### ISSUE THREAD

**Issue by BaraMike** [hashicorp/terraform-provider-azurerm#13358]
Hello,

We are running in an issue when using "terraform plan" on our existing app_service_managed_certificate_resource

It seems to be a null reference exception when reading the managed certificate resource.
See the terraform plan log at the end of this issue.

You can see in the log a null reference in the following file/line:
internal/services/web/app_service_managed_certificate_resource.go:221
function => resourceAppServiceManagedCertificateRead

Seems like the "issueDate" is missing in our azure response when querying our existing app_service_managed_certificate_resource which results in a null reference exception when parsing the azure response.

### Terraform (and AzureRM Provider) Version
We are using terraform 1.0.6 and azurerm 2.76.0.

### Affected Resource(s)
app_service_managed_certificate_resource

### Terraform Configuration Files
The following is our resource definition. Nothing complicated.

resource "azurerm_app_service_custom_hostname_binding" "pubfuncs" {
  count               = 1
  hostname            = "ourdomain.com"
  app_service_name    = "appservicename"
  resource_group_name = "resourcegroupname"
}

resource "azurerm_app_service_managed_certificate" "pubfuncs" {
  count                      = 1
  custom_hostname_binding_id = azurerm_app_service_custom_hostname_binding.pubfuncs[0].id
}

resource "azurerm_app_service_certificate_binding" "pubfuncs" {
  count               = 1
  hostname_binding_id = azurerm_app_service_custom_hostname_binding.pubfuncs[0].id
  certificate_id      = azurerm_app_service_managed_certificate.pubfuncs[0].id
  ssl_state           = "SniEnabled"
}

### Expected Behaviour
terraform plan/apply should not fail when reading the app_service_managed_certificate_resource

### Actual Behaviour
terraform plan/apply fails when reading the app_service_managed_certificate_resource

TERRAFORM PLAN LOG:

2021-09-15T08:05:16.6431048Z Stack trace from the terraform-provider-azurerm_v2.76.0_x5.exe plugin:
2021-09-15T08:05:16.6431431Z 
2021-09-15T08:05:16.6431917Z panic: runtime error: invalid memory address or nil pointer dereference
2021-09-15T08:05:16.6432647Z [signal 0xc0000005 code=0x0 addr=0x0 pc=0x53a4d4a]
2021-09-15T08:05:16.6432909Z 
2021-09-15T08:05:16.6433301Z goroutine 926 [running]:
2021-09-15T08:05:16.6434185Z github.com/hashicorp/terraform-provider-azurerm/internal/services/web.resourceAppServiceManagedCertificateRead(0xc002ac6b80, 0x57c32c0, 0xc002205500, 0x0, 0x0)
2021-09-15T08:05:16.6435318Z 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/web/app_service_managed_certificate_resource.go:221 +0x70a
2021-09-15T08:05:16.6436471Z github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0015f50a0, 0x67cf5a8, 0xc001139200, 0xc002ac6b80, 0x57c32c0, 0xc002205500, 0x0, 0x0, 0x0)
2021-09-15T08:05:16.6437631Z 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1fb
2021-09-15T08:05:16.6439974Z github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0015f50a0, 0x67cf5a8, 0xc001139200, 0xc0004673b0, 0x57c32c0, 0xc002205500, 0xc0002888a0, 0x0, 0x0, 0x0)
2021-09-15T08:05:16.6441240Z 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
2021-09-15T08:05:16.6442435Z github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000284708, 0x67cf5a8, 0xc001139200, 0xc001139240, 0xc001139200, 0xabeca, 0x5afb360)
2021-09-15T08:05:16.6449845Z 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x45b
2021-09-15T08:05:16.6458231Z github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001e11d40, 0x67cf650, 0xc001139200, 0xc000281ce0, 0xc001e11d40, 0xc002473200, 0xc0005ebba0)
2021-09-15T08:05:16.6465784Z 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x108
2021-09-15T08:05:16.6476290Z github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x5cc45c0, 0xc001e11d40, 0x67cf650, 0xc002473200, 0xc000281c80, 0x0, 0x67cf650, 0xc002473200, 0xc00389a380, 0x356)
2021-09-15T08:05:16.6483937Z 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222
2021-09-15T08:05:16.6492939Z google.golang.org/grpc.(*Server).processUnaryRPC(0xc00024e540, 0x681f298, 0xc00064d980, 0xc0028817a0, 0xc001940ab0, 0x9eec4b0, 0x0, 0x0, 0x0)
2021-09-15T08:05:16.6502304Z 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
2021-09-15T08:05:16.6510732Z google.golang.org/grpc.(*Server).handleStream(0xc00024e540, 0x681f298, 0xc00064d980, 0xc0028817a0, 0x0)
2021-09-15T08:05:16.6519897Z 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
2021-09-15T08:05:16.6527475Z google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0011a6710, 0xc00024e540, 0x681f298, 0xc00064d980, 0xc0028817a0)
2021-09-15T08:05:16.6533989Z 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xb2
2021-09-15T08:05:16.6541411Z created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-09-15T08:05:16.6548456Z 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd
2021-09-15T08:05:16.6550128Z 
2021-09-15T08:05:16.6557242Z Error: The terraform-provider-azurerm_v2.76.0_x5.exe plugin crashed!
2021-09-15T08:05:16.6559640Z 
2021-09-15T08:05:16.6566048Z This is always indicative of a bug within the plugin. It would be immensely
2021-09-15T08:05:16.6573967Z helpful if you could report the crash with the plugin's maintainers so that it
2021-09-15T08:05:16.6582142Z can be fixed. The output above should help diagnose the issue.
2021-09-15T08:05:16.6585042Z

**Comment by BaraMike** [comment]
There seems to be already this issue and should be fixed with pull request

https://github.com/hashicorp/terraform-provider-azurerm/pull/13357

Sorry!
