### ISSUE TITLE
 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nubesFilius** [hashicorp/terraform-provider-azurerm#13405]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.66.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

eventgrid

### Debug Output

```
2021/09/17 20:29:23 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2021/09/17 20:29:23 [TRACE] vertex "module.eventgrid[0].azurerm_eventgrid_system_topic_event_subscription.kvsecretrotationsub[\"anviszat\"]": visit complete
2021/09/17 20:29:23 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/09/17 20:29:23 [TRACE] vertex "module.eventgrid[0].azurerm_eventgrid_system_topic_event_subscription.kvsecretrotationsub": dynamic subgraph encountered errors
2021/09/17 20:29:23 [TRACE] vertex "module.eventgrid[0].azurerm_eventgrid_system_topic_event_subscription.kvsecretrotationsub": visit complete
2021/09/17 20:29:23 [TRACE] vertex "module.eventgrid.azurerm_eventgrid_system_topic_event_subscription.kvsecretrotationsub (expand)": dynamic subgraph encountered errors
2021/09/17 20:29:23 [TRACE] vertex "module.eventgrid.azurerm_eventgrid_system_topic_event_subscription.kvsecretrotationsub (expand)": visit complete
2021/09/17 20:29:23 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/09/17 20:29:23 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" errored, so skipping
2021/09/17 20:29:23 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/09/17 20:29:23 [INFO] backend/local: plan operation completed
```

### Panic Output

```
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: panic: runtime error: invalid memory address or nil pointer dereference
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: [signal 0xc0000005 code=0x0 addr=0x18 pc=0x5639c15]
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: 
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: goroutine 8778 [running]:
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/eventgrid.resourceEventGridSystemTopicEventSubscriptionRead(0xc002b07180, 0x61719c0, 0xc001cbc000, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/eventgrid/eventgrid_system_topic_event_subscription_resource.go:238 +0x695
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000a1d880, 0x70c3dc8, 0xc002e59000, 0xc002b07180, 0x61719c0, 0xc001cbc000, 0x0, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1fb
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a1d880, 0x70c3dc8, 0xc002e59000, 0xc0008009a0, 0x61719c0, 0xc001cbc000, 0xc002812210, 0x0, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0002ad1a0, 0x70c3dc8, 0xc002e59000, 0xc002e59040, 0xc002e59000, 0xe8bf6a, 0x64803a0)
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x45b
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001824400, 0x70c3e70, 0xc002e59000, 0xc004c08060, 0xc001824400, 0xc0030273b0, 0xc002659ba0)
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x108
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x6639fc0, 0xc001824400, 0x70c3e70, 0xc0030273b0, 0xc001747f80, 0x0, 0x70c3e70, 0xc0030273b0, 0xc004a5c700, 0x65b)
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007a4540, 0x710de38, 0xc000297680, 0xc002930d80, 0xc0010dd110, 0xa5f3a70, 0x0, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: google.golang.org/grpc.(*Server).handleStream(0xc0007a4540, 0x710de38, 0xc000297680, 0xc002930d80, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005ce3c0, 0xc0007a4540, 0x710de38, 0xc000297680, 0xc002930d80)
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xb2
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
[DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5.exe: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd
```

### Expected Behaviour

Run a successful ```terraform plan```

### Actual Behaviour

```
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Unavailable desc = transport is closing
```
### Steps to Reproduce

1. ```terraform init```
2. ```terraform plan -var-file="path/to/tfvars" -target="module.eventgrid[0].azurerm_eventgrid_system_topic_event_subscription.kvsecretrotationsub" -no-color```

### Important Factoids

All our modules are dynamic and indexed.
Running targeted plans for other modules doesn't fail.
Running targeted other eventgrid subcomponents doesn't fail. For example:
    - ```terraform plan -var-file="tfvars" -target="module.eventgrid[0].azurerm_eventgrid_system_topic.kvsecretrotation" -no-color```
    - ```terraform plan -var-file="tfvars" -target="module.eventgrid[0].azurerm_monitor_diagnostic_setting.kvsecretrotationomslogs" -no-color```

**Comment by favoretti** [comment]
HI there and thank you for reporting this. Quick glance at the code suggests that there were some improvements to this in the later versions, would you mind retrying with the latest provider version please? The line crash points to right now is.. let's say it's fairly impossible that it crashes there. :)

**Comment by nubesFilius** [comment]
@favoretti Thanks for the input. A simple upgrade to our azurerm provider to 2.77 fixed our terraform plans issue.
