### ISSUE TITLE
Segmentation fault when destroying a shared image gallery

### ISSUE THREAD

**Issue by xpillons** [hashicorp/terraform-provider-azurerm#13770]
```
Stack trace from the terraform-provider-azurerm_v2.61.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x4606137]

goroutine 114 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute.resourceSharedImageGalleryDelete(0xc0013628c0, 0x53ff0a0, 0xc0002ce300, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute/shared_image_gallery_resource.go:174 +0x237
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0005b0140, 0xc000758fa0, 0xc0011fafa0, 0x53ff0a0, 0xc0002ce300, 0x40e101, 0xc001897200, 0x5dcd218)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:293 +0x4a6
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000a9480, 0xc0017f5a38, 0xc000758fa0, 0xc0011fafa0, 0x97214e0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000135bb8, 0x62e48b0, 0xc001773ad0, 0xc0013622a0, 0xc000135bb8, 0xc000e0eba0, 0x46d007)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:895 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x58e16a0, 0xc000135bb8, 0x62e48b0, 0xc001773ad0, 0xc0016dc420, 0x0, 0x62e48b0, 0xc001773ad0, 0xc001756400, 0x200)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000229340, 0x632a058, 0xc001b70000, 0xc000160a00, 0xc000c49020, 0x96de900, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000229340, 0x632a058, 0xc001b70000, 0xc000160a00, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000974130, 0xc000229340, 0x632a058, 0xc001b70000, 0xc000160a00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:857 +0x1fd

Error: The terraform-provider-azurerm_v2.61.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
terraform -v
Terraform v1.0.9
on linux_amd64
```

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
resource "azurerm_shared_image_gallery" "sig" {
  name                = "azhop_${random_string.resource_postfix.result}"
  location            = local.create_rg ? azurerm_resource_group.rg[0].location : data.azurerm_resource_group.rg[0].location
  resource_group_name = local.create_rg ? azurerm_resource_group.rg[0].name : data.azurerm_resource_group.rg[0].name
  description         = "Shared images for AZHOP"
}
```

### Steps to Reproduce

1. `terraform apply`
2. Add image definitions outside of TF
3. `terraform destroy`

### References

* #0000

**Comment by aristosvo** [comment]
@xpillons This issue is based on an older version of `azurerm`, and since then the `azurerm_shared_image_gallery` has seen some changes on this specific code path which should've fixed it already.

Do you see the same behaviour in the newest version of `azurerm`?
