### ISSUE TITLE
Enabling oms_agent breaks IMDS access

### ISSUE THREAD

**Issue by mibollma** [hashicorp/terraform-provider-azurerm#13826]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.6

### Affected Resource(s)
azurerm_kubernetes_cluster

### Terraform Configuration Files

```
resource "azurerm_kubernetes_cluster" "somecluster" {
  name                = "somecluster"
  location            = azurerm_resource_group.somegroup.location
  resource_group_name = azurerm_resource_group.somegroup.name
  dns_prefix          = "someprefix"

  default_node_pool {
    name            = "default"
    node_count      = 1
    vm_size         = "Standard_D2_v2"
    os_disk_size_gb = 30
    vnet_subnet_id  = azurerm_subnet.somesubnet.id
  }

  network_profile {
    network_plugin = "azure"
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true
  }

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.someworkspace.id
    }
  }
}
```

### Expected Behaviour
Enabling omg_agent has no impact on access to IMDS

### Actual Behaviour
As soon as the omg_agent addon is enabled, the pods are unable to access IMDS to retrieve their system assigned identity credentials. If I remove the addon, everything works as expected.

The error output looks like this:
```

2021-10-21 09:04:12.004Z ERROR c.a.i.implementation.IdentityClient - ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
2021-10-21 09:04:12.012Z ERROR c.a.i.ManagedIdentityCredential - Azure Identity => ERROR in getToken() call for scopes [https://monitor.azure.com//.default]: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
2021-10-21 09:04:12.014Z ERROR c.a.c.i.AccessTokenCache - Failed to acquire a new access token.
2021-10-21 09:04:12.020Z WARN  c.m.a.a.i.q.QuickPulsePingSender - Pinging live metrics endpoint: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established. (future warnings will be aggregated and logged once every 5 minutes)
com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
        at com.azure.identity.implementation.IdentityClient.lambda$authenticateToIMDSEndpoint$49(IdentityClient.java:1154)
        at reactor.core.publisher.MonoCallable.call(MonoCallable.java:92)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:174)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.MonoFromFluxOperator.subscribe(MonoFromFluxOperator.java:81)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
        at reactor.core.publisher.Mono.block(Mono.java:1703)
        at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulsePingSender.ping(QuickPulsePingSender.java:116)
        at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulseCoordinator.ping(QuickPulseCoordinator.java:107)
        at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulseCoordinator.run(QuickPulseCoordinator.java:63)
        at java.base/java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Mono.block(Mono.java:1704)
                ... 4 common frames omitted
```

**Comment by tombuildsstuff** [comment]
hey @mibollma 

As @aristosvo has mentioned unfortunately this appears to be an AKS bug rather than something specific to the Azure Provider - so for now I'd agree that it'd be good to open a bug [on the AKS repository](https://github.com/Azure/AKS/issues) where someone from that team should be able to take a look and confirm this. For the moment I'm going to close this out, but if the AKS Team recon that this is something specific to Terraform then we can reopen this and take another look.

Thanks!
