### ISSUE TITLE
Permission denied on msal_token_cache.bin.lockfile when using Azure CLI 2.30.0

### ISSUE THREAD

**Issue by Stolpe** [hashicorp/terraform-provider-azurerm#14143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.84.0
```
### Terraform Configuration Files

https://github.com/Stolpe/terraform-azurecli-repro

### Expected Behaviour

Normal output from a `terraform plan`

### Actual Behaviour

```
PS C:\Users\Per Stolpe\Desktop\terraform-repro> terraform plan
module.test_module.module.prod_module.azurerm_resource_group.resource_group: Refreshing state... [id=/subscriptions/(redacted)/resourceGroups/(redacted)]
azurerm_resource_group.test_resource_group: Refreshing state... [id=/subscriptions/(redacted)/resourceGroups/(redacted)]
azurerm_resource_group.prod_resource_group: Refreshing state... [id=/subscriptions/(redacted)/resourceGroups/(redacted)]
╷
│ Error: unable to get authorization token for storage endpoints: Error obtaining Authorization Token from the Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: The command failed with an unexpected error. Here is the traceback:
│ ERROR: [Errno 13] Permission denied: 'C:\\Users\\Per Stolpe\\.azure\\msal_token_cache.bin.lockfile'
│ Traceback (most recent call last):
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 74, in get_access_token
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 381, in get_raw_token
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 588, in _create_credential
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 182, in get_user_credential
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/msal_authentication.py", line 41, in __init__
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 
872, in get_accounts
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 
910, in _find_msal_accounts
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 53, in find
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/cache_lock.py", line 29, in __enter__
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/utils.py", line 199, in __enter__
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/utils.py", line 128, in acquire
│   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/utils.py", line 175, in _get_fh
\\msal_token_cache.bin.lockfile'                                               \\msal_token_cache.bi
│ To open an issue, please run: 'az feedback'
│
│   with module.test_module.provider["registry.terraform.io/hashicorp/azurerm"],                                                                              ,    
│   on modules\test\main.tf line 10, in provider "azurerm":
│   10: provider "azurerm" {
│
╵
```

### Steps to Reproduce

1. `terraform init`
2. Edit the three `main.tf` files to point to two real subscriptions and modify `import.ps1` to import real resource groups from those two subscriptions.
3. `./import.ps1`
4. `terraform plan`

I'm unable to reproduce this error every time using my repro pro, but now and then, the above error appears.

This error always occurs with my actual setup which uses multiple modules, which themselves use modules pointing to multiple subscriptions. Unfortunately, I'm unable to share this setup. I have filed an issue (linked below) with the Azure CLI team, and unless you think that this is worth working around, consider this more of a heads-up that this issue exists with version 2.30.0 of the Azure CLI.

### References

* https://github.com/Azure/azure-cli/issues/20273

**Comment by Stolpe** [comment]
This issue is fixed in version 2.32.0 of the Azure CLI, so I'll close this issue.
