### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing during terraform deployment

### ISSUE THREAD

**Issue by boboky** [hashicorp/terraform-provider-azurerm#14273]
While attempting to deploy azurerm_synapse_workspace using terraform version `0.13.6` and `azurerm: version = "~> 2.86.0"` I get the error below: 

```
module.synapse.azurerm_synapse_workspace.workspace: Still creating... [7m40s elapsed]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: [signal 0xc0000005 code=0x0 addr=0x0 pc=0x501505b]
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: 
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: goroutine 271 [running]:
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: github.com/hashicorp/terraform-provider-azurerm/internal/services/synapse.resourceSynapseWorkspaceCreate(0x0, {0x5480360, 0xc000cf6380})
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/synapse/synapse_workspace_resource.go:433 +0x175b
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000cc3bf0, {0x6515128, 0xc000d6fc80}, 0x2, {0x5480360, 0xc000cf6380})
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:318 +0x178
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001318fc0, {0x6515128, 0xc000d6fc80}, 0xc0012ba8f0, 0xc0001ad780, {0x5480360, 0xc000cf6380})
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x871
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000989fe0, {0x6515128, 0xc000d6fc80}, 0xc001326c80)
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0013d48c0, {0x65151d0, 0xc000c04030}, 0xc0029ebd70)
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:332 +0x6c
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x59a4480, 0xc0013d48c0}, {0x65151d0, 0xc000c04030}, 0xc001cbf920, 0x0)
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000df2540, {0x65646c0, 0xc0001a3b00}, 0xc001461200, 0xc000cd9410, 0xaa55440, 0x0)
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
2021-11-19T11:50:34.645Z [DEBUG] plugin.terraform-provider-azurerm_v2.86.0_x5.exe: google.golang.org/grpc.(*Server).handleStream(0xc000df2540, {0x65646c0, 0xc0001a3b00}, 0xc001461200, 0x0)

```

Please assist.

**Comment by aristosvo** [comment]
Hi @boboky! I'll close this as a duplicate for #14272 if you don't mind.

Thanks!
