### ISSUE TITLE
Add azurerm_api_management_backend to existing APIM resource via Terraform CLI fails with Plugin did not respond

### ISSUE THREAD

**Issue by jmburns** [hashicorp/terraform-provider-azurerm#14791]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.2
AzureRM v2.90.0

### Affected Resource(s)

* `azurerm_api_management_backend`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=2.90.0"
    }
  }
  cloud {
    # The name of your Terraform Cloud organization.
    organization = "***"

    # The name of the Terraform Cloud workspace to store Terraform state files in.
    workspaces {
      name = "api-dev-test1"
    }
  }
}

# Configure Microsoft Azure Provider
provider "azurerm" {
  features {}

  subscription_id             = "***"
  client_id                   = "***"
  tenant_id                   = "***"
  client_certificate_path     = "***"
  client_certificate_password = var.client_certificate_password
}

# Resource Group Data
data "azurerm_resource_group" "rg" {
  name = "rg-dev"
}

# Existing APIM Resource Data
data "azurerm_api_management" "apim_dev" {
  name                = "apim-dev"
  resource_group_name = data.azurerm_resource_group.rg.name
}

resource "azurerm_api_management_backend" "back_end_slot" {
  name                = "func-api-dev-test1"
  resource_group_name = data.azurerm_resource_group.rg.name
  api_management_name = data.azurerm_api_management.apim_dev.name
  protocol            = "http"
  url                 = "https://func-api-dev-test1.azurewebsites.net/api"

  credentials {
    certificate = []
    header      = {}
    query       = {}
  }

  tls {
    validate_certificate_chain = false
    validate_certificate_name  = false
  }
}
```

### Debug Output

[Terraform Output](https://gist.github.com/jmburns/575f363e695c74b1f201dd87e0c0cd55)

### Panic Output

Included in Terraform Output above.

### Expected Behaviour

Backend should have been successfully added to the APIM resource.

### Actual Behaviour

Terraform apply failed with output above.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -var 'client_certificate_password="***"' -auto-approve

### References

Did not find any related GitHub issues.

**Comment by tombuildsstuff** [comment]
Stack trace:

```
Stack trace from the terraform-provider-azurerm_v2.90.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 106 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement.expandApiManagementBackendCredentials({0xc000b293f0, 0x5dc86af, 0x6472c20})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/api_management_backend_resource.go:395 +0x405
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement.resourceApiManagementBackendCreateUpdate(0xc0010a2e00, {0x54f0ae0, 0xc00106b880})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/api_management_backend_resource.go:278 +0x5ec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0017a4420, {0x64bf8b8, 0xc0017746c0}, 0x2, {0x54f0ae0, 0xc00106b880})
```

**Comment by jmburns** [comment]
A workaround for this issue is to use the `base-url` attribute on the `<set-backend-service>` element in the APIM operation policy. 
```
<set-backend-service id="apim-generated-policy" base-url="https://func-api-dev-test1.azurewebsites.net/api" />
```
