### ISSUE TITLE
Error creating VNET Peering in VNET in another subscription

### ISSUE THREAD

**Issue by SPSamL** [hashicorp/terraform-provider-azurerm#15093]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 1.0.7
AzureRM version: 2.93.1, 2.90.0, 2.89.0

### Affected Resource(s)

* `azurerm_virtual_network_peering`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network_peering" "peering" {
      allow_forwarded_traffic      = true
      allow_gateway_transit        = true
      allow_virtual_network_access = true
      id                           = (known after apply)
      name                         = "VALID NAME"
      remote_virtual_network_id    = "VALID RESOURCE ID"
      resource_group_name          = "VALID RESOURCE GROUP NAME"
      use_remote_gateways          = (known after apply)
      virtual_network_name         = "VALID VNET NAME"
    }

```

### Debug Output

2022-01-24T18:40:20.905Z [WARN]  ValidateProviderConfig from "module.base-module.provider[\"registry.terraform.io/hashicorp/azurerm\"].VALID_PROVIDER_ALIAS" changed the config value, but that value is unused
2022-01-24T18:40:21.647Z [WARN]  ValidateProviderConfig from "module.base-module.provider[\"registry.terraform.io/hashicorp/azurerm\"]" changed the config value, but that value is unused
module.base-module.azurerm_virtual_network_peering.peering: Creating...
2022-01-24T18:40:25.488Z [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
╷
│ Error: Plugin did not respond
│ 
│   with module.base-module.azurerm_virtual_network_peering.peering,
│   on ..\..\modules\base\virtual-network.tf line 21, in resource "azurerm_virtual_network_peering" "peering":
│   21: resource "azurerm_virtual_network_peering" "peering" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.90.0_x5.exe plugin:

### Panic Output

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x52fbd38]

goroutine 85 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.retryVnetPeeringsClientCreateUpdate.func1()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/network/virtual_network_peering_resource.go:229 +0x298
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource/wait.go:27 +0x56
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource/state.go:110 +0x21f
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource/state.go:83 +0x1dd

Error: The terraform-provider-azurerm_v2.90.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behaviour

Creates VNET Peering.

### Actual Behaviour

Error as noted above.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- Running in Azure US Government
- Executing from a YAML pipeline in Azure DevOps Server
- This code worked, using 2.90.0, on 1/14/22.

**Comment by SPSamL** [comment]
Came to find out that there was a Resource Group Lock set on the remote VNET's RGP that was set to Read-only.  I was able to change that to Delete and it worked fine.

I would suggest finding a way to return a better error message.  I don't know if that's possible, but I wouldn't have figured that out had I not tried to create the peering manually (with the intent to import it to tfstate).
