### ISSUE TITLE
azurerm_virtual_machine_data_disk_attachment crashes if attaching are shared disk via a module

### ISSUE THREAD

**Issue by benpetz** [hashicorp/terraform-provider-azurerm#15436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.15.5
azurerm v2.96.0

### Affected Resource(s)

* `azurerm_virtual_machine_data_disk_attachment`

### Terraform Configuration Files

```hcl
#from within the module:
resource "azurerm_virtual_machine_data_disk_attachment" "attach_data_disk" {
  for_each           = {for disk in var.disks:disk.name => disk}
  managed_disk_id    = azurerm_managed_disk.data[each.key].id 
  virtual_machine_id = azurerm_windows_virtual_machine.virtual_machine.id
  lun                = each.value.lun
  caching            = "${each.value.type == "UltraSSD_LRS" ? "None" : each.value.max-shares > "0" ? "None" :"ReadWrite" }"
}

#output is done via:

output "managed_disk_lun" {

value = {for k, v in azurerm_virtual_machine_data_disk_attachment.attach_data_disk : k=> tomap({id=v.id, lun=v.lun}) }
}

#from within the testvm.tf:

resource "azurerm_virtual_machine_data_disk_attachment" "attach_shared_disks_cl2" {
  managed_disk_id    = module.cl1.managed_disk_lun.E.id
  virtual_machine_id = module.cl2.vm_id
  lun                = module.cl1.managed_disk_lun.E.lun
  caching            = "None"
}
```

### Debug Output

```hcl
### Panic Output
azurerm_virtual_machine_data_disk_attachment.attach_shared_disks_cl2: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with azurerm_virtual_machine_data_disk_attachment.attach_shared_disks_cl2,
│   on vm_module_test.tf line 62, in resource "azurerm_virtual_machine_data_disk_attachment" "attach_shared_disks_cl2":
│   62: resource "azurerm_virtual_machine_data_disk_attachment" "attach_shared_disks_cl2" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-azurerm_v2.96.0_x5 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47e9540]
goroutine 118 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/compute.retrieveDataDiskAttachmentManagedDisk(0x664a640, {0x5686660, 0xc0014d2a80}, {0xc0000742c0, 0xa9})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/compute/virtual_machine_data_disk_attachment_resource.go:304 +0x100
github.com/hashicorp/terraform-provider-azurerm/internal/services/compute.resourceVirtualMachineDataDiskAttachmentCreateUpdate(0xc0001bd900, {0x5686660, 0xc0014d2a80})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/compute/virtual_machine_data_disk_attachment_resource.go:117 +0x72b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0019bd6b0, {0x669d2d8, 0xc001cc7b00}, 0x2, {0x5686660, 0xc0014d2a80})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00046c8c0, {0x669d2d8, 0xc001cc7b00}, 0xc0006b5ba0, 0xc0001bd780, {0x5686660, 0xc0014d2a80})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002b6060, {0x669d2d8, 0xc001cc7b00}, 0xc00051aa00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000[298](https://git.dpd.de/azure-infrastructure/automation-testing-windows/win-infrastructure/-/jobs/434586#L298)500, {0x669d380, 0xc0019bc030}, 0xc00194a150)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5bd49a0, 0xc000298500}, {0x669d380, 0xc0019bc030}, 0xc001d1d680, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000236700, {0x66ecd18, 0xc0003ce480}, 0xc0019faa20, 0xc000c45a40, 0xacff1e0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000236700, {0x66ecd18, 0xc0003ce480}, 0xc0019faa20, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294
Error: The terraform-provider-azurerm_v2.96.0_x5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
Cleaning up project directory and file based variables
00:02
ERROR: Job failed: exit code 1

```

### Expected Behaviour
The exisisting shared disk of cl1 with maxhshares=2 value should be attached to the exisiting vm cl2.

### Actual Behaviour
Terraform Plan works fine, Terraform Apply crashes.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by myc2h6o** [comment]
Hi @benpetz After looking at the log, I found the error is from line 304 below, where `parsedId` is nil and panic when calling the  String() on it. The panic should be fixed by #15470.
https://github.com/hashicorp/terraform-provider-azurerm/blob/57c1717a6394b7e66feb14fe700d83d405ab734a/internal/services/compute/virtual_machine_data_disk_attachment_resource.go#L302-L304

However, since the code goes here where the parse for ManagedDiskID fails, I think there may be some issue with `managed_disk_id = module.cl1.managed_disk_lun.E.id`. After the above fixed is checked in and released, you shall be able to see the id from the output correctly. Before that, I think you can output `module.cl1.managed_disk_lun.E.id` to see if its a valid managed_disk_id

**Comment by benpetz** [comment]
Hi @myc2h6o thank you for the feedback. I think I have checked the output value already and it was valid from my point of view but I will check this again...

**Comment by myc2h6o** [comment]
Hi @benpetz v2.97.0 is released with the fix, you may want to upgrade to provider version and check the error in the output, it can have some explanation of why the parse fails

**Comment by benpetz** [comment]
Hi @myc2h6o thank you for the information and the fast Version release. We have now updated to the new version and were able to see with the new error message where our error was. For explanation:

with V2.97.0 Error message appeard at Terraform apply:

```hcl
Error: retrieving Managed Disk "/subscriptions/xxxxx/resourceGroups/xxx/providers/Microsoft.Compute/virtualMachines/xxxx/dataDisks/xxxxx": parsing Managed Disk ID "/subscriptions/xxxx/resourceGroups/win-base-rg/providers/Microsoft.Compute/virtualMachines/xxx/dataDisks/xxxx": ID was missing the `disks` element
```
we changed then the output var & the code in testvm.tf to the following:
```hcl
output "managed_disk_lun" {

value = {for k, v in azurerm_virtual_machine_data_disk_attachment.attach_data_disk : k=> tomap({id=v.id, lun=v.lun, managed_disk_id=v.managed_disk_id})}

}

resource "azurerm_virtual_machine_data_disk_attachment" "attach_shared_disks_cl2" {
  managed_disk_id    = module.cl1.managed_disk_lun.E.managed_disk_id
  virtual_machine_id = module.cl2.vm_id
  lun                = module.cl1.managed_disk_lun.E.lun
  caching            = "None"
}
```
this worked then for us sucessfully. Thanks again.
