### ISSUE TITLE
Error: The terraform-provider-azurerm_v2.97.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by cashman04** [hashicorp/terraform-provider-azurerm#15537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Running on TF cloud. TF version 1.0.0

### Affected Resource(s)

* `azurerm_v2.97.0_x5`

### Terraform Configuration Files

Unable to post TF code due to time it would take to redact all company information and configuration. 

### Description
TF plans are failing with this latest plugin version.  Nothing changed in our TF config files, I was just running a plan to detect drift.  Made small changes to app service configs to test if a change would work and get the same errors.

### Debug Output

```
Stack trace from the terraform-provider-azurerm_v2.97.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 867 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network/migration.NetworkWatcherFlowLogV0ToV1.UpgradeFunc.func1({0xae14020, 0x550fde0}, 0x7f94a97805b8, {0xc00145a438, 0x550fde0})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/network/migration/network_watcher_flow_log.go:146 +0x450
github.com/hashicorp/terraform-provider-azurerm/internal/tf/pluginsdk.StateUpgrades.func1({0x672af18, 0xc001fddf80}, 0xc0024dda70, {0x56fd5a0, 0xc001ad4000})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/tf/pluginsdk/state_upgrades.go:52 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).upgradeJSONState(0xc00124c918, {0x672af18, 0xc001fddf80}, 0x550fde0, 0xc00145a438, 0xc000c8dcc0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:424 +0x97
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).UpgradeResourceState(0xc00124c918, {0x672af18, 0xc001fddf80}, 0xc002410500)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:300 +0x365
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).UpgradeResourceState(0xc0001acd00, {0x672afc0, 0xc001536300}, 0xc001636c80)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:528 +0x2db
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_UpgradeResourceState_Handler({0x5c51ee0, 0xc0001acd00}, {0x672afc0, 0xc001536300}, 0xc0020d7e00, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:308 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000229340, {0x677b278, 0xc000b2d380}, 0xc002222fc0, 0xc000e1b5f0, 0xadd3360, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000229340, {0x677b278, 0xc000b2d380}, 0xc002222fc0, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.97.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Multiple errors in TF cloud like below:

```
Error: Request cancelled
with azurerm_storage_container.deadletter
on storage.tf line 33, in resource "azurerm_storage_container" "deadletter":
resource "azurerm_storage_container" "deadletter" {
The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
```

```
Error: Request cancelled
with azurerm_mssql_server_extended_auditing_policy.placeholder_primary
on db_pdmp.tf line 116, in resource "azurerm_mssql_server_extended_auditing_policy" "placeholder_primary":
resource "azurerm_mssql_server_extended_auditing_policy" "placeholder_primary" {
The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
```

**Comment by jackofallops** [comment]
Appears related to #15493.
