### ISSUE TITLE
terraform-provider-azurerm_v3.1.0_x5 plugin - panic: runtime error

### ISSUE THREAD

**Issue by swetharaot22** [hashicorp/terraform-provider-azurerm#16400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_v3.1.0_x5

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "resource_group" {
    name     = "${var.application}-${var.environment}-rg"
    location = var.location
    
    tags = var.tags
}


resource "azurerm_service_plan" "example" {
  name                = local.AppPlanName
  location            = var.location
  resource_group_name = azurerm_resource_group.resource_group.name
  os_type             = "Linux"
  sku_name            = var.webappskusize
  tags = var.tags
}

resource "azurerm_linux_web_app" "example_app" {
  name                    = local.example_appname
  location                = var.location
  resource_group_name     = azurerm_resource_group.resource_group.name
  service_plan_id         = azurerm_service_plan.example.id
  client_affinity_enabled = false
  

  tags = var.tags

  identity {
    type = "SystemAssigned"
  }

  site_config {
    always_on                 = true
    http2_enabled             = true
    use_32_bit_worker         = false
            
   }
}
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.1.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 533 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers.ExpandSiteConfigLinux({0xc00017d6c0, 0x3?, 0x6fc23ac00?}, 0x0, {0xc001464380, {0x63a73f0, 0xc00035f458}, 0xc00222d280, 0x0, {0x63a8ff0, ...}})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/appservice/helpers/web_app_schema.go:2931 +0x141d
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice.LinuxWebAppResource.Create.func1({0x63a5e10, 0xc002135440}, {0xc001464380, {0x63a73f0, 0xc00035f458}, 0xc00222d280, 0x0, {0x63a8ff0, 0xa24d7e8}})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/appservice/linux_web_app_resource.go:277 +0xbc5
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func2({0x63a5e10, 0xc002135440}, 0x1a3185c4557?, {0x5382d00?, 0xc001464380?})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:52 +0x163
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.diagnosticsWrapper.func1({0x63a5e10, 0xc002135440}, 0x53bb1e0?, {0x5382d00, 0xc001464380})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:185 +0xbe
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0003c5ce0, {0x63a5da0, 0xc00221e480}, 0x2?, {0x5382d00, 0xc001464380})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003c5ce0, {0x63a5da0, 0xc00221e480}, 0xc002258000, 0xc00222cc00, {0x5382d00, 0xc001464380})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:467 +0x6f1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000699698, {0x63a5da0, 0xc00221e480}, 0xc002140e60)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00012ae00, {0x63a5e48?, 0xc0022202a0?}, 0xc00061b880)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:603 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x58cea60?, 0xc00012ae00}, {0x63a5e48, 0xc0022202a0}, 0xc002134de0, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017d180, {0x63b6db0, 0xc0000f6900}, 0xc0021f6900, 0xc000c3fc50, 0xa20c980, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc00017d180, {0x63b6db0, 0xc0000f6900}, 0xc0021f6900, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x28a

Error: The terraform-provider-azurerm_v3.1.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Resources to be created with out error 

### Actual Behaviour

Panic attack : runtime error during terraform apply 

### Steps to Reproduce

terraform apply

**Comment by lonegunmanb** [comment]
Hi @swetharaot22 , I've tried to reproduce the issue with the following code and the plugin crashed as we expected:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "zjhe-f16400"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "zjhe-f16400"
  resource_group_name = azurerm_resource_group.example.name
  location            = "West Europe"
  os_type             = "Linux"
  sku_name            = "P1v2"
}

resource "azurerm_linux_web_app" "example" {
  name                = "zjhe-f16400"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {
    application_stack {
    }
    always_on         = true
    http2_enabled     = true
    use_32_bit_worker = false
  }
}
```

I'll submit a pr to fix it.
