### ISSUE TITLE
Terraform Initialization ##[error]You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by xhzuo** [hashicorp/terraform-provider-azurerm#16736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.9

### AzureRM Provider Version

2.4.0

### Affected Resource(s)/Data Source(s)

all

### Terraform Configuration Files

```hcl
- task: petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.Xpirit-Vsts-Release-Terraform.Terraform@2
              displayName: 'Terraform Initialization'
              inputs:
                TemplatePath: 'steps/deploy-infra'
                Arguments: 'init'
                InstallTerraform: true
                Version: $(terraformVersion)
                UseAzureSub: true
                ConnectedServiceNameARM: ${serviceEndpointName }
```

### Debug Output/Panic Output

```shell
We have the above Terraform Initialization step that worked well before. And begin from yesterday. this failed. See part of the error log. Any suggestions please?


##[debug]Env:INPUT_VERSION: '0.14.9'
##[debug]GET https://releases.hashicorp.com/terraform/ with 0-byte payload
##[debug]received -1-byte response of content type text/html
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]+             ForEach-Object {
##[debug]+             ~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
##[debug]    + FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.Commands.ForEachObjectCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at Install-Terraform, D:\a\_tasks\Terraform_31f040e5-e040-4336-878a-59a493289794\2.4.0\Terraform.ps1: line 47
##[debug]at <ScriptBlock>, D:\a\_tasks\Terraform_31f040e5-e040-4336-878a-59a493289794\2.4.0\Terraform.ps1: line 215
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
##[debug]   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
##[debug]   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
##[debug]   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
##[debug]   at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
##[error]You cannot call a method on a null-valued expression.
##[debug]Processed: ##vso[task.logissue type=error]You cannot call a method on a null-valued expression.
```

**Comment by mybayern1974** [comment]
@xhzuo , could you please provide more contexts, including what terraform config files you are using thus we could troubleshoot by knowing what specific Azure services you are interacting with by terraform. In addition, both the terraform version and azurerm provider version you are using is quite old, you can try to upgrade them to `>1.0.0` and `>3.0.0`, separately and see whether things could work.

**Comment by tombuildsstuff** [comment]
hi @xhzuo 

Thanks for opening this issue.

Unfortunately this isn't an issue with the Provider but with the Azure DevOps Terraform integration, which needs to be updated to account for the changes made to the Release API recently - so I'd suggest reaching out to whoever manages that extension within Azure DevOps who should be able to dig into that.

Thanks!

**Comment by xhzuo** [comment]
Thank you for the reply. Will check.
