### ISSUE TITLE
terraform-provider-azurerm_v3.3.0 crashed with segmentation fault

### ISSUE THREAD

**Issue by abhijaiswal123** [hashicorp/terraform-provider-azurerm#16829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Terraform terraform-provider-azurerm_v3.3.0_x5 plugin crashed with segmentation fault in runtime.

### Terraform Version

1.1.8

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

cosmos

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.3.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4603dbd]

goroutine 115 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/cosmos.flattenAzureRmCosmosDBAccountGeoLocations(0xc000d017c0)
	github.com/hashicorp/terraform-provider-azurerm/internal/services/cosmos/cosmosdb_account_resource.go:1366 +0x5d
github.com/hashicorp/terraform-provider-azurerm/internal/services/cosmos.resourceCosmosDbAccountRead(0xc001b6fc80, {0x53da680?, 0xc0018b1500?})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/cosmos/cosmosdb_account_resource.go:1016 +0xf89
github.com/hashicorp/terraform-provider-azurerm/internal/services/cosmos.resourceCosmosDbAccountCreate(0xc001b6fc80, {0x53da680?, 0xc0018b1500})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/cosmos/cosmosdb_account_resource.go:741 +0x1fbb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc001ca8d20?, {0x640ee40?, 0xc001c10980?}, 0x2?, {0x53da680?, 0xc0018b1500?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00096a1c0, {0x640ee40, 0xc001c10980}, 0xc001c25040, 0xc001b6f780, {0x53da680, 0xc0018b1500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x6f1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000c5a0a8, {0x640ee40, 0xc001c10980}, 0xc00011cbe0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000c55280, {0x640eee8?, 0xc001c16600?}, 0xc000cc59d0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x592b860?, 0xc000c55280}, {0x640eee8, 0xc001c16600}, 0xc001b51080, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000144e00, {0x641ff00, 0xc000193c80}, 0xc001b2db00, 0xc0011abfb0, 0xa24b5e0, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000144e00, {0x641ff00, 0xc000193c80}, 0xc001b2db00, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1617 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.39.0/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.39.0/server.go:938 +0x28a

Error: The terraform-provider-azurerm_v3.3.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2022-05-16T17:59:26.279Z [DEBUG] provider: plugin exited
```

**Comment by lonegunmanb** [comment]
Hi @abhijaiswal123 , would you please give us a sample code that can reproduce this issue so we can try a fix? Thanks.
