### ISSUE TITLE
azurerm_synapse_workspace_aad_admin and azurerm_synapse_workspace_sql_aad_admin are modifying the same attribute

### ISSUE THREAD

**Issue by fgarcia-cnb** [hashicorp/terraform-provider-azurerm#16853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.7

### AzureRM Provider Version

2.95.0

### Affected Resource(s)/Data Source(s)

azurerm_synapse_workspace_aad_admin and azurerm_synapse_workspace_sql_aad_admin

### Terraform Configuration Files

```hcl
resource "azurerm_synapse_workspace_aad_admin" "synapse_aad_admin" {
  count                = var.resource_count
  synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace[count.index].id
  login                = var.aad_admin_login
  object_id            = var.aad_admin_object_id
  tenant_id            = data.azurerm_client_config.current.tenant_id

  depends_on = [azurerm_synapse_workspace_key.synapse_workspace_key]
}

resource "azurerm_synapse_workspace_sql_aad_admin" "synapse_sql_aad_admin" {
  count                = var.resource_count
  synapse_workspace_id = azurerm_synapse_workspace.synapse_workspace[count.index].id
  login                = var.sql_aad_admin_login
  object_id            = var.sql_aad_admin_object_id
  tenant_id            = data.azurerm_client_config.current.tenant_id

  depends_on = [azurerm_synapse_workspace_key.synapse_workspace_key]
}
```

### Debug Output/Panic Output

```shell
resources appear to be modifying the same values. if var.sql_aad_admin_object_id is different than var.aad_admin_object_id, they will keep trying to overwrite each other on every run
```

### Expected Behaviour

workspace aad admin should set`https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Synapse/workspaces/{workspaceName}/administrators/activeDirectory?api-version=2021-06-01`

sql aad admin should set
`https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Synapse/workspaces/{workspaceName}/sqlAdministrators/activeDirectory?api-version=2021-06-01`

### Actual Behaviour

resources appear to be modifying the same values. if var.sql_aad_admin_object_id is different than var.aad_admin_object_id, they will keep trying to overwrite each other on every run

**Comment by fgarcia-cnb** [comment]
so i commented out the synapse_sql_aad_admin resource, and the apply deleted it successfully... but since its pointing to the same data the synapse_aad_admin resource is pointing to, it completely invalidated my state file. Subsequent runs all errored out with:

```Stack trace from the terraform-provider-azurerm_v2.95.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x51c99d0]

goroutine 96 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/synapse.resourceSynapseWorkspaceAADAdminRead(0xc000126900, {0x5657420, 0xc000b40380})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/synapse/synapse_workspace_aad_admin_resource.go:120 +0x550
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x5f45110, {0x6663c18, 0xc00193e380}, 0x24, {0x5657420, 0xc000b40380})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0006d7c00, {0x6663c18, 0xc00193e380}, 0xc00149a5b0, {0x5657420, 0xc000b40380})
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0006da4f8, {0x6663c18, 0xc00193e380}, 0xc00193e400)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000127000, {0x6663cc0, 0xc001782510}, 0xc0014860c0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x5ba1ea0, 0xc000127000}, {0x6663cc0, 0xc001782510}, 0xc001486060, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000227340, {0x66b3618, 0xc0002f4000}, 0xc001a0e240, 0xc000b6de30, 0xaca4e90, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000227340, {0x66b3618, 0xc0002f4000}, 0xc001a0e240, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.95.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue
```

with a ton of `The plugin.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.` errors 

I had to run a terraform state rm command to remove the `synapse_aad_admin`  resource

**Comment by ms-henglu** [comment]
Hi @fgarcia-cnb ,

I've confirmed it with service team, that both sqlAdministrators and the administrators are the same proxy-resource resource type and have the same functionality. So you can use one of them.
