### ISSUE TITLE
provider-crash: Dropping WAF from app gw 

### ISSUE THREAD

**Issue by davidkarlsen** [hashicorp/terraform-provider-azurerm#17212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
when changing from:


waf_configuration = {
    enabled            = true
    firewall_mode      = "Detection"
    rule_set_version   = "3.2"
    request_body_check = false
    disabled_rule_group = [ //many rules]
  }
```

to

```
waf_configuration = {
    enabled            = false
    firewall_mode      = "Detection"
    rule_set_version   = "3.2"
    request_body_check = false
  }
```
it crashes as described
```


### Debug Output/Panic Output

```shell
with module.application-gateway.azurerm_application_gateway.appgw,
  on .terraform/modules/application-gateway/main.tf line 1, in resource "azurerm_application_gateway" "appgw":
   1: resource "azurerm_application_gateway" "appgw" {
The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
Releasing state lock. This may take a few moments...
Stack trace from the terraform-provider-azurerm_v3.9.0_x5 plugin:
panic: runtime error: index out of range [0] with length 0
goroutine 117 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.expandApplicationGatewayWafConfig(0x672c320?)
	github.com/hashicorp/terraform-provider-azurerm/internal/services/network/application_gateway_resource.go:4446 +0x59b
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.resourceApplicationGatewayUpdate(0xc001b36080, {0x5676020?, 0xc000eb1180})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/network/application_gateway_resource.go:1915 +0x1a78
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000eb7a70?, {0x6739ff8?, 0xc00193f600?}, 0x24?, {0x5676020?, 0xc000eb1180?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:363 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001044a80, {0x6739ff8, 0xc00193f600}, 0xc0022da750, 0xc0027e6000, {0x5676020, 0xc000eb1180})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:475 +0x53a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003f36f8, {0x6739ff8, 0xc00193f600}, 0xc0020ce960)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000134980, {0x673a0a0?, 0xc0022b8030?}, 0xc000cf5420)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5bfbe40?, 0xc000134980}, {0x673a0a0, 0xc0022b8030}, 0xc001952840, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017ce00, {0x674b458, 0xc000349980}, 0xc0019450e0, 0xc000ce15f0, 0xa774a00, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc00017ce00, {0x674b458, 0xc000349980}, 0xc0019450e0, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1617 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.39.0/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.39.0/server.go:938 +0x28a
```
```


### Expected Behaviour

should not crash

### Actual Behaviour

crashes

### Steps to Reproduce

see description

### Important Factoids

_No response_

### References

_No response_

**Comment by davidkarlsen** [comment]
Ah, seems like a duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/17207 (which has a PR).
