### ISSUE TITLE
Plugin crash if cookies_condition is used on azurerm_cdn_frontdoor_rule

### ISSUE THREAD

**Issue by comspace-lfr** [hashicorp/terraform-provider-azurerm#18370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.1.7"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.22.0"
    }
  }
}

resource "azurerm_cdn_frontdoor_rule_set" "rs" {
  name                     = "test"
  cdn_frontdoor_profile_id = var.frontdoor_id
}

resource "azurerm_cdn_frontdoor_rule" "rule" {
  name                      = "rule"
  cdn_frontdoor_rule_set_id = azurerm_cdn_frontdoor_rule_set.rs.id
  order                     = 1
  behavior_on_match         = "Stop"

  conditions {
    cookies_condition {
      cookie_name  = "some_cookie"
      operator     = "Equal"
      transforms   = ["Lowercase"]
      match_values = ["some value"]
    }
  }

  actions {
    url_redirect_action {
      redirect_type        = "Found"
      destination_hostname = var.custom_hostname
      redirect_protocol    = "MatchRequest"
      destination_path     = "/test"
    }
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Plugin did not respond
│
│   with module.website.azurerm_cdn_frontdoor_rule.rule,
│   on ..\..\modules\website\main.tf line 83, in resource "azurerm_cdn_frontdoor_rule" "rule":
│   83: resource "azurerm_cdn_frontdoor_rule" "rule" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.22.0_x5.exe plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 101 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/frontdoorruleconditions.ExpandCdnFrontDoorCookiesCondition({0xc001702da0, 0x1, 0x6aba192?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/frontdoorruleconditions/cdn_frontdoor_rule_conditions.go:812 +0x785
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.expandFrontdoorDeliveryRuleConditions({0xc001702d70, 0x1, 0x722ba40?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_rule_resource.go:884 +0x7d2
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.resourceCdnFrontDoorRuleCreate(0x0?, {0x60e1740?, 0xc0001ea380})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_rule_resource.go:637 +0x65c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x72357c8?, {0x72357c8?, 0xc001898cc0?}, 0xd?, {0x60e1740?, 0xc0001ea380?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000a74c40, {0x72357c8, 0xc001898cc0}, 0xc001a8e750, 0xc001897f00, {0x60e1740, 0xc0001ea380})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0005290e0, {0x72357c8?, 0xc001898c00?}, 0xc001a83ef0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0004bf180, {0x72357c8?, 0xc0018984b0?}, 0xc0008d78f0)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:813 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x66d0680?, 0xc0004bf180}, {0x72357c8, 0xc0018984b0}, 0xc00195a240, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000236c40, {0x72470d8, 0xc00122c4e0}, 0xc00182b440, 0xc00128a5a0, 0xb2fcfc0, 0x0)
        google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000236c40, {0x72470d8, 0xc00122c4e0}, 0xc00182b440, 0x0)
        google.golang.org/grpc@v1.47.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.47.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.47.0/server.go:920 +0x28a

Error: The terraform-provider-azurerm_v3.22.0_x5.exe plugin crashed!
```

### Actual Behaviour

An empty rule set is created. The rule with a cookies_condition is missing / not created.
If cookies_condition is replaced with a request_header_condition the rule is created successfully.

### Important Factoids

'azurerm' backend is used for state management.

**Comment by Amier3** [comment]
@comspace-lfr 

Thanks for bringing this to our attention. I was able to replicate the crash so we'll investigate this and figure out what's going on here 👁️

**Comment by WodansSon** [comment]
@comspace-lfr Thanks for reporting this issue and @Amier3 for bringing it to my attention 🙂 I have checked in this [commit](https://github.com/hashicorp/terraform-provider-azurerm/pull/18231/commits/43abd6d5072bb025419038c82570cc6b908d2692) that will fix this issue.
