### ISSUE TITLE
Importing Frontdoor rule causes panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Gerthum** [hashicorp/terraform-provider-azurerm#18814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.27.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_rule_set" "cors" {
  name                     = "CORS"
  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.front_door.id
}
resource "azurerm_cdn_frontdoor_rule" "access_control_allow_origin" {
  depends_on = [azurerm_cdn_frontdoor_origin_group.shell , azurerm_cdn_frontdoor_origin.shell]

  name                      = "AccessControlAllowOrigin"
  cdn_frontdoor_rule_set_id = azurerm_cdn_frontdoor_rule_set.cors.id
  order                     = 1
  behavior_on_match         = "Continue"

  actions {
    route_configuration_override_action {
      cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.shell.id
      forwarding_protocol           = "HttpsOnly"
      query_string_caching_behavior = "IncludeSpecifiedQueryStrings"
      query_string_parameters       = ["foo", "clientIp={client_ip}"]
      compression_enabled           = true
      cache_behavior                = "OverrideIfOriginMissing"
      cache_duration                = "365.23:59:59"
    }

    url_redirect_action {
      redirect_type        = "PermanentRedirect"
      redirect_protocol    = "MatchRequest"
      query_string         = "clientIp={client_ip}"
      destination_path     = "/exampleredirection"
      destination_hostname = "contoso.com"
      destination_fragment = "UrlRedirect"
    }
  }

  conditions {
    host_name_condition {
      operator         = "Equal"
      negate_condition = false
      match_values     = ["www.contoso.com", "images.contoso.com", "video.contoso.com"]
      transforms       = ["Lowercase", "Trim"]
    }

    is_device_condition {
      operator         = "Equal"
      negate_condition = false
      match_values     = ["Mobile"]
    }

    post_args_condition {
      post_args_name = "customerName"
      operator       = "BeginsWith"
      match_values   = ["J", "K"]
      transforms     = ["Uppercase"]
    }

    request_method_condition {
      operator         = "Equal"
      negate_condition = false
      match_values     = ["DELETE"]
    }

    url_filename_condition {
      operator         = "Equal"
      negate_condition = false
      match_values     = ["media.mp4"]
      transforms       = ["Lowercase", "RemoveNulls", "Trim"]
    }
  }
}
```

### Debug Output/Panic Output

```shell
Trying to run an import an an existing resources produces the following error:

Stack trace from the terraform-provider-azurerm_v3.27.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4672065]

goroutine 175 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.flattenRuleSetResourceArray(0xc0024cf950)
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_route_resource.go:617 +0xc5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000595180, {0x6ab8e48, 0xc002523e00}, 0xc0018f7ba0, {0x59422e0, 0xc0005ecc00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000044f8, {0x6ab8e48?, 0xc002523d40?}, 0xc00253c580)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000ce0320, {0x6ab8e48?, 0xc002523620?}, 0xc0018ef200)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:747 +0x41e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x5f40000?, 0xc000ce0320}, {0x6ab8e48, 0xc002523620}, 0xc0018ef1a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000130a80, {0x6acaaa0, 0xc00163c000}, 0xc0025266c0, 0xc0015c9bf0, 0xabb6830, 0x0)
        google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000130a80, {0x6acaaa0, 0xc00163c000}, 0xc0025266c0, 0x0)
        google.golang.org/grpc@v1.47.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.47.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.47.0/server.go:920 +0x28a

Error: The terraform-provider-azurerm_v3.27.0_x5.exe plugin crashed!
```

### Expected Behaviour

The resource should be imported. 

### Steps to Reproduce

terraform import azurerm_cdn_frontdoor_rule.access_control_allow_origin <resource id>

**Comment by Gerthum** [comment]
Re-testing and will log new
