### ISSUE TITLE
Azurerm (v3.11.0) plugin crashing when trying to create app configuration key

### ISSUE THREAD

**Issue by amantur** [hashicorp/terraform-provider-azurerm#19398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.11

### AzureRM Provider Version

3.11.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
resource "azurerm_app_configuration" "appconfig" {
  name                = var.app_conf_name
  resource_group_name = var.resource_group_name
  location            = var.location
  sku                 = var.sku

  identity {
    type = "SystemAssigned"
  }

  tags = var.tags
}

resource "azurerm_app_configuration_key" "appconfig_key" {
  configuration_store_id = var.appconfig_id
  key                    = var.key_name
  label                  = var.label
  value                  = var.value
  locked                 = var.is_locked
  type                   = var.type
  content_type           = var.kv_content_type
  vault_key_reference    = var.vault_key_reference

  tags = var.tags
}

########
locals{
local_keys = [
    {
      type  = "kv"
      name  = "EventHubConsumerGroup"
      value = "notifications"
    },   
    {
      type        = "vault"
      name        = "EventHubConnectionString"
      secret_name = "EventHubConnectionString"
    }
]
tags = {"env":"dev"}
}

module "cnf_mytest" {
  source = "./modules/app_configuration"

  app_conf_name       = var.config_svc_name
  resource_group_name = var.resource_group_name
  sku                 = "standard"

  tags = local.tags
}

module "cnf_keys" {
  source = "./modules/app_configuration_key"

  for_each = { for k in local.local_keys : k.name => k }

  appconfig_id = module.cnf_mytest.app_configuration_output.id

  key_name = each.key
  label    = try(each.value.label, "")

  type            = each.value.type
  value           = each.value.type == "kv" ? each.value.value : null
  kv_content_type = each.value.type == "kv" ? try(each.value.content_type, null) : null

  is_locked = try(each.value.locked, false)

  vault_key_reference = each.value.type == "kv" ? null : "myexamplekv.vault.azure.net/secrets/${each.value.secret_name}"

  tags = local.tags
}
```

### Debug Output/Panic Output

```shell
Error: Plugin did not respond

  with module.cnf_keys["EventHubConnectionString"].azurerm_app_configuration_key.appconfig_key,
  on modules/app_configuration_key/main.tf line 1, in resource "azurerm_app_configuration_key" "appconfig_key":
   1: resource "azurerm_app_configuration_key" "appconfig_key" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
contain more details.

Error: Plugin did not respond

  with module.cnf_keys["EventHubConsumerGroup"].azurerm_app_configuration_key.appconfig_key,
  on modules/app_configuration_key/main.tf line 1, in resource "azurerm_app_configuration_key" "appconfig_key":
   1: resource "azurerm_app_configuration_key" "appconfig_key" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
contain more details.



panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x40d31eb]

goroutine 174 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/appconfiguration.KeyResource.Create.func1({0x640eeb0, 0xc0020a6540}, {0xc001bf8000, {0x6410490, 0xc00000d9b0}, 0xc0020a8480, 0x0, {0x6412090, 0xa28c448}})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/appconfiguration/app_configuration_key_resource.go:142 +0x46b
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func2({0x640eeb0, 0xc0020a6540}, 0x1a3185c3f98?, {0x53da680?, 0xc001bf8000?})
	github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:52 +0x163
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.diagnosticsWrapper.func1({0x640eeb0, 0xc0020a6540}, 0x5412f80?, {0x53da680, 0xc001bf8000})
	github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:185 +0xbe
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001b2a80, {0x640ee40, 0xc0020a4440}, 0x2?, {0x53da680, 0xc001bf8000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001b2a80, {0x640ee40, 0xc0020a4440}, 0xc002075860, 0xc0020a8300, {0x53da680, 0xc001bf8000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x6f1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00022d4a0, {0x640ee40, 0xc0020a4440}, 0xc0015a7040)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0013ac100, {0x640eee8?, 0xc00207d440?}, 0xc00205d730)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x592b860?, 0xc0013ac100}, {0x640eee8, 0xc00207d440}, 0xc0020a6060, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000197180, {0x641ff00, 0xc000b79c80}, 0xc002090d80, 0xc0013a7320, 0xa24b5e0, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000197180, {0x641ff00, 0xc000b79c80}, 0xc002090d80, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1617 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.39.0/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.39.0/server.go:938 +0x28a

Error: The terraform-provider-azurerm_v3.3.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Expected to create configuration keys.

### Actual Behaviour

Created App Configuration instance but failed on creating configuration keys.

### Important Factoids

Running in Azure DevOps (yaml pipeline, bash task) in Australia East data center.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. After tested with latest azurerm provider version and below tf config that is similar with yours, seems I cannot repro this issue. Could you try latest azurerm provider and tf config to see if the issue still exists?

tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-appconfig-test01"
  location = "westeurope"
}

data "azurerm_client_config" "test" {
}

resource "azurerm_role_assignment" "test" {
  scope                = azurerm_resource_group.test.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.test.object_id
}

resource "azurerm_app_configuration" "test" {
  name                = "testacc-appconftest01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "standard"
  identity {
    type = "SystemAssigned"
  }
  depends_on = [
    azurerm_role_assignment.test,
  ]

  tags = {
    ENV2 = "test2"
  }
}

resource "azurerm_key_vault" "example" {
  name                       = "a-v-test01"
  location                   = azurerm_resource_group.test.location
  resource_group_name        = azurerm_resource_group.test.name
  tenant_id                  = data.azurerm_client_config.test.tenant_id
  sku_name                   = "premium"
  soft_delete_retention_days = 7

  access_policy {
    tenant_id = data.azurerm_client_config.test.tenant_id
    object_id = data.azurerm_client_config.test.object_id

    key_permissions = [
      "Create",
      "Get",
    ]

    secret_permissions = [
      "Set",
      "Get",
      "Delete",
      "Purge",
      "Recover"
    ]
  }
}

resource "azurerm_key_vault_secret" "example" {
  name         = "acctest-secret-test01"
  value        = "szechuan"
  key_vault_id = azurerm_key_vault.example.id
}

resource "azurerm_app_configuration_key" "test" {
  configuration_store_id = azurerm_app_configuration.test.id
  key                    = "acctest-ackey-test01"
  label                  = "acctest-ackeylabel-test01"
  locked                 = false
  type                   = "vault"
  vault_key_reference    = azurerm_key_vault_secret.example.id

  tags = {
    ENV = "test"
  }
}
```

**Comment by amantur** [comment]
Hi @neil-yechenwei ,
Tried again. I think the issue is private endpoint. When there is a private endpoint it is causing problem. I'm running it again and trying to ascertain that DNS entries are done properly, though they should be already there when private endpoint is created.
