### ISSUE TITLE
Empty Authentication block in PostgreSQL Flexible Server will cause panic output

### ISSUE THREAD

**Issue by ArnavBhutaniLithia** [hashicorp/terraform-provider-azurerm#19752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.36.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "pg-server" {
  name                = "postgre"
  resource_group_name = "postgre-rg"
  sku_name            = "GP_Standard_D2ds_v4"

  location                     = "westus3"
  geo_redundant_backup_enabled = "false"
  zone                         = "1"

  high_availability {
    mode = "ZoneRedundant"
  }

  delegated_subnet_id = data.azurerm_subnet.postgres-spoke-subnet.id
  private_dns_zone_id = data.azurerm_private_dns_zone.psql-dns-zone.id

  version    = "11"
  storage_mb = "32768"

  administrator_login    = "admin"
  administrator_password = "Somepassword1"
  authentication {} # If this is commented out, the apply runs fine.

  backup_retention_days = "7"
  maintenance_window {
    start_minute = 0
    start_hour   = 2
    day_of_week  = 1
  }

  tags = {
    test = "test"
  }
}
```
```


### Debug Output/Panic Output

```shell
module.pg-server.azurerm_postgresql_flexible_server.pg-server: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with module.pg-server.azurerm_postgresql_flexible_server.pg-server,
│   on ../../modules/postgres_flex_db/server.tf line 18, in resource "azurerm_postgresql_flexible_server" "pg-server":
│   18: resource "azurerm_postgresql_flexible_server" "pg-server" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.36.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 74 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres.expandFlexibleServerAuthConfig(...)
        github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres/postgresql_flexible_server_resource.go:761
github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres.resourcePostgresqlFlexibleServerCreate(0x0?, {0x68401e0?, 0xc001e60400})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres/postgresql_flexible_server_resource.go:353 +0x2025
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x7a93b00?, {0x7a93b00?, 0xc0010a06f0?}, 0xd?, {0x68401e0?, 0xc001e60400?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0014a29a0, {0x7a93b00, 0xc0010a06f0}, 0xc0019e48f0, 0xc00227a900, {0x68401e0, 0xc001e60400})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00021ca50, {0x7a93b00?, 0xc0010a05d0?}, 0xc0005fa320)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0013a4140, {0x7a93b00?, 0xc00104fce0?}, 0xc00151c070)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x6ee83c0?, 0xc0013a4140}, {0x7a93b00, 0xc00104fce0}, 0xc00151c000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ec000, {0x7aa5880, 0xc000564680}, 0xc0019d6000, 0xc001289350, 0xbd20020, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0000ec000, {0x7aa5880, 0xc000564680}, 0xc0019d6000, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.36.0_x5 plugin crashed!
```

### Expected Behaviour

Some form of error saying that the authentication block can't be empty.

### Actual Behaviour

Stack trace and panic output.

### Steps to Reproduce

1. terraform apply

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Actually, if you don't need `authentication`, you just need to remove it from tf config.
