### ISSUE TITLE
Service Fabric settings invalid value for type boolean

### ISSUE THREAD

**Issue by steve-hawkins** [hashicorp/terraform-provider-azurerm#1988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.15.0

### Affected Resource(s)

* azurerm_service_fabric_cluster

### Terraform Configuration Files

```hcl
  fabric_settings {
    name = "ClusterManager"
    parameters = {
      EnableDefaultServicesUpgrade = true
    }
  }
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Section - ClusterManager
Parameter - EnableDefaultServicesUpgrade
Value - True

### Actual Behavior

Section - ClusterManager
Parameter - EnableDefaultServicesUpgrade
Value - 1

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The Terraform execution completes successfully, the cluster even successfully accepts the value of `1` instead of `True`, however the Service Fabric agents on the VMSS instances error with the following:-

```
2018/09/27-09:04:45.567,Error,680,FabricDeployer.FabricDeployer,System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.ArgumentException: Error occurs in section ClusterManager, entry [EnableDefaultServicesUpgrade, System.Fabric.Management.WindowsFabricValidator.WindowsFabricSettings+SettingsValue]. The error message is System.ArgumentException: Section ClusterManager name EnableDefaultServicesUpgrade type bool value 1 parsing failed with exception System.FormatException: 1 is not a valid value for Boolean. ---> System.FormatException: String was not recognized as a valid Boolean.
	   at System.Boolean.Parse(String value)
	   at System.ComponentModel.BooleanConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
	   --- End of inner exception stack trace ---
	   at System.ComponentModel.BooleanConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
	   at System.Fabric.Management.WindowsFabricValidator.WindowsFabricSettings.VerifyValue[T](String section, String name, String type, String value)
	   at System.Fabric.Management.WindowsFabricValidator.WindowsFabricSettings.ThrowOnException(String section, String name, String type, String value, Exception exception)
	   at System.Fabric.Management.WindowsFabricValidator.WindowsFabricSettings.VerifyValue[T](String section, String name, String type, String value)
	   at System.Fabric.Management.WindowsFabricValidator.WindowsFabricSettings.ValidateSettingsNamesAndTypes()
	   at System.Fabric.Management.WindowsFabricValidator.WindowsFabricSettings.ValidateSettingsNamesAndTypes()
	   at System.Fabric.Management.WindowsFabricValidator.WindowsFabricSettings..ctor(ClusterManifestType manifest, Boolean skipValidation)
	   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
	   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
	   at System.Fabric.FabricDeployer.ConfigureOperation.OnExecuteOperation(DeploymentParameters parameters, ClusterManifestType clusterManifest, Infrastructure infrastructure)
	   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
	   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace)
	   at System.Fabric.FabricDeployer.Program.Main(String[] args)

```

### Workaround

```hcl
  fabric_settings {
    name = "ClusterManager"
    parameters = {
      EnableDefaultServicesUpgrade = "true"
    }
  }
```

**Comment by Lucretius** [comment]
The code that handles this is here: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_service_fabric_cluster.go#L861  and it looks like this is because values always get converted to strings.  Given that [the possible list of fabric settings](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings) is huge, and that the Azure SDK for Go does not expose any way to determine the type of the setting (nor does go lend itself well to any sort of dynamic type reflection even if it did - as far as I am aware) if that workaround works, we may be best just altering the documentation to specify that all fabric setting values need to be strings.  @katbyte @tombuildsstuff  what do you two think?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
