### ISSUE TITLE
Terraform crash during Azure backend lock release

### ISSUE THREAD

**Issue by ScottS-byte** [hashicorp/terraform-provider-azurerm#20463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.8 on darwin_arm64

### AzureRM Provider Version

3.43.0

### Affected Resource(s)/Data Source(s)

Releasing state lock. This may take a few moments...

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.3.0, < 1.4.0"
  backend "azurerm" {
    resource_group_name  = "TheName"
    storage_account_name = "thename1234567"
    container_name       = "statename"
    key                  = "dev/terraform.tfstate"
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.35.0, < 4.0.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0.4"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.17.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.4.3"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy       = false
      purge_soft_deleted_keys_on_destroy = false
      recover_soft_deleted_key_vaults    = false
    }
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

provider "kubernetes" {
  config_path = "~/.kube/config"
}

provider "random" {}
```

### Debug Output/Panic Output

```shell
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	github.com/hashicorp/terraform/internal/logging/panic.go:55 +0x170
panic({0x104dfd0e0, 0x10641c9f0})
	runtime/panic.go:884 +0x204
github.com/hashicorp/terraform/internal/backend/remote-state/azure.(*RemoteClient).Put(0x14000861590, {0x140003b02c0, 0x14b, 0x160})
	github.com/hashicorp/terraform/internal/backend/remote-state/azure/client.go:88 +0x404
github.com/hashicorp/terraform/internal/states/remote.(*State).PersistState(0x14000d5fd40, 0x10502b5a0?)
	github.com/hashicorp/terraform/internal/states/remote/state.go:202 +0x4fc
github.com/hashicorp/terraform/internal/states/statemgr.WriteAndPersist({0x12e472bd0, 0x14000d5fd40}, 0x0?, 0x1400095de80?)
	github.com/hashicorp/terraform/internal/states/statemgr/helper.go:53 +0x58
github.com/hashicorp/terraform/internal/backend/local.(*Local).opApply(0x0?, {0x1051a8d38, 0x14000d1f700}, {0x1051a8d38, 0x14000d1f740}, 0x14000d2c480, 0x14000d1f6c0)
	github.com/hashicorp/terraform/internal/backend/local/backend_apply.go:201 +0xd14
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	github.com/hashicorp/terraform/internal/backend/local/backend.go:323 +0xd8
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	github.com/hashicorp/terraform/internal/backend/local/backend.go:316 +0x440
```

### Expected Behaviour

No crash/lock released

### Actual Behaviour

Crashed/unknown lock condition

### Steps to Reproduce

Execute a `terraform destroy`

**Comment by ScottS-byte** [comment]
Also, the Resource Group was imported into terraform management. That showed as successful.

**Comment by wuxu92** [comment]
Hi @ScottS-byte thanks for your feedback. but this looks like a terraform issue, which not relate to azurerm provider. may you file a issue in https://github.com/hashicorp/terraform/issues?

**Comment by manicminer** [comment]
Transferring this to `hashicorp/terraform` since this is a backend issue.
