### ISSUE TITLE
Terraform crashed 

### ISSUE THREAD

**Issue by kural82** [hashicorp/terraform-provider-azurerm#20869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.9

### AzureRM Provider Version

v3.46.0

### Affected Resource(s)/Data Source(s)

azurerm storage account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_container" "example" {
  name                  = "content"
  storage_account_name  = "storageaccountnametest19"
  container_access_type = "private"
}

terraform {
  backend "azurerm" {
    resource_group_name  = "example<>resources"
    storage_account_name = "storageaccountnametest19"
    container_name       = "content"
    key                  = "terraform.tfstate"
  }
}
```

### Debug Output/Panic Output

```shell
Error releasing the state lock
│ 
│ Error message: failed to retrieve lock info: blobs.Client#GetProperties: Failure sending request: StatusCode=0 -- Original Error: Head
│ "https://storageaccountnametest19.blob.core.windows.net/content/terraform.tfstate": dial tcp: lookup storageaccountnametest19.blob.core.windows.net: no such host
│ 
│ Terraform acquires a lock when accessing your state to prevent others
│ running Terraform to potentially modify the state at the same time. An
│ error occurred while releasing this lock. This could mean that the lock
│ did or did not release properly. If the lock didn't release properly,
│ Terraform may not be able to run future commands since it'll appear as if
│ the lock is held.
│ 
│ In this scenario, please call the "force-unlock" command to unlock the
│ state manually. This is a very dangerous operation since if it is done
│ erroneously it could result in two people modifying state at the same time.
│ Only call this command if you're certain that the unlock above failed and
│ that no one else is holding a lock.
╵

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/distiller/project/project/internal/logging/panic.go:55 +0x153
panic({0x2e445e0, 0x4a4c010})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/backend/remote-state/azure.(*RemoteClient).Put(0xc0002242d0, {0xc00064f980, 0x1859, 0x1980})
        /Users/distiller/project/project/internal/backend/remote-state/azure/client.go:88 +0x583
github.com/hashicorp/terraform/internal/states/remote.(*State).PersistState(0xc000a09260, 0x3072d00?)
        /Users/distiller/project/project/internal/states/remote/state.go:202 +0x5c5
github.com/hashicorp/terraform/internal/states/statemgr.WriteAndPersist({0x2dd6d4c0, 0xc000a09260}, 0x2?, 0xc00034de90?)
        /Users/distiller/project/project/internal/states/statemgr/helper.go:53 +0x53
github.com/hashicorp/terraform/internal/backend/local.(*Local).opApply(0x0?, {0x3777278, 0xc000725940}, {0x3777278, 0xc000725980}, 0xc000217e60, 0xc000725900)
        /Users/distiller/project/project/internal/backend/local/backend_apply.go:201 +0x1075
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
        /Users/distiller/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /Users/distiller/project/project/internal/backend/local/backend.go:316 +0x44a
```

### Expected Behaviour

Just deleting the resources after running terraform destroy

### Actual Behaviour

terraform crashed

**Comment by sebader** [comment]
The storage account that you want to use for your backend needs to exist before you run terraform. TF itself cannot create that storage account

`storageaccountnametest19.blob.core.windows.net: no such host`

**Comment by lonegunmanb** [comment]
Hi @kural82, thanks for reporting this crash, according to the dump stack:

>github.com/hashicorp/terraform/internal/backend/remote-state/azure.(*RemoteClient).Put(0xc0002242d0, {0xc00064f980, 0x1859, 0x1980})
        /Users/distiller/project/project/internal/backend/remote-state/azure/client.go:88 +0x583

The code that crashed Terraform is in [Terraform core](https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/azure/client.go#L88)

I'd like to submit a pr to fix this issue, would you please copy this issue to [Terraform repo](https://github.com/hashicorp/terraform) and close this one so I can reference your pr at Terraform repo? Thanks!
