### ISSUE TITLE
terraform-provider-azurerm_v3.50.0_x5.exe plugin crashed

### ISSUE THREAD

**Issue by tassab** [hashicorp/terraform-provider-azurerm#21218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_windows_web_app" "example" {
  name                = "${var.prefix}-${var.environment}-${var.suffix}"
  location            = var.location
  resource_group_name = var.rg_name
  service_plan_id     = var.plan_id

  identity {
    type = "SystemAssigned"
  }

  auth_settings_v2 {
    auth_enabled           = var.auth_enabled
    default_provider       = "aad"
    unauthenticated_action = "RedirectToLoginPage"
    require_authentication = true
    require_https          = true

    active_directory_v2 {
      client_id                  = var.aad_client_id
      allowed_audiences          = var.aad_allowed_audiences
      tenant_auth_endpoint       = "https://sts.windows.net/<tenant_id>/"
      client_secret_setting_name = "MICROSOFT_PROVIDER_AUTHENTICATION_SECRET"
    }

    login {}
  }

  site_config {
    always_on              = true
    default_documents      = ["index.html"]
    ftps_state             = "FtpsOnly"
    vnet_route_all_enabled = true
    use_32_bit_worker      = false
    cors {
      allowed_origins     = var.cors_allowed_origins
      support_credentials = true
    }
  }

  app_settings = {
    "MICROSOFT_PROVIDER_AUTHENTICATION_SECRET" = "@Microsoft.KeyVault(VaultName=${var.vault_name};SecretName=${var.client_secret_name})"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Plugin did not respond
│
│   with module.web-app.azurerm_windows_web_app.example,
│   on [...]\main.tf line 1, in resource "azurerm_windows_web_app" "example":
│    1: resource "azurerm_windows_web_app" "example" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.50.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x52195e3]

goroutine 153 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers.expandAadAuthV2Settings({0xc0006660e0, 0x1, 0x0?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers/auth_v2_schema.go:988 +0x603
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers.ExpandAuthV2Settings({0xc000ae8340, 0x1, 0x7e3db80?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers/auth_v2_schema.go:2059 +0x12a
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice.WindowsWebAppResource.Update.func1({0x7e4b168, 0xc00143e6c0}, {0xc001804000, {0x7e4bc90, 0xc00073e8e8}, 0xc0037ce080, 0x0, {0x7e4d078, 0xc3e6bc8}})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/windows_web_app_resource.go:847 +0x1cc5
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func7({0x7e4b168, 0xc00143e6c0}, 0x1a3185c5000?, {0x69fbbc0?, 0xc001804000?})
        github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:116 +0x15c
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.diagnosticsWrapper.func1({0x7e4b168, 0xc00143e6c0}, 0x0?, {0x69fbbc0, 0xc001804000})
        github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:185 +0xbe
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000773c00, {0x7e4b1a0, 0xc002f9aae0}, 0xd?, {0x69fbbc0, 0xc001804000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000773c00, {0x7e4b1a0, 0xc002f9aae0}, 0xc002fb3ba0, 0xc002fce780, {0x69fbbc0, 0xc001804000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00073e840, {0x7e4b1a0?, 0xc002f9a9c0?}, 0xc0026e6500)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0014b4dc0, {0x7e4b1a0?, 0xc002f9a390?}, 0xc000a31420)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x7151340?, 0xc0014b4dc0}, {0x7e4b1a0, 0xc002f9a390}, 0xc000a313b0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027a000, {0x7e5b4a0, 0xc0016671e0}, 0xc002f96c60, 0xc001299890, 0xc380ec0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00027a000, {0x7e5b4a0, 0xc0016671e0}, 0xc002f96c60, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.50.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

``terraform apply``

### References

still the same issue as in #21110 for release 3.49.0

**Comment by aristosvo** [comment]
I'll submit another fix, I missed something

**Comment by epomatti** [comment]
man I wasted SO MUCH time in this component already, been broken forever. Maybe I'll try it a year from now.

Here is a solution for anyone that needs it:

```terraform
resource "azapi_update_resource" "auth_settings_v2" {
  type      = "Microsoft.Web/sites/config@2022-03-01"
  name      = "authsettingsV2"
  parent_id = azurerm_linux_web_app.main.id

  body = jsonencode({
    properties = {
      "globalValidation" : {
        "excludedPaths" : [
          "/api/dogs",
          "/healthz"
        ],
        "requireAuthentication" : var.require_authentication,
        "unauthenticatedClientAction" : var.unauthenticated_client_action,
        "redirectToProvider" : "azureactivedirectory"
      },
      "httpSettings" : {
        "forwardProxy" : {
          "convention" : "NoProxy"
        },
        "requireHttps" : true,
        "routes" : {
          "apiPrefix" : "/.auth"
        }
      },
      "identityProviders" : {
        "azureActiveDirectory" : {
          "enabled" : true,
          "login" : {
            "disableWWWAuthenticate" : false,
            "loginParameters" : [
              "response_type=code id_token",
              "scope=openid offline_access profile https://graph.microsoft.com/User.Read"
            ]
          },
          "registration" : {
            "clientId" : "${azuread_application.app.application_id}",
            "clientSecretSettingName" : "APP_REGISTRATION_SECRET",
            "openIdIssuer" : "https://sts.windows.net/${data.azurerm_subscription.current.tenant_id}/v2.0"
          },
          "validation" : {
            "allowedAudiences" : [
              local.identifier_uri
            ],
            "defaultAuthorizationPolicy" : {
              "allowedPrincipals" : {}
            },
            "jwtClaimChecks" : {}
          }
        }
      },
      "login" : {
        "cookieExpiration" : {
          "convention" : "FixedTime",
          "timeToExpiration" : "08:00:00"
        },
        "nonce" : {
          "nonceExpirationInterval" : "00:05:00",
          "validateNonce" : true
        },
        "preserveUrlFragmentsForLogins" : false,
        "routes" : {},
        "tokenStore" : {
          "azureBlobStorage" : {},
          "enabled" : true,
          "fileSystem" : {},
          "tokenRefreshExtensionHours" : 72.0
        }
      },
      "platform" : {
        "enabled" : true,
        "runtimeVersion" : "~1"
      }
    }
  })
}
```

**Comment by aristosvo** [comment]
Thanks @epomatti!

Sorry you had to deal with this, I hope next release will cover all your issues!
