### ISSUE TITLE
azurerm_monitor_metric_alert Error with 3.52.0 when setting dynamic_criteria

### ISSUE THREAD

**Issue by Michael-Wearne** [hashicorp/terraform-provider-azurerm#21445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.52.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "to_monitor" {
  name                     = "monitorname"
  resource_group_name      = "myrgname"
  location                 = "australiaeast"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_monitor_action_group" "main" {
  name                = "example-actiongroup"
  resource_group_name = "myrgname"
  short_name          = "exampleact"

  webhook_receiver {
    name        = "callmyapi"
    service_uri = "http://example.com/alert"
  }
}

resource "azurerm_monitor_metric_alert" "example" {
  name                = "example-metricalert"
  resource_group_name = "myrgname"
  scopes              = [azurerm_storage_account.to_monitor.id]
  description         = "Action will be triggered when Transactions count is greater than 50."

  dynamic_criteria {
    metric_namespace  = "Microsoft.Storage/storageAccounts"
    metric_name       = "Availability"
    aggregation       = "Minimum"
    operator          = "GreaterThan"
    alert_sensitivity = "High"

    dimension {
      name     = "ApiName"
      operator = "Include"
      values   = ["*"]
    }

    evaluation_total_count   = 4
    evaluation_failure_count = 1
  }

  action {
    action_group_id = azurerm_monitor_action_group.main.id
  }
}
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.52.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x565e091]

goroutine 204 [running]:

github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x75dcbc0?, {0x75dcbc0?, 0xc0028bb500?}, 0xd?, {0x6178440?, 0xc001e6e400?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001484b60, {0x75dcbc0, 0xc0028bb500}, 0xc001a80ea0, 0xc002309200, {0x6178440, 0xc001e6e400})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0005270e0, {0x75dcbc0?, 0xc0028bb3b0?}, 0xc001a286e0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000cd75e0, {0x75dcbc0?, 0xc0028baa80?}, 0xc001a7c930)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x68f7820?, 0xc000cd75e0}, {0x75dcbc0, 0xc0028baa80}, 0xc001a7c8c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001f01e0, {0x75ec040, 0xc001bec9c0}, 0xc00123cd80, 0xc001bf6150, 0xbad2440, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001f01e0, {0x75ec040, 0xc001bec9c0}, 0xc00123cd80, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.52.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Actual Behaviour

Apply Fails

**Comment by Michael-Wearne** [comment]
Sorry, I meant to add this to the report, but the same code will succeed with

criteria {
    metric_namespace = "Microsoft.Storage/storageAccounts"
    metric_name      = "Transactions"
    aggregation      = "Total"
    operator         = "GreaterThan"
    threshold        = 52

    dimension {
      name     = "ApiName"
      operator = "Include"
      values   = ["*"]
    }
  }
  
  Instead of the dynamic_criteria block used in the example.
