### ISSUE TITLE
terraform-provider-azurerm_v3.0.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by prajith-nair** [hashicorp/terraform-provider-azurerm#21480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

 v1.4.5

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_data_disk_attachment

### Terraform Configuration Files

```hcl
# data.azurerm_client_config.current:
data "azurerm_client_config" "current" {
    client_id       = "xxxxxxx"
    id              = "2023-04-19 06:54:09.619649 +0000 UTC"
    object_id       = "xxxxxxx"
    subscription_id = "xxxxxx"
    tenant_id       = "xxxxxxxxx"
}

# azurerm_managed_disk.managed_disk:
resource "azurerm_managed_disk" "managed_disk" {
    create_option                 = "Empty"
    disk_iops_read_only           = 0
    disk_iops_read_write          = 500
    disk_mbps_read_only           = 0
    disk_mbps_read_write          = 60
    disk_size_gb                  = 100
    id                            = "/subscriptions/xxx-xx-xx-xxx-xxx-xxx/resourceGroups/my-staging-rsgroup/providers/Microsoft.Compute/disks/data"
    location                      = "southindia"
    max_shares                    = 0
    name                          = "data"
    on_demand_bursting_enabled    = false
    public_network_access_enabled = true
    resource_group_name           = "my-staging-rsgroup"
    storage_account_type          = "Standard_LRS"
    tags                          = {
        "deployment"  = "my-staging"
        "environment" = "my-stage"
        "managed_by"  = "terraform"
    }
    trusted_launch_enabled        = false
}

# azurerm_resource_group.my_rsgroup:
resource "azurerm_resource_group" "my_rsgroup" {
    id       = "/subscriptions/xxx-xx-xx-xxx-xxx-xxx/resourceGroups/my-staging-rsgroup"
    location = "southindia"
    name     = "my-staging-rsgroup"
    tags     = {
        "deployment"  = "my-staging"
        "environment" = "my-stage"
        "managed_by"  = "terraform"
    }
}
```

### Debug Output/Panic Output

```shell
│ Error: Plugin did not respond
│
│   with azurerm_storage_account.my_blob_storage,
│   on storage.tf line 1, in resource "azurerm_storage_account" "my_blob_storage":
│    1: resource "azurerm_storage_account" "my_blob_storage" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.0.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x107dd9734]

goroutine 410 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/compute.resourceVirtualMachineDataDiskAttachmentCreateUpdate(0x14000548980, {0x1093289a0, 0x140005bc700})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/internal/services/compute/virtual_machine_data_disk_attachment_resource.go:102 +0x104
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140007c76c0, {0x109d08b78, 0x140019d9a80}, 0x14000548980, {0x1093289a0, 0x140005bc700})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:329 +0x170
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140007c76c0, {0x109d08b78, 0x140019d9a80}, 0x14001223520, 0x14000548700, {0x1093289a0, 0x140005bc700})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:467 +0x8d8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140008c3320, {0x109d08b78, 0x140019d9a80}, 0x14002212fa0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xe38
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140000a3000, {0x109d08c20, 0x14000f2a540}, 0x14000dfe3f0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:603 +0x338
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10986d540, 0x140000a3000}, {0x109d08c20, 0x14000f2a540}, 0x1400052bbc0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000bafc0, {0x109d6df08, 0x140003b0480}, 0x14002e86900, 0x14000c9f980, 0x10e2f0f40, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc04
google.golang.org/grpc.(*Server).handleStream(0x140000bafc0, {0x109d6df08, 0x140003b0480}, 0x14002e86900, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x140008cc730, 0x140000bafc0, {0x109d6df08, 0x140003b0480}, 0x14002e86900)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1f0

Error: The terraform-provider-azurerm_v3.0.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

terraform apply should not crash 

### Actual Behaviour

**Error: The terraform-provider-azurerm_v3.0.0_x5 plugin crashed!**

### Steps to Reproduce

Step 1. `terraform plan`
Step 1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_data_disk_attachment

**Comment by tombuildsstuff** [comment]
hi @prajith-nair 

Thanks for opening this issue.

Taking a look through here `v3.0.0` of the Azure Provider was released over a year ago now, since there's been a considerable number of changes since then, please update to the latest version of the Provider, which at the time of writing is `v3.52.0`.

Since this should be fixed by updating to the latest version of the Provider I'm going to close this issue for the moment, but should this still be an issue when using the latest version of the Provider then please let us know and we'll take another look.

Thanks!

**Comment by prajith-nair** [comment]
@tombuildsstuff  - Thanks for pointing out on azurerm version, I will proceed to use v3.52.0 Azure Provider.
