### ISSUE TITLE
azurerm_mssql_elasticpool Failed to Destroy in Terraform

### ISSUE THREAD

**Issue by Denisjc** [hashicorp/terraform-provider-azurerm#22175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.5.0

### AzureRM Provider Version

v3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_3.61.0

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_elasticpool" "pool" {
  name                = var.db_elastic_pool
  resource_group_name = azurerm_resource_group.devx.name
  location            = azurerm_resource_group.devx.location
  server_name         = azurerm_mssql_server.server.name
  max_size_gb         = 50

  sku {
    name     = "StandardPool"
    tier     = "Standard"
    capacity = 100
  }

  per_database_settings {
    min_capacity = 50
    max_capacity = 100
  }

  tags = merge(local.tags, {
  })
}
```

### Debug Output/Panic Output

```shell
azurerm_resource_group.devx: Refreshing state... [id=/subscriptions/f4a675bc-b98b-453c-bf43-e2f3654fb899/resourceGroups/asdevxeuneuais001rg001]
azurerm_mssql_server.server: Refreshing state... [id=/subscriptions/f4a675bc-b98b-453c-bf43-e2f3654fb899/resourceGroups/asdevxeuneuais001rg001/providers/Microsoft.Sql/servers/asdeveuneuais001sqlsrv003]
azurerm_mssql_elasticpool.pool: Refreshing state... [id=/subscriptions/f4a675bc-b98b-453c-bf43-e2f3654fb899/resourceGroups/asdevxeuneuais001rg001/providers/Microsoft.Sql/servers/asdeveuneuais001sqlsrv003/eazurerm_mssql_database.dwh1_serverless: Refreshing state... [id=/subscriptions/f4a675bc-b98b-453c-bf43-e2f3654fb899/resourceGroups/asdevxeuneuais001rg001/providers/Microsoft.Sql/servers/asdeveuneuais001sqlsrv003/databases/asdeveuneuais001sqldb002]
╷
│ Error: Plugin did not respond
│
│ with azurerm_mssql_database.dwh1_serverless,
│ on create_database.tf line 14, in resource "azurerm_mssql_database" "dwh1_serverless":
│ 14: resource "azurerm_mssql_database" "dwh1_serverless" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ with azurerm_mssql_elasticpool.pool,
│ on create_database_server.tf line 28, in resource "azurerm_mssql_elasticpool" "pool":
│ 28: resource "azurerm_mssql_elasticpool" "pool" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.61.0_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "53687091200": value out of range

goroutine 248 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x1e211b80, {0x1e3251b8, 0x1, 0x1}, 0x8)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x1e211b80)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource_data.go:351 +0x3a7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x1ce5d8f0, {{{0x77f8400, 0x1e324960}}, {0x64d8aa0, 0x1e267f80}})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1cc085a0, {0x77f75e0, 0x1dd66cf0}, 0x1e2679e0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1ce2b5e0, {0x77f75e0, 0x1dd66600}, 0x1e26e630)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x6bd82e0, 0x1ce2b5e0}, {0x77f75e0, 0x1dd66600}, 0x1daae400, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x1cf1c6c0, {0x7800084, 0x1d9d4000}, 0x1e30ae60, 0x1dfd8f60, 0xbb9b448, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1340 +0xe22
google.golang.org/grpc.(*Server).handleStream(0x1cf1c6c0, {0x7800084, 0x1d9d4000}, 0x1e30ae60, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1713 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.51.0/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.51.0/server.go:963 +0x25f

Error: The terraform-provider-azurerm_v3.61.0_x5.exe plugin crashed!
```

### Expected Behaviour

The items should have been deleted.

### Actual Behaviour

The state file was updated and the plugin now fails to run
terraform plan -out main.tfplan Or terraform plan -destroy -out main.tfplan

Editing the state file and removing the setting returns the state to allow plan to to work, but destory seems to return the value back to the state file.

### Steps to Reproduce

terraform plan -out main.tfplan
terraform plan -destroy -out main.tfplan
At this point the terraform.tfstate state file contrains the value 53687091200

"max_size_bytes": 53687091200,

changing this to a smaller value allows for the terraform plan -out main.tfplan to work again
but not the terraform plan -destroy -out main.tfplan

Thus I cannot delete the pool using terraform.

**Comment by bflad** [comment]
Hi @Denisjc 👋 Thank you for raising this issue and sorry you are running into trouble here.

Are you running a 32-bit version of Terraform (I believe so from your [original report description](https://github.com/hashicorp/terraform/issues/33369): `on windows_386`) and are you able to try running on 64-bit? A `53687091200` integer value would overflow a 32-bit integer, which would cause the underlying error within the provider.

**Comment by Denisjc** [comment]
This might sound stupid but there is no download for a 64bit version on the Terraform site
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/31697943/c7822174-a0c4-431e-854b-183012fa97aa)

**Comment by wuxu92** [comment]
@Denisjc are you running a 32-bit OS?

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @bflad‘s response as an answer. If that is not the case, please provide additional information including if you are running a 32-bit OS, thanks!
