### ISSUE TITLE
Destroying azure eventhub schema group fails with Internal Server Error(500)

### ISSUE THREAD

**Issue by sumitroy2611** [hashicorp/terraform-provider-azurerm#22267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_eventhub_namespace_schema_group

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace_schema_group" "schemagrp" {
  for_each             = { for ns in var.event_ns : ns.app_name => ns }
  name                 = var.schemagrp_name
  namespace_id         = azurerm_eventhub_namespace.event_hub[each.value["app_name"]].id
  schema_compatibility = var.schema_features.schema_compatibility
  schema_type          = var.schema_features.schema_type

  depends_on = [
    azurerm_eventhub_namespace.event_hub
  ]
}
```

### Debug Output/Panic Output

```shell
These are the azure backend logs shared by Microsoft team on support ticket(2306120050004696) :

TrackingId: 6cfa1ea2-3a5b-4fe9-8286-3496071b1680_M3CH3_M3CH3, SubsystemId: NoSystemTracker, ServiceBus Resource Provider entity operation failed with following exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.InvalidOperationException: 'Transfer-Encoding: chunked' header can not be used when content object is not specified.
   at System.Net.Http.WinHttpHandler.GetChunkedModeForSend(HttpRequestMessage requestMessage)
   at System.Net.Http.WinHttpHandler.OpenRequestHandle(WinHttpRequestState state, SafeWinHttpHandle connectHandle, String httpVersion, WinHttpChunkMode& chunkedModeForSend, SafeWinHttpHandle& requestHandle)
   at System.Net.Http.WinHttpHandler.<StartRequestAsync>d__122.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Cloud.ServiceBus.ResourceProvider.RpTaskCompletionSource.RunOperationAsync.<Start>d__18.MoveNext() in X:\bt\1229392\repo\src\product\Service\ResourceProvider\Microsoft.Cloud.ServiceBus.ResourceProvider\RpTaskCompletionSource.cs:line 496
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Cloud.ServiceBus.ResourceProvider.RpTaskCompletionSource.RunOperationAsync.<ExecuteHttpRequest>d__14.MoveNext() in X:\bt\1229392\repo\src\product\Service\ResourceProvider\Microsoft.Cloud.ServiceBus.ResourceProvider\RpTaskCompletionSource.cs:line 255https://ns-eh2-prod-ln1-505.cloudapp.net/$schemagroups/schgroup?api-version=2021-10
1
DELETE

Detail: 

The MS eventhub Product Group team has informed that the above http request contains a header called 'transfer-encoding' which is set to 'chunked'. For a delete operation, the request fails saying transfer-encoding' does not contain any content since there is no body and chunked encoding is expecting a body.
```

### Expected Behaviour

The schema group gets successfully deleted with eventhub tear down

### Actual Behaviour

The schema group doesn't get deleted with following error

<img width="1349" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/53339968/24062e1e-293c-4121-8149-b621e4fd6f45">

**Comment by xiaxyi** [comment]
Thanks @sumitroy2611 for raising this issue, does this issue always reproduced? I would like to try to reproduce the issue, so can you share the TF config of the schema group part and replace the `  schema_compatibility = var.schema_features.schema_compatibility
` with the actual value?

**Comment by katbyte** [comment]
Thank you for taking the time to report this issue, and apologies that it has sat without a resolution for so long.

This bug was reported against an early major version of the AzureRM provider. The provider has since moved on to v5.x, and the affected functionality has often been significantly reworked across those major releases, so bug reports from legacy major versions prior to v4.0 are generally no longer actionable as written.

As part of a cleanup of historical issues we are closing bug reports that target legacy provider versions. If you are still running into this behaviour on the current major version, please open a new issue with up-to-date reproduction details (feel free to reference this one) so it can be triaged with current context.

Thank you again for the report, and for your patience.
