### ISSUE TITLE
azurerm_logic_app_workflow access_control block plugin crashed

### ISSUE THREAD

**Issue by danilomnds** [hashicorp/terraform-provider-azurerm#22474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.2

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_workflow

### Terraform Configuration Files

```hcl
** note1: The part of the code that generates the plugin crash is commented.
** note2: The same issue is occurring on azurerm 3.63.0 and 3.64.0. I tested both...

module "logic-coe-fqa-001" {
  source = "git::https://github.com/danilomnds/terraform-azurerm-logic-app-workflow?ref=v1.0.0" 
  name = "logic-coe-fqa-001"
  location = "brazilsouth"
  resource_group_name = "my rg"
  # teste ovalle    
  azure_ad_groups = ["ad group 1"]
  # if you are creating more than one, please specify true once.
  rbac_scope_rg = true
  tags = {
    key1 = "value1"
    key2 = "value2"    
  }  
}
output "logic-coe-fqa-001-name" {
  value = module.logic-coe-fqa-001.name
}
output "logic-coe-fqa-001-id" {
  value = module.logic-coe-fqa-001.id
}
```

### Debug Output/Panic Output

```shell
danilomendes@Danilos-MacBook-Pro teste-modulos % terraform apply                 
module.logic-coe-fqa-001.data.azurerm_resource_group.rg: Reading...
module.logic-coe-fqa-001.data.azurerm_resource_group.rg: Read complete after 0s [id=my info]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create

Terraform will perform the following actions:

  # module.logic-coe-fqa-001.azurerm_logic_app_workflow.logic_app_workflow will be created
  + resource "azurerm_logic_app_workflow" "logic_app_workflow" {
      + access_endpoint                 = (known after apply)
      + connector_endpoint_ip_addresses = (known after apply)
      + connector_outbound_ip_addresses = (known after apply)
      + enabled                         = true
      + id                              = (known after apply)
      + location                        = "brazilsouth"
      + name                            = "logic-coe-fqa-001"
      + resource_group_name             = "my rg"
      + tags                            = (known after apply)
      + workflow_endpoint_ip_addresses  = (known after apply)
      + workflow_outbound_ip_addresses  = (known after apply)
      + workflow_schema                 = "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#"
      + workflow_version                = "1.0.0.0"

      + access_control {
        }
    }

  # module.logic-coe-fqa-001.azurerm_role_assignment.rg_scope_contributor["ad group"] will be created
  + resource "azurerm_role_assignment" "rg_scope_contributor" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = "ad group"
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "Logic App Contributor"
      + scope                            = "my scope"
      + skip_service_principal_aad_check = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + logic-coe-fqa-001-id   = (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.logic-coe-fqa-001.azurerm_logic_app_workflow.logic_app_workflow: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with module.logic-coe-fqa-001.azurerm_logic_app_workflow.logic_app_workflow,
│   on .terraform/modules/logic-coe-fqa-001/main.tf line 1, in resource "azurerm_logic_app_workflow" "logic_app_workflow":
│    1: resource "azurerm_logic_app_workflow" "logic_app_workflow" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.63.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 140 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/logic.expandLogicAppWorkflowAccessControl({0x14002ae6fa0?, 0x1076ec457?, 0x14002cf0e15?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/logic/logic_app_workflow_resource.go:800 +0x2a8
github.com/hashicorp/terraform-provider-azurerm/internal/services/logic.resourceLogicAppWorkflowCreate(0x140023c9300, {0x1084d4280?, 0x140014fe400})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/logic/logic_app_workflow_resource.go:347 +0xb24
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1090f8b00?, {0x1090f8b00?, 0x14002c3b620?}, 0xd?, {0x1084d4280?, 0x140014fe400?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:695 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140011c5880, {0x1090f8b00, 0x14002c3b620}, 0x14002cff860, 0x140023c9180, {0x1084d4280, 0x140014fe400})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0x888
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140012388b8, {0x1090f8b00?, 0x14002c3b500?}, 0x14002a892c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xb78
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400034c820, {0x1090f8b00?, 0x14002c3a840?}, 0x140023ce540)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x108cd2020?, 0x1400034c820}, {0x1090f8b00, 0x14002c3a840}, 0x140023ce4d0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001c81e0, {0x109108f80, 0x140004261a0}, 0x14000166900, 0x14001623920, 0x10d712520, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xbac
google.golang.org/grpc.(*Server).handleStream(0x140001c81e0, {0x109108f80, 0x140004261a0}, 0x14000166900, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28c

Error: The terraform-provider-azurerm_v3.63.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

This variable on this use case was empty, so I didn't understand the cause of the error. 
I created this module in a way to support any future customization, this is way all possible variables are declared.

### Actual Behaviour

The plugin is crashing

### Steps to Reproduce

terraform apply

** the terraform plan does not reproduce the error.

**Comment by ziyeqf** [comment]
Hi @danilomnds, thanks for reporting.

The crash happens when `access_control` was declared as an empty block, I have submitted a PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/22486) for it and I suggest remove the empty block if it's not used to avoid the crash before the PR get merged.

For any further questions please leave comments.
Thanks.
