### ISSUE TITLE
panic: runtime error: during creation of azurerm_app_service_custom_hostname_binding

### ISSUE THREAD

**Issue by J3d3r** [hashicorp/terraform-provider-azurerm#22715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.9

### AzureRM Provider Version

3.66.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service_custom_hostname_binding

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "testrg"
  location = var.location

  lifecycle { prevent_destroy = true }
}

data "azurerm_key_vault_secret" "app_service_certificate_secret" {
  name         = "test-cert"
  key_vault_id = "test key vault - create one"
}

resource "azurerm_service_plan" "app_service_plan" {
  name                = "testappserviceplan"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  os_type             = var.service_plan.os_type
  sku_name            = var.service_plan.sku_name
}

resource "azurerm_linux_web_app" "app_service" {
  name                = "testappservice"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  service_plan_id     = azurerm_service_plan.app_service_plan.id
  
  identity { type = "SystemAssigned" }
}

resource "azurerm_app_service_certificate" "app_service_certificate" {
  name                = data.azurerm_key_vault_secret.app_service_certificate_secret.name
  resource_group_name = azurerm_resource_group.rg.name
  location            = var.location
  pfx_blob            = data.azurerm_key_vault_secret.app_service_certificate_secret.value
}

resource "azurerm_app_service_custom_hostname_binding" "app_service_domain" {
  hostname            = var.custom_domain
  app_service_name    = azurerm_linux_web_app.app_service.name
  resource_group_name = azurerm_resource_group.rg.name
  
  # Ignore ssl_state and thumbprint as they are managed using
  # azurerm_app_service_certificate_binding.app_service_certificate_binding
  lifecycle {
    ignore_changes = [ssl_state, thumbprint]
  }
  depends_on = [
    azurerm_app_service_certificate.app_service_certificate
  ]
}

resource "azurerm_app_service_certificate_binding" "app_service_certificate_binding" {
  hostname_binding_id = azurerm_app_service_custom_hostname_binding.app_service_domain.id
  certificate_id      = azurerm_app_service_certificate.app_service_certificate.id
  ssl_state           = "SniEnabled"
  
  depends_on = [
    azurerm_app_service_custom_hostname_binding.app_service_domain
  ]
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Plugin did not respond
│
│   with module.service.azurerm_app_service_custom_hostname_binding.app_service_domain,
│   on lib\modules\prov-az-linux-webapp\main.tf line 204, in resource "azurerm_app_service_custom_hostname_binding" "app_service_domain":
│  204: resource "azurerm_app_service_custom_hostname_binding" "app_service_domain" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.66.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x62556d6]

goroutine 32 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/web.resourceAppServiceCustomHostnameBindingCreate(0xc002c7a600, {0x686d780?, 0xc002b34000})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/web/app_service_custom_hostname_binding_resource.go:109 +0xd36
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x7cab4a0?, {0x7cab4a0?, 0xc000e19470?}, 0xd?, {0x686d780?, 0xc002b34000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0016a7ce0, {0x7cab4a0, 0xc000e19470}, 0xc0029496c0, 0xc002c7a480, {0x686d780, 0xc002b34000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000116ae0, {0x7cab4a0?, 0xc000e19350?}, 0xc002b23c20)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000527360, {0x7cab4a0?, 0xc000e18960?}, 0xc002b255e0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x709df20?, 0xc000527360}, {0x7cab4a0, 0xc000e18960}, 0xc002b25570, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c81e0, {0x7cbbd00, 0xc000e58000}, 0xc002951200, 0xc001761e60, 0xc342a60, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0001c81e0, {0x7cbbd00, 0xc000e58000}, 0xc002951200, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.66.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Error occurred while executing scripts!
```

### Expected Behaviour

App service being deployed with custom domain using certificate imported from key vault.

Please note that the required DNS records (CNAME and TXT) where configured manually and not managed via Terraform.
Please also note that the actual setup of our resources is a bit more complicated and was simplified for creation of the issue.

### Actual Behaviour

Provider crashes with error message above.

### Steps to Reproduce

terraform apply

**Comment by wuxu92** [comment]
@J3d3r thanks for filing this issue. could you please help me to understand this clear. have you already added the custom domain to the app before `terraform apply`? and is this panic issue occasional or persistent?

**Comment by J3d3r** [comment]
Hello,the custom domain was not added before and should be added by Terraform.Only the DNS records where configured manually.This panic issue is persistent any time Terraform tries to add the custom hostname binding.Actually importing the certificate from key vault was already successfull via Terraform but the error seems to happen when it tries to add the custom domain/hostname.BRJulian-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 28.07.23, 08:36 schrieb Xu Wu ***@***.***>:

   
  @J3d3r thanks for filing this issue. could you please help me to understand this clear. have you already added the custom domain to the app before terraform apply? and is this panic issue occasional or persistent?

**Comment by wuxu92** [comment]
could you please share the debug log of `terraform apply`? [here](https://developer.hashicorp.com/terraform/internals/debugging) is the document to enable debug output. use `TF_LOG=DEBUG terraform apply`

**Comment by J3d3r** [comment]
Hi all,

issue seems to be resolved with newer provider.
There was also a mistake in configuration on our side.

BR
