### ISSUE TITLE
Stack trace from the terraform-provider-cloudad_v0.1.0 plugin

### ISSUE THREAD

**Issue by Baburaju01** [hashicorp/terraform-provider-azurerm#22739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

terraform-provider-cloudad/cloudad.arsSearchHostName(0xc00012a550, 0xe, 0xc00012a530, 0xa, 0xc00012a510, 0xf, 0x0, 0x0)
	terraform-provider-cloudad/cloudad/soap.go:108 +0x563
terraform-provider-cloudad/cloudad.dataSourceCloudADRead(0xd8ad20, 0xc0000bb020, 0xc0000c4900, 0x0, 0x0, 0x0, 0x0, 0x0)
	terraform-provider-cloudad/cloudad/data_source_cloudad.go:68 +0x535
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003240c0, 0xd8aca0, 0xc000223080, 0xc0000c4900, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:297 +0x1ea
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0003240c0, 0xd8aca0, 0xc000223080, 0xc00000ce00, 0x0, 0x0, 0x0, 0xc00000ce00, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:498 +0xfd
	google.golang.org/grpc@v1.35.0/server.go:1540 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000b61f0, 0xc000322540, 0xd92f80, 0xc000001800, 0xc000406200)
	google.golang.org/grpc@v1.35.0/server.go:878 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.35.0/server.go:876 +0x1fd

Error: The terraform-provider-cloudad_v0.1.0 plugin crashed!

### Terraform Version

1.1

### AzureRM Provider Version

3.0

### Affected Resource(s)/Data Source(s)

data "cloudad" "verifyhost"

### Terraform Configuration Files

```hcl
data "cloudad" "verifyhost" {
  host_name   = var.host_name
  action      = var.action
  ad_user     = data.azurerm_key_vault_secret.aduser.value
  ad_password = data.azurerm_key_vault_secret.adpassword.value
}
```

### Debug Output/Panic Output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xb20e63]

goroutine 65 [running]:
terraform-provider-cloudad/cloudad.arsSearchHostName(0xc00012a550, 0xe, 0xc00012a530, 0xa, 0xc00012a510, 0xf, 0x0, 0x0)
	terraform-provider-cloudad/cloudad/soap.go:108 +0x563
terraform-provider-cloudad/cloudad.dataSourceCloudADRead(0xd8ad20, 0xc0000bb020, 0xc0000c4900, 0x0, 0x0, 0x0, 0x0, 0x0)
	terraform-provider-cloudad/cloudad/data_source_cloudad.go:68 +0x535
```

### Actual Behaviour

 Error: Plugin did not respond
│ 
│   with module.virtual_machine.module.az-verify-hostname.data.cloudad.verifyhost,
│   on .terraform/modules/virtual_machine.az-verify-hostname/modules/az-verify-hostname/main.tf line 16, in data "cloudad" "verifyhost":
│   16: data "cloudad" "verifyhost" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.

**Comment by mybayern1974** [comment]
@Baburaju01 thank you for opening this issue. Could you please provide your raw TF config file which can help repro this issue? From the error log there was only TF module related info which cannot help identify the target problematic AzureRM provider resource.

**Comment by tombuildsstuff** [comment]
hi @Baburaju01 

Taking a look through here this crash is coming from the `CloudAD` Provider, since this repository is for `AzureRM` Provider unfortunately there's not much we can do for this issue - and as such I'm going to close this issue for the moment, but I'd suggest opening an issue on that repository where someone should be able to take a look.

Thanks!
