### ISSUE TITLE
`azurerm_container_registry_task_schedule_run_now` always in `Failed` state

### ISSUE THREAD

**Issue by clemlesne** [hashicorp/terraform-provider-azurerm#23334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.73.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry_task_schedule_run_now

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry_task" "this" {
  name                  = "xxx"
  container_registry_id = azurerm_container_registry.this.id

  platform {
    architecture = "amd64"
    os           = "Linux"
  }

  docker_step {
    context_access_token = var.ghcrToken
    context_path         = "https://github.com/xxx/xxx-aoai.git#${var.sourcesBranchName}"
    dockerfile_path      = "Dockerfile"

    image_names = [
      "xxx:{{.Run.ID}}",
      "xxx:${var.sourcesBranchName}",
    ]
  }

  source_trigger {
    branch         = var.sourcesBranchName
    events         = ["commit", "pullrequest"]
    name           = "sources"
    repository_url = "https://github.com/xxx/xxx-aoai"
    source_type    = "Github"

    authentication {
      token      = var.ghcrToken
      token_type = "PAT"
    }
  }

  base_image_trigger {
    name = "base-image"
    type = "All"
  }
}

resource "azurerm_container_registry_task_schedule_run_now" "this" {
  container_registry_task_id = azurerm_container_registry_task.this.id

  depends_on = [
    azurerm_container_registry_task.this,
  ]
}
```

### Debug Output/Panic Output

```shell
Error: waiting for scheduled task to finish: unexpected state 'Failed', wanted target 'Succeeded'. last error: %!s(<nil>)

with azurerm_container_registry_task_schedule_run_now.this,
on main.tf line 194, in resource "azurerm_container_registry_task_schedule_run_now" "this":
194: resource "azurerm_container_registry_task_schedule_run_now" "this" {

waiting for scheduled task to finish: unexpected state 'Failed', wanted target 'Succeeded'. last error: %!s(<nil>)
```

### Expected Behaviour

Resource returned a `Succeeded` state.

### Actual Behaviour

Resource returned a `Failed` state.

In Azure, resource is first in a `Running` state, then `Succeeded`.

### Steps to Reproduce

1. `terraform apply`

**Comment by magodo** [comment]
@clemlesne This normally indicates there is something run in the registry task definition, that causes it failed to run. The resource state you were looking into was suspicously the container registry, not the scheduled task run? Alternatively, you can enable the debug log and find out the exact error message from the API sequences in the log, which might give you additional clues.

Meanwhile, I've tried to run the acctest in this project: https://github.com/hashicorp/terraform-provider-azurerm/blob/1f0865c0535c10b87ee6a0676e55e1fef93ff969/internal/services/containers/container_registry_task_schedule_run_now_resource_test.go#L21, which contains the 3 possible task types, and all of them passed.

**Comment by CShen-101-solution** [comment]
I am experiencing the same issue when using azurerm_container_registry_task_schedule_run_now to trigger a build task, even the task was triggered and finished successfully, the terraform apply returned error as below:
Environment:
**_Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/azurerm v3.72.0_**


```
goroutine 228 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/containers.ContainerRegistryTaskScheduleResource.Create.func1({0x7a40c48, 0xc004ac6f60}, {0xc002639680, {0x7a414d0, 0xc000011350}, 0xc001bc1180, 0x0, {0x7a42650, 0xc423088}})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/containers/container_registry_task_schedule_run_now_resource.go:107 +0x83e
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func2({0x7a40c48, 0xc004ac6f60}, 0x7a40c80?, {0x64986e0?, 0xc002639680?})
	github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:55 +0x163
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.diagnosticsWrapper.func1({0x7a40c48, 0xc004ac6f60}, 0x0?, {0x64986e0, 0xc002639680})
	github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:190 +0xb8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0008f2fc0, {0x7a40c80, 0xc004ac64e0}, 0xd?, {0x64986e0, 0xc002639680})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0008f2fc0, {0x7a40c80, 0xc004ac64e0}, 0xc0047632b0, 0xc001bc1000, {0x64986e0, 0xc002639680})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0013fd428, {0x7a40c80?, 0xc004ac63c0?}, 0xc0015e0e60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001a44320, {0x7a40c80?, 0xc004aabb90?}, 0xc000ecdd50)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x6e87360?, 0xc001a44320}, {0x7a40c80, 0xc004aabb90}, 0xc000ecdce0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ea1e0, {0x7a51360, 0xc001562680}, 0xc004abde60, 0xc001ac4060, 0xc3e2020, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0001ea1e0, {0x7a51360, 0xc001562680}, 0xc004abde60, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.72.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by CShen-101-solution** [comment]
Is there any update on this issue?

**Comment by magodo** [comment]
@CShen-101-solution The issue you encountered seems not the same as @clemlesne's, would you mind create a new issue, with a minimal self contained config & debug log provided?

**Comment by waterfoul** [comment]
I found the edgecase where this happens. Try setting up the task with a failing task.yaml, then change to a task.yaml that succeeds with the same task name
