### ISSUE TITLE
Destruction of Azure IoT Hub (azurerm_iothub) results to error: Plugin did not respond 

### ISSUE THREAD

**Issue by matthiasdev99** [hashicorp/terraform-provider-azurerm#23680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.2

### AzureRM Provider Version

3.77.0

### Affected Resource(s)/Data Source(s)

azurerm_iothub

### Terraform Configuration Files

```hcl
resource "azurerm_iothub" "azure_iot_hub" {
  name                = "iottestmodulexx"
  resource_group_name = "anyrg"
  location            = "westeurope"

  sku {
    name     = "S1"
    capacity = "1"
  }

  identity {
    type = "SystemAssigned"
  }

}
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.77.0_x5 plugin:

panic: time: unknown unit ":" in duration "00:00:15s"

goroutine 105 [running]:
github.com/Azure/go-autorest/autorest/azure.Future.GetPollingDelay({{0x9983098?, 0xc00225ae70?}})
github.com/Azure/go-autorest/autorest@v0.11.29/azure/async.go:185 +0xad
github.com/Azure/go-autorest/autorest/azure.(*Future).WaitForCompletionRef(0xc002c47f80, {0x9968ed8?, 0xc00225ad90?}, {{0x9949e40, 0xc0000504e0}, {0x994c4a0, 0xc001eeb4a0}, 0xc001eeb4d0, 0x0, 0x6fc23ac00, ...})
github.com/Azure/go-autorest/autorest@v0.11.29/azure/async.go:218 +0x1a5
github.com/hashicorp/terraform-provider-azurerm/internal/services/iothub.resourceIotHubDelete(0xc0012b0800, {0x8215d80?, 0xc001ae4900})
github.com/hashicorp/terraform-provider-azurerm/internal/services/iothub/iothub_resource.go:951 +0x331
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0x9968e30?, {0x9968e30?, 0xc000daf650?}, 0xd?, {0x8215d80?, 0xc001ae4900?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:817 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00113b880, {0x9968e30, 0xc000daf650}, 0xc0020a7930, 0xc0012b0780, {0x8215d80, 0xc001ae4900})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:878 +0x605
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000659a58, {0x9968e30?, 0xc000daf560?}, 0xc0012267d0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001518820, {0x9968e30?, 0xc000daeb70?}, 0xc00225a5b0)
github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56a
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x8cecde0?, 0xc001518820}, {0x9968e30, 0xc000daeb70}, 0xc00225a540, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a81e0, {0x997a560, 0xc001a381a0}, 0xc000db05a0, 0xc00192f4d0, 0xf5219f8, 0x0)
google.golang.org/grpc@v1.58.0/server.go:1376 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002a81e0, {0x997a560, 0xc001a381a0}, 0xc000db05a0, 0x0)
google.golang.org/grpc@v1.58.0/server.go:1753 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
google.golang.org/grpc@v1.58.0/server.go:998 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 40
google.golang.org/grpc@v1.58.0/server.go:996 +0x165

Error: The terraform-provider-azurerm_v3.77.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Apply of the destroy should run without the error

### Actual Behaviour

Apply errored with the error above but the resource is deleted in Azure Resource Group

### Steps to Reproduce

- Plan and Apply in TFC
- Run manually destroy plan in Terraform Cloud or delete resource from tf-file (both triggers result into the error while applying the deletetion)

### Important Factoids

Tried also using Terraform version 1.5.0 and/or Provider version 3.20.0/3.60.0

**Comment by wuxu92** [comment]
Hi @matthiasdev99 Thanks for reporting this issue. This appears to be related to the API in some European regions. We are reaching out to the IoT team regarding this matter.

**Comment by jaritimonen** [comment]
This is affecting use also in North Europe with Iot Hub removal.

**Comment by ziyeqf** [comment]
Hi @matthiasdev99 and @jaritimonen. Thanks for reporting. This should have been fixed, could you please give it a try? And if this issue appears again, please leave comments with the region. Thanks!

**Comment by jaritimonen** [comment]
@ziyeqf Seems to be working. Thanks alot!

**Comment by matthiasdev99** [comment]
@ziyeqf Looks good in west europe - Thank you!

**Comment by ziyeqf** [comment]
> Same crash today in uk south
> 
> ```
> ╷
> │ Error: Plugin did not respond
> │ 
> │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
> ╵
> ╷
> │ Error: Plugin did not respond
> │ 
> │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
> ╵
> 
> Stack trace from the terraform-provider-azurerm_v3.79.0_x5 plugin:
> 
> panic: time: unknown unit ":" in duration "00:00:15s"
> 
> goroutine 560 [running]:
> github.com/Azure/go-autorest/autorest/azure.Future.GetPollingDelay({{0x99c1c98?, 0xc000cb8700?}})
>         github.com/Azure/go-autorest/autorest@v0.11.29/azure/async.go:185 +0xad
> github.com/Azure/go-autorest/autorest/azure.(*Future).WaitForCompletionRef(0xc001f89000, {0x99a7968?, 0xc000be9ab0?}, {{0x9988720, 0xc001a9c470}, {0x998ad80, 0xc001d39f80}, 0xc001d39fb0, 0x0, 0x6fc23ac00, ...})
>         github.com/Azure/go-autorest/autorest@v0.11.29/azure/async.go:218 +0x1a5
> github.com/hashicorp/terraform-provider-azurerm/internal/services/iothub.resourceIotHubDelete(0xc001ab7500, {0x82414c0?, 0xc001aec000})
>         github.com/hashicorp/terraform-provider-azurerm/internal/services/iothub/iothub_resource.go:951 +0x331
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0x99a78c0?, {0x99a78c0?, 0xc001341a40?}, 0xd?, {0x82414c0?, 0xc001aec000?})
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:817 +0x163
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000f6ca80, {0x99a78c0, 0xc001341a40}, 0xc002b41040, 0xc001ab7480, {0x82414c0, 0xc001aec000})
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:878 +0x605
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0006168d0, {0x99a78c0?, 0xc001341950?}, 0xc0026153b0)
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
> github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00159c820, {0x99a78c0?, 0xc0017f96b0?}, 0xc000be9340)
>         github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56a
> github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x8d1c9c0?, 0xc00159c820}, {0x99a78c0, 0xc0017f96b0}, 0xc000be92d0, 0x0)
>         github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
> google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a81e0, {0x99b9080, 0xc0019821a0}, 0xc001f4e000, 0xc00191c5a0, 0xf5849f8, 0x0)
>         google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
> google.golang.org/grpc.(*Server).handleStream(0xc0002a81e0, {0x99b9080, 0xc0019821a0}, 0xc001f4e000, 0x0)
>         google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
> google.golang.org/grpc.(*Server).serveStreams.func1.1()
>         google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
> created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 65
>         google.golang.org/grpc@v1.58.3/server.go:997 +0x145
> 
> Error: The terraform-provider-azurerm_v3.79.0_x5 plugin crashed!
> 
> This is always indicative of a bug within the plugin. It would be immensely
> helpful if you could report the crash with the plugin's maintainers so that it
> can be fixed. The output above should help diagnose the issue.
> ```

Thanks for feedback, we have reached out to IoT team to fix on that region, please give it a try about 1 day later. 
And we are trying to test automatically on all regions and fix them.

**Comment by ziyeqf** [comment]
Hi all, the fix has been rolled out on all regions. 

For any further questions please leave comments. Thanks!

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved per the comment above. As such, I am going to mark this issue as closed. If that is not the case, please provide
