### ISSUE TITLE
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call.

### ISSUE THREAD

**Issue by faheemvp2021** [hashicorp/terraform-provider-azurerm#23712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.2

### AzureRM Provider Version

3.78.0

### Affected Resource(s)/Data Source(s)

None

### Terraform Configuration Files

```hcl
Trying to update Azurerm sql elastic pool.
```

### Debug Output/Panic Output

```shell
Error: Plugin did not respond

  with azurerm_mssql_elasticpool.rg_pri_sol_sql_ep,
  on sql-server-elastic-pools.tf line 1, in resource "azurerm_mssql_elasticpool" "rg_pri_sol_sql_ep":
   1: resource "azurerm_mssql_elasticpool" "rg_pri_sol_sql_ep" {

The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.

Stack trace from the terraform-provider-azurerm_v3.78.0_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "268435456000": value out of range

goroutine 162 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x193e5680, {0x197b6068, 0x1, 0x1}, 0x8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource_data.go:556 +0x28f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x193e5680)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource_data.go:354 +0x463
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x18c09420, {{{0x8e5a600, 0x193f1f08}}, {0x7954760, 0x197b23e0}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:670 +0x1e8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x182ed940, {0x8e58ec0, 0x1978ed98}, 0x193efe40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:623 +0x238
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x183c1c20, {0x8e58ec0, 0x1978eb10}, 0x193f5650)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:789 +0x481
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x82d1b60, 0x183c1c20}, {0x8e58ec0, 0x1978eb10}, 0x188929c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:431 +0x176
google.golang.org/grpc.(*Server).processUnaryRPC(0x180d2780, {0x8e62210, 0x1900e120}, 0x18c3a460, 0x18fb0f90, 0xe66cbd4, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1374 +0xed9
google.golang.org/grpc.(*Server).handleStream(0x180d2780, {0x8e62210, 0x1900e120}, 0x18c3a460, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1751 +0xa02
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.58.3/server.go:986 +0xe1
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 68
        google.golang.org/grpc@v1.58.3/server.go:997 +0x14c

Error: The terraform-provider-azurerm_v3.78.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

should bring complete plan and successfully apply

### Actual Behaviour

It brings an incomplete plan thus failed to apply

**Comment by wuxu92** [comment]
Hi @faheemvp2021 thanks for filing this issue. As for the error message `Error reading level state: strconv.ParseInt: parsing "268435456000": value out of range` shows that you are running a 32-bit version provider. could you please share the result of `terraform --version`?

**Comment by katbyte** [comment]
Thank you for taking the time to report this issue, and apologies that it has sat without a resolution for so long.

This bug was reported against an early major version of the AzureRM provider. The provider has since moved on to v5.x, and the affected functionality has often been significantly reworked across those major releases, so bug reports from legacy major versions prior to v4.0 are generally no longer actionable as written.

As part of a cleanup of historical issues we are closing bug reports that target legacy provider versions. If you are still running into this behaviour on the current major version, please open a new issue with up-to-date reproduction details (feel free to reference this one) so it can be triaged with current context.

Thank you again for the report, and for your patience.
