### ISSUE TITLE
Segmentation Violation in Azurerm v3.83

### ISSUE THREAD

**Issue by Paxilein** [hashicorp/terraform-provider-azurerm#24096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.4

### AzureRM Provider Version

3.83

### Affected Resource(s)/Data Source(s)

azurerm_app_service_custom_hostname_binding, azurerm_relay_hybrid_connection, azurerm_mssql_database

### Terraform Configuration Files

```hcl
That's kind of complicated as it's part of a Landing Zone's Workload deployment... And it affects several modules, so don't think that it's related to the actual terraform code... But if it's actually needed I can see what I can do to get some useful stuff together that doesn't need everything...
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.83.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a52126]

goroutine 73 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/web.resourceAppServiceCustomHostnameBindingCreate(0xc00524a680, {0x81d4060?, 0xc0011f7b00})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/web/app_service_custom_hostname_binding_resource.go:108 +0xd66
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x9964880?, {0x9964880?, 0xc005247560?}, 0xd?, {0x81d4060?, 0xc0011f7b00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000b3fdc0, {0x9964880, 0xc005247560}, 0xc0019901a0, 0xc00524a500, {0x81d4060, 0xc0011f7b00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00002b968, {0x9964880?, 0xc005247470?}, 0xc0005651d0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001d3da40, {0x9964880?, 0xc005246c60?}, 0xc0018f9260)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56a
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x8cd2780?, 0xc001d3da40}, {0x9964880, 0xc005246c60}, 0xc0018f91f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ac1e0, {0x9976000, 0xc00090eb60}, 0xc005248fc0, 0xc000f0b3b0, 0xf4cd9f8, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002ac1e0, {0x9976000, 0xc00090eb60}, 0xc005248fc0, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 25
	google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.83.0_x5 plugin crashed!
```

### Expected Behaviour

Not crash?

### Actual Behaviour

Plugin crashes

### Steps to Reproduce

apply the plan

**Comment by Paxilein** [comment]
Interestingly, just running the plan and apply again it works... So, maybe not an urgent issue but might be missing catching that error and gracefully failing instead of crashing?

**Comment by Paxilein** [comment]
When that error happened the same happened in azurerm_relay_hybrid_connection and azurerm_mssql_database... Only the full trace of the azurerm_app_service_custom_hostname_binding was posted in the error though... So not sure if the others were only caused by this crash or maybe have the same issue?

**Comment by katbyte** [comment]
Thank you for taking the time to report this issue, and apologies that it has sat without a resolution for so long.

This bug was reported against an early major version of the AzureRM provider. The provider has since moved on to v5.x, and the affected functionality has often been significantly reworked across those major releases, so bug reports from legacy major versions prior to v4.0 are generally no longer actionable as written.

As part of a cleanup of historical issues we are closing bug reports that target legacy provider versions. If you are still running into this behaviour on the current major version, please open a new issue with up-to-date reproduction details (feel free to reference this one) so it can be triaged with current context.

Thank you again for the report, and for your patience.
