### ISSUE TITLE
The terraform-provider-azurerm_v3.92.0_x5 plugin crashed

### ISSUE THREAD

**Issue by sk0289** [hashicorp/terraform-provider-azurerm#24957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.92.0

### Affected Resource(s)/Data Source(s)

postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "psql-flex" {
  name                   = "psql-tst
  resource_group_name    = var.rgname
  location               = var.location
  version                = var.version_psql
  delegated_subnet_id    = var.subnet_id
  private_dns_zone_id    = var.private_dns_zone_id
  administrator_login    = var.admin_login
  administrator_password = var.admin_login_pwd == null ? random_password.main.0.result : var.admin_login_pwd

  storage_mb             = var.storage_mb
  sku_name               = var.sku_name
  depends_on             = [var.dependent_module]
  authentication {
    active_directory_auth_enabled = true
    tenant_id                     = data.azurerm_client_config.current.tenant_id
  }  
  identity {
    type         = var.psql_server_identity
    identity_ids = var.identity_ids
  }
  customer_managed_key {
    key_vault_key_id                         = var.tde_kv_key_id
    primary_user_assigned_identity_id        = var.primary_user_assigned_identity_id
  }
  lifecycle {
    ignore_changes = [
      zone,
      administrator_password,
    ]
  } 

}
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.92.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 115 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres.expandFlexibleServerDataEncryption({0xc005b98e70?, 0x89ff6b7?, 0xc000dcb420?})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres/postgresql_flexible_server_resource.go:1097 +0x385
github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres.resourcePostgresqlFlexibleServerCreate(0x0?, {0x7a33fa0?, 0xc00171f680?})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres/postgresql_flexible_server_resource.go:441 +0xb6f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x9233420?, {0x9233420?, 0xc005b830b0?}, 0xd?, {0x7a33fa0?, 0xc00171f680?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001a75420, {0x9233420, 0xc005b830b0}, 0xc0015dd5f0, 0xc005904980, {0x7a33fa0, 0xc00171f680})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00055d080, {0x9233420?, 0xc005b82fc0?}, 0xc001bb3770)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0010fdf40, {0x9233420?, 0xc005993e30?}, 0xc000dcac40)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x85fff80?, 0xc0010fdf40}, {0x9233420, 0xc005993e30}, 0xc000dcabd0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ce1e0, {0x925a200, 0xc001a8e680}, 0xc00189ed80, 0xc0016c77a0, 0xec0be98, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002ce1e0, {0x925a200, 0xc001a8e680}, 0xc00189ed80, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 52
	google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.92.0_x5 plugin crashed!
```

**Comment by sk0289** [comment]
The plugin crashes when the null value is supplied to the parameter primary_user_assigned_identity_id

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. It just happens when the empty block "customer_managed_key {}" is specified. Suggest to not set it when it doesn't need. Thanks.
