### ISSUE TITLE
The terraform-provider-azurerm_v3.71.0_x5 plugin crashed! panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lex885uk** [hashicorp/terraform-provider-azurerm#25075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

panic: runtime error: invalid memory address or nil pointer dereference

### Terraform Configuration Files

```hcl
Currently every terraform operation comes back with this error so it is not linked to any configuration. All speculative runs result in the below error since yesterday afternoon. Before that my runs were all good.

We have a few subscriptions set up through Terraform Cloud workspaces. The smaller ones are tested and still working fine, only the 2 big ones having this issue.
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.71.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x54dd53a]

goroutine 131739 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy.flattenAzureRmVirtualMachineOsProfile(...)
github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy/virtual_machine_resource.go:1284
github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy.resourceVirtualMachineRead(0xc00af92e80, {0x64a9480?, 0xc0016d1680})
github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy/virtual_machine_resource.go:884 +0xe5a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x7a4e060?, {0x7a4e060?, 0xc008521530?}, 0xd?, {0x64a9480?, 0xc0016d1680?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0012a8460, {0x7a4e060, 0xc008521530}, 0xc00d245e10, {0x64a9480, 0xc0016d1680})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0016d32c0, {0x7a4e060?, 0xc008521410?}, 0xc009fbf6c0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000bea5a0, {0x7a4e060?, 0xc008520870?}, 0xc00b771c80)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x6e900a0?, 0xc000bea5a0}, {0x7a4e060, 0xc008520870}, 0xc008c88540, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d01e0, {0x7a5e640, 0xc001933380}, 0xc003fea5a0, 0xc001938270, 0xc3e3d50, 0x0)
google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0001d01e0, {0x7a5e640, 0xc001933380}, 0xc003fea5a0, 0x0)
google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.71.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

normal plan should run adding a few changes to an NSG and fixing some drifts.

### Actual Behaviour

We are trying to do terraform plan through our agent what is hosted in a container instance in our azure. 

### Steps to Reproduce

terraform plan

### Important Factoids

no

**Comment by mybayern1974** [comment]
close this issue per wuxu92's suggestion. Feel free to suggest to reactivate this issue it upgrading the project version still does not help.
