### ISSUE TITLE
Error: The terraform-provider-azurerm_v3.96.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by tbraman1065** [hashicorp/terraform-provider-azurerm#25321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5

### AzureRM Provider Version

v3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
terraform {
    required_providers {
        azurerm = {
            source  = "hashicorp/azurerm"
            version = "3.95.0"
        }
    }

    backend "azurerm" {
      resource_group_name  = "deploymentSupport-rg"
      storage_account_name = "91df53418af3427tfstate"
      container_name       = "tfstate"
      key                  = "terraform_azuresql.tfstate"
    } 
}

provider "azurerm" {
  features {}
}

# Resource Group for SQL Resources to be created
data "azurerm_resource_group" "rsgAzureSql" {
  name     = var.AZ_SQL_RSG
}

data "azurerm_client_config" "current" {
}

###############################################################################
#                                                                             #
# Connect to Key Vault to retrieve secrets                                    #
#                                                                             #
###############################################################################

# Key Vault containing the credentials to use for the SA account
data "azurerm_key_vault" "sqltestkeyvault" {
  name                       = var.AZ_KEYVAULT_NAME
  resource_group_name        = var.AZ_SQL_RSG
}

# Need sql-sa-sample-username and sql-sa-sample-password from the keyvault
data "azurerm_key_vault_secret" "sqlsasampleusername" {
  name                       = var.AZ_SQL_SA_KV_ACCOUNT_NAME
  key_vault_id               = data.azurerm_key_vault.sqltestkeyvault.id
}

data "azurerm_key_vault_secret" "sqlsasamplepassword" {
  name                       = var.AZ_SQL_SA_KV_ACCOUNT_PASSWORD
  key_vault_id               = data.azurerm_key_vault.sqltestkeyvault.id
}

###############################################################################
#                                                                             #
# Set up logging to SIEM                                                      #
#                                                                             #
###############################################################################

# sub_evicore_prod, needed by the logging to SIEM
provider "azurerm" {
  alias                         = "prodsub"
  subscription_id               = var.AZ_PRODUCTION_SUBSCRIPTIONID
  tenant_id                     = var.AZ_TENANTID
  features {}
}
resource "azurerm_mssql_server" "azuresqldb" {
  name                          = var.AZ_SQL_NAME
  resource_group_name           = data.azurerm_resource_group.rsgAzureSql.name
  location                      = data.azurerm_resource_group.rsgAzureSql.location
  version                       = var.AZ_SQL_VERSION
  administrator_login           = data.azurerm_key_vault_secret.sqlsasampleusername.value
  administrator_login_password  = data.azurerm_key_vault_secret.sqlsasamplepassword.value
  minimum_tls_version           = var.AZ_SQL_TLS_VERSION
  connection_policy             = var.AZ_SQL_CONNECTION_POLICY
  public_network_access_enabled = var.AZ_SQL_PUBLIC_NETWORK_ACCESS

  identity {
    type = "SystemAssigned"
  }

  azuread_administrator {
    azuread_authentication_only = var.AZ_SQL_AZURE_AD_AUTHENTICATION_ONLY
    login_username              = var.AZ_SQL_SA_AAD_LOGIN
    object_id                   = var.AZ_SQL_AZUREAD_ADMIN_OBJECT_ID
  }

  tags                          = var.AZ_SQL_TAGS
}

resource "azurerm_mssql_database" "testdatabase" {
  name                      = "RaDAR"
  depends_on                = [azurerm_mssql_server.azuresqldb] 
  server_id                 = azurerm_mssql_server.azuresqldb.id
  collation                 = var.AZ_SQL_COLLATION
  license_type              = var.AZ_SQL_LICENSE
  max_size_gb               = var.AZ_SQL_MAXSIZE
  read_scale                = var.AZ_SQL_READSCALE
  sku_name                  = var.AZ_SQL_SKU
  zone_redundant            = var.AZ_SQL_ZONEREDUNDANT

  long_term_retention_policy {
    weekly_retention        = try(var.AZ_SQL_WEEKLY_RETENTION != null) ? var.AZ_SQL_WEEKLY_RETENTION : null
    monthly_retention       = try(var.AZ_SQL_MONTHLY_RETENTION != null) ? var.AZ_SQL_MONTHLY_RETENTION : null
    yearly_retention        = try(var.AZ_SQL_YEARLY_RETENTION != null) ? var.AZ_SQL_YEARLY_RETENTION : null
    week_of_year            = var.AZ_SQL_WEEKOFYEAR
  }

  tags = var.AZ_SQL_TAGS
}
```

### Debug Output/Panic Output

```shell
azurerm_mssql_database.testdatabase: Still creating... [8m0s elapsed]
╷
│ Error: Plugin did not respond
│
│   with azurerm_mssql_database.testdatabase,
│   on main.tf line 117, in resource "azurerm_mssql_database" "testdatabase":
│  117: resource "azurerm_mssql_database" "testdatabase" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more      
│ details.
╵

Stack trace from the terraform-provider-azurerm_v3.96.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x65132aa]

goroutine 107 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql.resourceMsSqlDatabaseCreate(0xc004a24980, {0x7532900?, 0xc001ea4900?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql/mssql_database_resource.go:585 +0x47ea
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x8d5fac0?, {0x8d5fac0?, 0xc004a06c00?}, 0xd?, {0x7532900?, 0xc001ea4900?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000cdcc40, {0x8d5fac0, 0xc004a06c00}, 0xc0016512b0, 0xc004a24800, {0x7532900, 0xc001ea4900})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001483f0, {0x8d5fac0?, 0xc004a06b10?}, 0xc001cf4370)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001a7e960, {0x8d5fac0?, 0xc004a060f0?}, 0xc000b76070)    
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x813ed60?, 0xc001a7e960}, {0x8d5fac0, 0xc004a060f0}, 0xc000b76000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002f81e0, {0x8d872c0, 0xc001b881a0}, 0xc004a12000, 0xc001b15470, 0xe6b0d38, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002f81e0, {0x8d872c0, 0xc001b881a0}, 0xc004a12000, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 23
        google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.96.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

When selecting the database, use sku: "HS_Gen5_2"

**Comment by tgalentinesr-Insight** [comment]
Same issue
