### ISSUE TITLE
azurerm_storage_share and azurerm_storage_account plugin not responding 

### ISSUE THREAD

**Issue by dshah93** [hashicorp/terraform-provider-azurerm#25378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

Azure storage account and azure file share

### Terraform Configuration Files

```hcl
getting error while its trying to generate plan
```

### Debug Output/Panic Output

```shell
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x8dc5fb0?, {0x8dc5fb0?, 0xc002f8fd70?}, 0xd?, {0x758ffe0?, 0xc0013d4d80?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:783 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc001bf7340, {0x8dc5fb0, 0xc002f8fd70}, 0xc002e4e820, {0x758ffe0, 0xc0013d4d80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00093d698, {0x8dc5fb0?, 0xc002f8fc80?}, 0xc002f8d580)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:649 +0x48a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0015ef900, {0x8dc5fb0?, 0xc002f8f4d0?}, 0xc002d95260)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:789 +0x48b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x81b95c0?, 0xc0015ef900}, {0x8dc5fb0, 0xc002f8f4d0}, 0xc0032d5490, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:431 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c61e0, {0x8dedb00, 0xc00135e680}, 0xc00457c6c0, 0xc0006ff680, 0xe6c1d08, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002c61e0, {0x8dedb00, 0xc00135e680}, 0xc00457c6c0, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 25
	google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.97.1_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by anwarnk** [comment]
FYI: I have the same error:

Stack trace from the terraform-provider-azurerm_v3.97.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x464ae9f]

goroutine 1517 [running]:
github.com/tombuildsstuff/giovanni/storage/2023-11-03/blob/containers.Client.GetProperties({0x3?}, {0x8f746f8, 0xc0000fddc0}, {0xc001655af0?, 0x5?}, {{0x0?, 0x5?}})
	github.com/tombuildsstuff/giovanni@v0.25.3/storage/2023-11-03/blob/containers/get_properties.go:53 +0x29f
github.com/hashicorp/terraform-provider-azurerm/internal/services/storage/shim.DataPlaneStorageContainerWrapper.Exists({0xc0033a61b0?}, {0x8f746f8?, 0xc0000fddc0?}, {0xc001655af0?, 0xc0010a0878?})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/storage/shim/containers_data_plane.go:42 +0x85
github.com/hashicorp/terraform-provider-azurerm/internal/services/storage.resourceStorageContainerCreate(0x0?, {0x7744b20?, 0xc001859200})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/storage/storage_container_resource.go:136 +0x72c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x8f74650?, {0x8f74650?, 0xc002582f90?}, 0xd?, {0x7744b20?, 0xc001859200?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00153ce00, {0x8f74650, 0xc002582f90}, 0xc001a8dba0, 0xc0019b7a80, {0x7744b20, 0xc001859200})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000818e10, {0x8f74650?, 0xc002582e70?}, 0xc00058d400)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000fad180, {0x8f74650?, 0xc002582630?}, 0xc0000fd570)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x836c6a0?, 0xc000fad180}, {0x8f74650, 0xc002582630}, 0xc0000fd500, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00034c1e0, {0x8f9c1a0, 0xc001b841a0}, 0xc00264dd40, 0xc001a5a180, 0xe859c98, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc00034c1e0, {0x8f9c1a0, 0xc001b841a0}, 0xc00264dd40, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:9[86](https://github.com/
Error: The terraform-provider-azurerm_v3.97.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by rcskosir** [comment]
@dshah93 Thank you for taking the time to open this issue. Can you please provide the terraform configuration that on plan leads to this output to help with reproduction?

**Comment by dshah93** [comment]
@rcskosir I am creating multiple storage account in loop structure 

**variable.tf**

  function_app_list = [
    {
      storage_account_name          = "sacscdnauseqaintlxfx00"
      function_app_name             = "fx-csc-dna-use-q-ase-test"
      app_service_plan_name         = "asp-csc-dna-use-int-qa-zone1b-01"
      app_insight_name              = "ai-csc-dna-use-q-ase-test"
      public_network_access_enabled = true
      identity = {
        type = "SystemAssigned"
      }
    },
    {
      storage_account_name          = "sacscdnauseqaintlxfx01"
      function_app_name             = "fx-csc-dna-use-q-pbsb-httprcvr"
      app_service_plan_name         = "asp-csc-dna-use-int-qa-zone1a-01"
      app_insight_name              = "ai-csc-dna-use-q-pbsb"
      public_network_access_enabled = true
      identity = {
        type = "SystemAssigned"
      }
    }
  ]

**storage.tf**

module "storage_function_app_ase" {
  source   = "../../../modules/blob_storage"
  for_each = { for function_app in local.function_app : function_app.storage_account_name => function_app }

  resource_group_name              = module.resource_group.resource_group_name
  loc                              = module.resource_group.location
  sa_blob_name                     = each.value.storage_account_name
  container_name                   = each.value.container_name
  cross_tenant_replication_enabled = each.value.cross_tenant_replication_enabled
  allow_nested_items_to_be_public  = each.value.allow_nested_items_to_be_public
  sa_identity                      = each.value.sa_identity
  container_access                 = each.value.container_access

  enable_advanced_threat_protection = each.value.enable_advanced_threat_protection
  enable_network_rule               = each.value.enable_network_rule
  default_action                    = each.value.default_action
  bypass_resources                  = each.value.bypass_resources
  bypass_ips                        = each.value.bypass_ips
  subnet_ids                        = each.value.subnet_ids
  private_link_access               = each.value.private_link_access

  tags = merge(local.sa_tags, {
    "hidden-title" = "Linux-Function"
  })
}

**resoure file**

resource "azurerm_storage_account" "blob" {
  name = var.sa_blob_name

  resource_group_name = var.resource_group_name
  location            = var.loc

  account_kind             = var.account_kind
  account_tier             = var.account_tier
  account_replication_type = var.repl_type
  #public_network_access_enabled     = var.public_network_access_enabled
  access_tier                       = var.access_tier
  infrastructure_encryption_enabled = var.infrastructure_encryption_enabled
  cross_tenant_replication_enabled  = var.cross_tenant_replication_enabled
  #shared_access_key_enabled         = var.shared_access_key_enabled
  allow_nested_items_to_be_public = var.allow_nested_items_to_be_public
  large_file_share_enabled        = var.large_file_share_enabled

  enable_https_traffic_only = var.https_only
  min_tls_version           = var.min_tls

  tags = var.tags

  dynamic "identity" {
    for_each = var.sa_identity
    content {
      type = identity.value["type"]
    }
  }


  blob_properties {
    versioning_enabled = var.blob_versioning

    dynamic "delete_retention_policy" {
      for_each = var.blob_soft_delete_days != null ? [var.blob_soft_delete_days] : []

      content {
        days = var.blob_soft_delete_days
      }
    }

    dynamic "container_delete_retention_policy" {
      for_each = var.container_soft_delete != null ? [var.container_soft_delete] : []
      content {
        days = var.container_soft_delete
      }

    }
  }

  routing {
    publish_internet_endpoints  = var.publish_internet_endpoints
    publish_microsoft_endpoints = var.publish_microsoft_endpoints
  }

  share_properties {
    dynamic "retention_policy" {
      for_each = var.file_share_soft_delete_retention != null ? [var.file_share_soft_delete_retention] : []
      content {
        days = var.file_share_soft_delete_retention
      }
    }
  }


  timeouts {
    create = var.timeouts.create
    read   = var.timeouts.read
    update = var.timeouts.update
    delete = var.timeouts.delete
  }

  lifecycle {
    ignore_changes = [
      dns_endpoint_type
    ]
  }
}

**Comment by dshah93** [comment]
thank you @manicminer, its working now

**Comment by manicminer** [comment]
@dshah93 Thanks for the feedback, marking this resolved
