### ISSUE TITLE
The terraform-provider-azurerm_v3.96.0_x5 plugin crashed

### ISSUE THREAD

**Issue by HansGe** [hashicorp/terraform-provider-azurerm#25456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "bootdiags" {

  name                      = "st${var.customer_abbreviation}${var.environment}${var.project}diag01"
  resource_group_name       = azurerm_resource_group.services.name
  location                  = var.location
  account_replication_type  = "LRS"
  account_tier              = "Standard"
  account_kind              = "StorageV2"
  enable_https_traffic_only = "true"
  #allow_blob_public_access  = false
  allow_nested_items_to_be_public = false
  depends_on                      = [azurerm_resource_group.services]



  network_rules {
    default_action             = "Deny"
    virtual_network_subnet_ids = var.subnets
    ip_rules                   = var.allowed_ips
  }

  lifecycle {
    ignore_changes = [tags]
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Plugin did not respond
│ 
│   with module.services.azurerm_storage_account.bootdiags,
│   on .terraform/modules/services/module.tf line 15, in resource "azurerm_storage_account" "bootdiags":
│   15: resource "azurerm_storage_account" "bootdiags" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.services.azurerm_storage_account.gendiags,
│   on .terraform/modules/services/module.tf line 69, in resource "azurerm_storage_account" "gendiags":
│   69: resource "azurerm_storage_account" "gendiags" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.services.azurerm_storage_account.scripts,
│   on .terraform/modules/services/module.tf line 117, in resource "azurerm_storage_account" "scripts":
│  117: resource "azurerm_storage_account" "scripts" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
Stack trace from the terraform-provider-azurerm_v3.96.0_x5 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xbe50ef]
goroutine 3546 [running]:
github.com/hashicorp/go-azure-sdk/sdk/client.(*Response).Unmarshal(0xc0025da910, {0x737ec40, 0xc003465a40?})
	github.com/hashicorp/go-azure-sdk/sdk@v0.20240314.1083835/client/client.go:171 +0x4f
github.com/tombuildsstuff/giovanni/storage/2023-11-03/blob/accounts.Client.GetServiceProperties({0xc001381d90?}, {0x904d1c8, 0xc0002bea10}, {0xc0033cc1c8?, 0x13})
	github.com/tombuildsstuff/giovanni@v0.25.1/storage/2023-11-03/blob/accounts/get_service_properties.go:42 +0x235
github.com/hashicorp/terraform-provider-azurerm/internal/services/storage.resourceStorageAccountRead(0xc003797000, {0x7826420?, 0xc0018e9200})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/storage/storage_account_resource.go:2333 +0x2c2f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x904d120?, {0x904d120?, 0xc003396a20?}, 0xd?, {0x7826420?, 0xc0018e9200?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:783 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0015a0000, {0x904d120, 0xc003396a20}, 0xc0032eef70, {0x7826420, 0xc0018e9200})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0001167b0, {0x904d120?, 0xc003396930?}, 0xc0021e4380)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:649 +0x48a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0002eef00, {0x904d120?, 0xc003396180?}, 0xc0030be060)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:789 +0x48b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x8430e20?, 0xc0002eef00}, {0x904d120, 0xc003396180}, 0xc0002be000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:431 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002e61e0, {0x9074920, 0xc001bba000}, 0xc00300e000, 0xc001ac6630, 0xe988c68, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002e61e0, {0x9074920, 0xc001bba000}, 0xc00300e000, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 36
	google.golang.org/grpc@v1.58.3/server.go:997 +0x145
Error: The terraform-provider-azurerm_v3.96.0_x5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Terraform plan output in tfplan file

### Actual Behaviour

Terraform azurerm plugin crashed

**Comment by rcskosir** [comment]
@HansGe Thanks for taking the time to open this issue. I believe this is a duplicate of #25314 which was fixed by #25332. As such, I'm going to mark this as a duplicate and close, this crash should no longer exist in the latest version of the provider. If you find that's not the case, please reach out and we can take another look.
