### ISSUE TITLE
Error: The terraform-provider-azurerm_v3.99.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by davetustin** [hashicorp/terraform-provider-azurerm#25617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.0

### AzureRM Provider Version

3.99.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_rule_set" "cdn_frontdoor_rule_set" {
  for_each = {
    for rule_set in var.rule_sets : rule_set.name => rule_set
  }

  name = each.value.name

  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.cdn_frontdoor_profile.id
}

resource "azurerm_cdn_frontdoor_rule" "cdn_frontdoor_rule" {
  for_each = {
    for rule in local.rules_per_rule_set : format("%s.%s", rule.rule_set_name, rule.name) => rule
  }

  name = each.value.name

  cdn_frontdoor_rule_set_id = azurerm_cdn_frontdoor_rule_set.cdn_frontdoor_rule_set[each.value.rule_set_name].id

  order             = each.value.order
  behavior_on_match = each.value.behavior_on_match

  actions {
    dynamic "url_rewrite_action" {
      for_each = each.value.actions.url_rewrite_actions
      iterator = action
      content {
        source_pattern          = action.value.source_pattern
        destination             = action.value.destination
        preserve_unmatched_path = action.value.preserve_unmatched_path
      }
    }
    dynamic "url_redirect_action" {
      for_each = each.value.actions.url_redirect_actions
      iterator = action
      content {
        redirect_type        = action.value.redirect_type
        destination_hostname = action.value.destination_hostname
        redirect_protocol    = action.value.redirect_protocol
        destination_path     = action.value.destination_path
        query_string         = action.value.query_string
        destination_fragment = action.value.destination_fragment
      }
    }
    dynamic "route_configuration_override_action" {
      for_each = each.value.actions.route_configuration_override_actions
      iterator = action
      content {
        cache_duration                = action.value.cache_duration
        cdn_frontdoor_origin_group_id = action.value.cdn_frontdoor_origin_group_id
        forwarding_protocol           = action.value.forwarding_protocol
        query_string_caching_behavior = action.value.query_string_caching_behavior
        query_string_parameters       = action.value.query_string_parameters
        compression_enabled           = action.value.compression_enabled
        cache_behavior                = action.value.cache_behavior
      }
    }
    dynamic "request_header_action" {
      for_each = each.value.actions.request_header_actions
      iterator = action
      content {
        header_action = action.value.header_action
        header_name   = action.value.header_name
        value         = action.value.value
      }
    }
    dynamic "response_header_action" {
      for_each = each.value.actions.response_header_actions
      iterator = action
      content {
        header_action = action.value.header_action
        header_name   = action.value.header_name
        value         = action.value.value
      }
    }
  }

  dynamic "conditions" {
    for_each = each.value.conditions[*]
    content {
      dynamic "remote_address_condition" {
        for_each = each.value.conditions.remote_address_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
        }
      }
      dynamic "request_method_condition" {
        for_each = each.value.conditions.request_method_conditions
        iterator = condition
        content {
          match_values     = condition.value.match_values
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
        }
      }
      dynamic "query_string_condition" {
        for_each = each.value.conditions.query_string_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
          transforms       = condition.value.transforms
        }
      }
      dynamic "post_args_condition" {
        for_each = each.value.conditions.post_args_conditions
        iterator = condition
        content {
          post_args_name   = condition.value.post_args_name
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
          transforms       = condition.value.transforms
        }
      }
      dynamic "request_uri_condition" {
        for_each = each.value.conditions.request_uri_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
          transforms       = condition.value.transforms
        }
      }
      dynamic "request_header_condition" {
        for_each = each.value.conditions.request_header_conditions
        iterator = condition
        content {
          header_name      = condition.value.header_name
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
          transforms       = condition.value.transforms
        }
      }
      dynamic "request_body_condition" {
        for_each = each.value.conditions.request_body_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          match_values     = condition.value.match_values
          negate_condition = condition.value.negate_condition
          transforms       = condition.value.transforms
        }
      }
      dynamic "request_scheme_condition" {
        for_each = each.value.conditions.request_scheme_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
        }
      }
      dynamic "url_path_condition" {
        for_each = each.value.conditions.url_path_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
          transforms       = condition.value.transforms
        }
      }
      dynamic "url_file_extension_condition" {
        for_each = each.value.conditions.url_file_extension_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
          transforms       = condition.value.transforms
        }
      }
      dynamic "url_filename_condition" {
        for_each = each.value.conditions.url_filename_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          match_values     = condition.value.match_values
          negate_condition = condition.value.negate_condition
          transforms       = condition.value.transforms
        }
      }
      dynamic "http_version_condition" {
        for_each = each.value.conditions.http_version_conditions
        iterator = condition
        content {
          match_values     = condition.value.match_values
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
        }
      }
      dynamic "cookies_condition" {
        for_each = each.value.conditions.cookies_conditions
        iterator = condition
        content {
          cookie_name      = condition.value.cookie_name
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
          transforms       = condition.value.transforms
        }
      }
      dynamic "is_device_condition" {
        for_each = each.value.conditions.is_device_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
        }
      }
      dynamic "socket_address_condition" {
        for_each = each.value.conditions.socket_address_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
        }
      }
      dynamic "client_port_condition" {
        for_each = each.value.conditions.client_port_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
          match_values     = condition.value.match_values
        }
      }
      dynamic "server_port_condition" {
        for_each = each.value.conditions.server_port_conditions
        iterator = condition
        content {
          operator         = condition.value.operator
          match_values     = condition.value.match_values
          negate_condition = condition.value.negate_condition
        }
      }
      dynamic "host_name_condition" {
        for_each = each.value.conditions.host_name_conditions
        iterator = condition
        content {
          operator     = condition.value.operator
          match_values = condition.value.match_values
          transforms   = condition.value.transforms
        }
      }
      dynamic "ssl_protocol_condition" {
        for_each = each.value.conditions.ssl_protocol_conditions
        iterator = condition
        content {
          match_values     = condition.value.match_values
          operator         = condition.value.operator
          negate_condition = condition.value.negate_condition
        }
      }
    }
  }

  depends_on = [
    azurerm_cdn_frontdoor_origin_group.cdn_frontdoor_origin_group,
    azurerm_cdn_frontdoor_origin.cdn_frontdoor_origin,
  ]
}
```

### Debug Output/Panic Output

```shell
Error: Plugin did not respond
│
│   with azurerm_cdn_frontdoor_rule.cdn_frontdoor_rule["cdnRedirect.cdnRedirect"],
│   on cdn-frontdoor-rules.tf line 11, in resource "azurerm_cdn_frontdoor_rule" "cdn_frontdoor_rule":
│   11: resource "azurerm_cdn_frontdoor_rule" "cdn_frontdoor_rule" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_cdn_frontdoor_rule.cdn_frontdoor_rule["wwwRedirect.wwwRedirect"],
│   on cdn-frontdoor-rules.tf line 11, in resource "azurerm_cdn_frontdoor_rule" "cdn_frontdoor_rule":
│   11: resource "azurerm_cdn_frontdoor_rule" "cdn_frontdoor_rule" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.99.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 76 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.expandFrontdoorDeliveryRuleActions({0xc00401d630, 0x82eafc1?, 0x8b20ea0?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_rule_resource.go:827 +0x7b6
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.resourceCdnFrontDoorRuleCreate(0x0?, {0x730a700?, 0xc00051e000})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_rule_resource.go:648 +0x4f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x8b3a0a0?, {0x8b3a0a0?, 0xc001d94990?}, 0xd?, {0x730a700?, 0xc00051e000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000d21dc0, {0x8b3a0a0, 0xc001d94990}, 0xc0007d88f0, 0xc001d49080, {0x730a700, 0xc00051e000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00045e6f0, {0x8b3a0a0?, 0xc001d948a0?}, 0xc000f6b9a0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001ad9220, {0x8b3a0a0?, 0xc001d87e90?}, 0xc0006149a0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x7f3cc00?, 0xc001ad9220}, {0x8b3a0a0, 0xc001d87e90}, 0xc000614930, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002d61e0, {0x8b61ec0, 0xc001c5e000}, 0xc001d90480, 0xc001bb2cf0, 0xe3d1d58, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002d61e0, {0x8b61ec0, 0xc001c5e000}, 0xc001d90480, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 52
        google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.99.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Expected Behaviour

Terraform plan output in tfplan file

### Actual Behaviour

Terraform azurerm plugin crashed

### Steps to Reproduce

terraform plan

**Comment by katbyte** [comment]
Thank you for taking the time to report this issue, and apologies that it has sat without a resolution for so long.

This bug was reported against an early major version of the AzureRM provider. The provider has since moved on to v5.x, and the affected functionality has often been significantly reworked across those major releases, so bug reports from legacy major versions prior to v4.0 are generally no longer actionable as written.

As part of a cleanup of historical issues we are closing bug reports that target legacy provider versions. If you are still running into this behaviour on the current major version, please open a new issue with up-to-date reproduction details (feel free to reference this one) so it can be triaged with current context.

Thank you again for the report, and for your patience.
