### ISSUE TITLE
Panic during apply on azurerm_lighthouse_definition

### ISSUE THREAD

**Issue by PeterLofaj** [hashicorp/terraform-provider-azurerm#25926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.102.0

### Affected Resource(s)/Data Source(s)

azurerm_lighthouse_definition

### Terraform Configuration Files

```hcl
# azurerm_lighthouse_definition
    lighthouse_definitions = {
      "name" = {
        managing_tenant_id = "id"
        scope              = "/subscriptions/${local.subscription_id}"
  
        authorization = {
          "name" = {
            principal_id       = local.principal_id
            role_definition_id = "id"
          },
        }
  
        lighthouse_definition_id = "id"
      },
    }
```

### Debug Output/Panic Output

```shell
module.lighthouse_definition.azurerm_lighthouse_definition.this[""]: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with module.lighthouse_definition.azurerm_lighthouse_definition.this[""],
│   on ../../main.tf line 1, in resource "azurerm_lighthouse_definition" "this":
│    1: resource "azurerm_lighthouse_definition" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.102.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x105a0ecdc]

goroutine 40 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/lighthouse.resourceLighthouseDefinitionCreateUpdate(0x0?, {0x107453020?, 0x14000f0e480?})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/lighthouse/lighthouse_definition_resource.go:221 +0x5c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1084734f8?, {0x1084734f8?, 0x14004908cc0?}, 0xd?, {0x107453020?, 0x14000f0e480?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140015d5340, {0x1084734f8, 0x14004908cc0}, 0x14001c9e410, 0x1400491c780, {0x107453020, 0x14000f0e480})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000b0d038, {0x1084734f8?, 0x14004908bd0?}, 0x14001b88460)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xb08
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14001b8b220, {0x1084734f8?, 0x140049081b0?}, 0x14000f6e070)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x108093340?, 0x14001b8b220}, {0x1084734f8, 0x140049081b0}, 0x14000f6e000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140004b6000, {0x10849c280, 0x14001873040}, 0x14004914000, 0x14001854780, 0x10dbe3098, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xb44
google.golang.org/grpc.(*Server).handleStream(0x140004b6000, {0x10849c280, 0x14001873040}, 0x14004914000, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x7cc
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xb4
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 16
	google.golang.org/grpc@v1.58.3/server.go:997 +0x160

Error: The terraform-provider-azurerm_v3.102.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Works without issues with version 3.101.0 and lower. 

### Actual Behaviour

Error: Plugin did not respond

### Steps to Reproduce

terraform apply

### References

Same behaviour reported in https://github.com/hashicorp/terraform-provider-azurerm/issues/25918

**Comment by lonegunmanb** [comment]
Hello @PeterLofaj have you tried `v3.103.0`? It looks like in `v3.102.0` the init call for `Lighthouse` client has been deleted, and has been reverted in `v3.103.0`.

**Comment by PeterLofaj** [comment]
Issue no longer happens in version v3.103.1
