### ISSUE TITLE
Internal error - Error: listing Site Publishing Credential information for Slot

### ISSUE THREAD

**Issue by flcdrg** [hashicorp/terraform-provider-azurerm#26183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

v3.106.1

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
Tricky to supply as internal app with private virtual network.

Azure App Services with private endpoints.
```

### Debug Output/Panic Output

```shell
https://gist.github.com/flcdrg/c4b86cb3d964714eb0c139d05cd9a2a0
```

### Expected Behaviour

Not crash

### Actual Behaviour

Provider crashed

error: listing Site Publishing Credential information for Slot

```
The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.


Stack trace from the terraform-provider-azurerm_v3.106.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbf77c1]

goroutine 4176 [running]:
github.com/hashicorp/go-azure-sdk/sdk/client/pollers.(*Poller).PollUntilDone.func1()
	github.com/hashicorp/go-azure-sdk/sdk@v0.20240529.1155048/client/pollers/poller.go:124 +0xa1
created by github.com/hashicorp/go-azure-sdk/sdk/client/pollers.(*Poller).PollUntilDone in goroutine 3612
	github.com/hashicorp/go-azure-sdk/sdk@v0.20240529.1155048/client/pollers/poller.go:108 +0xfd
```

### Steps to Reproduce

1. Terraform apply

**Comment by marcindulak** [comment]
I've just had a similar problem occurring once, but with a different resource `azurerm_linux_web_app_slot`, terraform `1.7.5` and azurerm versions `3.104.2`, and without `SIGSEGV`.

I'm adding this to the list of nondeterministc terraform behaviors at https://github.com/hashicorp/terraform-provider-azurerm/issues/25585

```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: listing Site Publishing Credential information for Slot (Subscription: "AAA"
│ Resource Group Name: "rg-test"
│ Site Name: "app-test"
│ Slot Name: "slot"): listing Site Publishing Credential information for Slot (Subscription: "AAA"
│ Resource Group Name: "rg-test"
│ Site Name: "app-test"
│ Slot Name: "slot"): Post "https://management.azure.com/subscriptions/AAA/resourceGroups/rg-test/providers/Mic\
rosoft.Web/sites/app-test/slots/slot/config/publishingcredentials/list?api-version=2023-01-01": HTTP response w\
as nil; connection may have been reset
│
│   with module.app.azurerm_linux_web_app_slot.this,
│   on .terraform/modules/app/app.tf line 493, in resource "azurerm_linux_web_app_slot" "this":
│  493: resource "azurerm_linux_web_app_slot" "this" {
...
```

**Comment by katbyte** [comment]
Thank you for taking the time to report this issue, and apologies that it has sat without a resolution for so long.

This bug was reported against an early major version of the AzureRM provider. The provider has since moved on to v5.x, and the affected functionality has often been significantly reworked across those major releases, so bug reports from legacy major versions prior to v4.0 are generally no longer actionable as written.

As part of a cleanup of historical issues we are closing bug reports that target legacy provider versions. If you are still running into this behaviour on the current major version, please open a new issue with up-to-date reproduction details (feel free to reference this one) so it can be triaged with current context.

Thank you again for the report, and for your patience.
