### ISSUE TITLE
Error: The terraform-provider-azurerm_v4.7.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by sheeeng** [hashicorp/terraform-provider-azurerm#27804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.7.0

### Affected Resource(s)/Data Source(s)

azurerm_4.7.0

### Terraform Configuration Files

```hcl
required_providers {
     azurerm = {
       source  = "hashicorp/azurerm"
-      version = "4.5.0"
+      version = "4.7.0"
     }
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v4.7.0_x5 plugin:

panic: interface conversion: rolemanagementpolicies.RoleManagementPolicyRule is rolemanagementpolicies.RoleManagementPolicyEnablementRule, not rolemanagementpolicies.RawRoleManagementPolicyRuleImpl

goroutine 19491 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/authorization.(*RoleManagementPolicyResource).Read.RoleManagementPolicyResource.Read.func1({0x8886240, 0xc000556690}, {0xc001915688, {0x8888ab8, 0xc0007eb710}, 0xc003237c00, 0x0, {0x8889a40, 0xddfb300}})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/authorization/role_management_policy_resource.go:466 +0x1e98
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func3({0x8886240, 0xc000556690}, 0xc000556690?, {0x70369c0?, 0xc001915688?})
	github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:68 +0x145
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.(*ResourceWrapper).diagnosticsWrapper.diagnosticsWrapper.func11({0x8886240?, 0xc000556690?}, 0x45d964b800?, {0x70369c0?, 0xc001915688?})
	github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:192 +0x59
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0008036c0, {0x8886198, 0xc003c9d320}, 0xc003237c00, {0x70369c0, 0xc001915688})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:795 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0008036c0, {0x8886198, 0xc003c9d320}, 0xc0038bde10, {0x70369c0, 0xc001915688})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x529
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0005376c8, {0x8886198?, 0xc003c9d260?}, 0xc0020600c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x4aa
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0xc0018d21c0, {0x8886198?, 0xc003c9ce10?}, 0xc0020600c0)
	github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ReadResource.go:35 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0017ce1e0, {0x8886198?, 0xc003c9c2a0?}, 0xc000e12460)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:783 +0x309
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x7d3fb40, 0xc0017ce1e0}, {0x8886198, 0xc003c9c2a0}, 0xc003237000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000c6c000, {0x8886198, 0xc003c9c210}, {0x88b2e20, 0xc000002000}, 0xc003071200, 0xc000bd0300, 0xdd88408, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000c6c000, {0x88b2e20, 0xc000002000}, 0xc003071200)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 12
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-azurerm_v4.7.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

### Expected Behaviour

No errors expected.

### Steps to Reproduce

`terraform plan`

**Comment by ziyeqf** [comment]
Hi @sheeeng, thanks for reporting.

There is an existing issue (https://github.com/hashicorp/terraform-provider-azurerm/issues/27710) for this and we have a merged PR(https://github.com/hashicorp/terraform-provider-azurerm/pull/27731) for this and will be released in v4.8.0.
