### ISSUE TITLE
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.

### ISSUE THREAD

**Issue by sagarhatrote1** [hashicorp/terraform-provider-azurerm#28116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

4.2.0

### Affected Resource(s)/Data Source(s)

azurerm_data_protection_backup_vault

### Terraform Configuration Files

```hcl
resource "azurerm_data_protection_backup_vault" "backup_vault" {
  for_each                     = { for vault in var.backupvault : "${vault.bv_redundancy}-${vault.backupvaultindex}" => vault }
  name                         = "BV-${substr(each.value.bv_redundancy, 0, 1)}RS-${each.value.backupvaultindex}"
  resource_group_name          = var.resource_group_name
  location                     = var.location
  datastore_type               = each.value.bv_datastore_type
  redundancy                   = each.value.bv_redundancy
  soft_delete                  = each.value.soft_delete
  tags                         = var.bvtags
  cross_region_restore_enabled = each.value.cross_region_restore_enabled
  identity { type = each.value.identitytype }
}
```

### Debug Output/Panic Output

```shell
data.azurerm_resource_group.backuprg: Refresh complete after 0s [id=/subscriptions/9d8ae9cd-44e9-440b-b211-75694d48a2ff/resourceGroups/backup-01]
 Warning: Argument is deprecated
   with provider["registry.terraform.io/hashicorp/azurerm"],
   on azurerm.tf line 2, in provider "azurerm":
    2: provider "azurerm" {
 This property is deprecated and will be removed in v5.0 of the AzureRM provider. Please use the `resource_provider_registrations` property instead.
   with provider["registry.terraform.io/hashicorp/azurerm"],
   on azurerm.tf line 2, in provider "azurerm":
    2: provider "azurerm" {
This property is deprecated and will be removed in v5.0 of the AzureRM provider. Please use the `resource_provider_registrations` property instead.
 Warning: Argument is deprecated
 Error: Plugin did not respond
   with azurerm_data_protection_backup_vault.backup_vault
   on backupvault.tf line 1, in resource "azurerm_data_protection_backup_vault" "backup_vault":
    1: resource "azurerm_data_protection_backup_vault" "backup_vault" {
 The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
 Error: Plugin did not respond
   with azurerm_data_protection_backup_vault.backup_vault
   on backupvault.tf line 1, in resource "azurerm_data_protection_backup_vault" "backup_vault":
    1: resource "azurerm_data_protection_backup_vault" "backup_vault" {
 The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
 Error: Plugin did not respond
   with azurerm_data_protection_backup_vault.backup_vault
   on backupvault.tf line 1, in resource "azurerm_data_protection_backup_vault" "backup_vault":
    1: resource "azurerm_data_protection_backup_vault" "backup_vault" {
 The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
 Stack trace from the terraform-provider-azurerm_v4.2.0_x5 plugin:
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x57b1a0c]
 goroutine 357 [running]:
 github.com/hashicorp/terraform-provider-azurerm/internal/services/dataprotection.resourceDataProtectionBackupVaultRead(0xc002ead900, {0x6eefcc0?, 0xc002631680?})
 	github.com/hashicorp/terraform-provider-azurerm/internal/services/dataprotection/data_protection_backup_vault_resource.go:260 +0x6ec
 github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x86b34a8?, {0x86b34a8?, 0xc0031281b0?}, 0xd?, {0x6eefcc0?, 0xc002631680?})
 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:783 +0x163
 github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000c91880, {0x86b34a8, 0xc0031281b0}, 0xc002e81860, {0x6eefcc0, 0xc002631680})
 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x552
 github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00001fd70, {0x86b34a8?, 0xc0031280c0?}, 0xc002e85c40)
 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x48a
 github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0x86b34e0?, {0x86b34a8?, 0xc003101da0?}, 0xc002e85c40)
 	github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ReadResource.go:35 +0x193
 github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000f626e0, {0x86b34a8?, 0xc003101590?}, 0xc00132ea10)
 	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:783 +0x309
 github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x7ba6da0?, 0xc000f626e0}, {0x86b34a8, 0xc003101590}, 0xc002ead600, 0x0)
 	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x169
 google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ad800, {0x86b34a8, 0xc003101500}, {0x86dee40, 0xc00029c780}, 0xc0031150e0, 0xc001d55440, 0xda393a8, 0x0)
 	google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
 google.golang.org/grpc.(*Server).handleStream(0xc0000ad800, {0x86dee40, 0xc00029c780}, 0xc0031150e0)
 	google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
 google.golang.org/grpc.(*Server).serveStreams.func2.1()
 	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
 created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 26
 	google.golang.org/grpc@v1.63.2/server.go:1030 +0x135
 Error: The terraform-provider-azurerm_v4.2.0_x5 plugin crashed!
 This is always indicative of a bug within the plugin. It would be immensely
 helpful if you could report the crash with the plugin's maintainers so that it
 can be fixed. The output above should help diagnose the issue.
 {"level":"error","timestamp":"2024-11-26T09:59:44.127Z","msg":"Command failed with exit code","exitCode":1,"error":"exit status 1"}
 {"level":"error","timestamp":"2024-11-26T09:59:44.127Z","msg":"Failed to run Terraform","error":"exit status 1"}
 {"level":"error","timestamp":"2024-11-26T09:59:44.132Z","msg":"Failed to run","error":"failed to run terraform: exit status 1"}
```

### Expected Behaviour

all the resources are getting created normally but the plugin crash errors are coming up

**Comment by ziyeqf** [comment]
Hi @sagarhatrote1, thanks for reporting.

The bug should have been fixed on v4.8.0 via this PR(https://github.com/hashicorp/terraform-provider-azurerm/pull/27762), could you please upgrade the provider version and give it a try?

Thanks
