### ISSUE TITLE
Bug when trying to apply terraform resource azurerm_app_service_custom_hostname_binding again

### ISSUE THREAD

**Issue by samershr** [hashicorp/terraform-provider-azurerm#4346]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Everytime I try to rerun the terrform code to make some changes (without changing the custom hostname binding to the Web App) an error will be displayed as shown below in the Output.
Is this a bug in in the provider or I am missing something here to prevent it?
### Terraform (and AzureRM Provider) Version
current version v1.33.1, also with older versions

### Affected Resource(s)

azurerm_app_service_custom_hostname_binding

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_custom_hostname_binding" "test_webapp" {
  hostname            = "test.com"
  app_service_name    = "test-webapp"
  resource_group_name = "test-arm"
}
```

### Output
```hcl
Error: Provider produced inconsistent result after apply

When applying changes to
azurerm_app_service_custom_hostname_binding.test_webapp, provider "azurerm"
produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

**Comment by samershr** [comment]
I forgot to mention that the output is not affecting the resource. It just appearing everytime after apply.

**Comment by hubby2004** [comment]
+1

I have the same issue. Here is the output during a terraform apply:

```
2021-05-03T17:23:28.783-0400 [TRACE] vertex "azurerm_app_service.app (expand)": visit complete
2021-05-03T17:23:28.783-0400 [TRACE] vertex "azurerm_app_service_custom_hostname_binding.wordpress": starting visit (*terraform.NodeApplyableResource)
2021-05-03T17:23:28.783-0400 [TRACE] vertex "azurerm_app_service_custom_hostname_binding.wordpress": visit complete
2021-05-03T17:23:28.783-0400 [TRACE] vertex "azurerm_app_service_custom_hostname_binding.wordpress (expand)": dynamic subgraph completed successfully
2021-05-03T17:23:28.783-0400 [TRACE] vertex "azurerm_app_service_custom_hostname_binding.wordpress (expand)": visit complete
2021-05-03T17:23:28.783-0400 [TRACE] setValue: Saving NoOp change for output.resource_group in changeset
2021-05-03T17:23:28.783-0400 [TRACE] setValue: Saving value for output.resource_group in state
2021-05-03T17:23:28.783-0400 [TRACE] vertex "output.resource_group": visit complete
2021-05-03T17:23:28.783-0400 [TRACE] vertex "azurerm_app_service_custom_hostname_binding.wordpress": starting visit (*terraform.NodeApplyableResourceInstance)
2021-05-03T17:23:28.783-0400 [TRACE] readDiff: Read Create change from plan for azurerm_app_service_custom_hostname_binding.wordpress
2021-05-03T17:23:28.783-0400 [TRACE] readResourceInstanceState: reading state for azurerm_app_service_custom_hostname_binding.wordpress
2021-05-03T17:23:28.784-0400 [TRACE] readResourceInstanceState: no state present for azurerm_app_service_custom_hostname_binding.wordpress
2021-05-03T17:23:28.784-0400 [TRACE] readDiff: Read Create change from plan for azurerm_app_service_custom_hostname_binding.wordpress
2021-05-03T17:23:28.785-0400 [TRACE] vertex "azurerm_app_service_custom_hostname_binding.wordpress": visit complete

panic: value is marked, so must be unmarked first

goroutine 360 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.ElementIterator(0x342a028, 0xc0003ac8e0, 0x2cd42e0, 0xc00101d308, 0x1, 0xc0003acec0)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/value_ops.go:1111 +0x56
github.com/hashicorp/terraform/terraform.getValMarks(0xc00100c4b0, 0x3429ff0, 0xc0003ace80, 0x2be5800, 0xc001b18db0, 0x0, 0x0, 0x0, 0x7020107, 0x1, ...)
	/home/circleci/project/project/terraform/evaluate.go:998 +0x748
github.com/hashicorp/terraform/terraform.markProviderSensitiveAttributes(0xc00100c4b0, 0x3429ff0, 0xc0003ace80, 0x2be5800, 0xc001b18db0, 0x0, 0x13, 0xc0006f9640, 0x3)
	/home/circleci/project/project/terraform/evaluate.go:960 +0x75
github.com/hashicorp/terraform/terraform.(*evaluationStateData).GetResource(0xc0006157a0, 0x4d, 0xc00078d188, 0x13, 0xc0006f9640, 0x3, 0xc0006f8c09, 0x7, 0x9f, 0x19, ...)
	/home/circleci/project/project/terraform/evaluate.go:787 +0x1353
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc000994820, 0xc001774890, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30)
	/home/circleci/project/project/lang/eval.go:360 +0x208d
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(...)
	/home/circleci/project/project/lang/eval.go:238
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc000994820, 0x3428ab8, 0xc0019cdb60, 0xc000395890, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/lang/eval.go:51 +0x105
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc001bab110, 0x3428d58, 0xc0019cdb60, 0xc000395890, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/terraform/eval_context_builtin.go:273 +0x1bb
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).plan(0xc0000c6fc0, 0x3460990, 0xc001bab110, 0xc0009ad180, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0006f9630, ...)
	/home/circleci/project/project/terraform/node_resource_abstract_instance.go:577 +0x3df
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).managedResourceExecute(0xc000084640, 0x3460990, 0xc001bab110, 0x0, 0x0, 0xc0003c1c10)
	/home/circleci/project/project/terraform/node_resource_apply_instance.go:235 +0x63d
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).Execute(0xc000084640, 0x3460990, 0xc001bab110, 0x2ca746c4501, 0xc0003c1d18, 0xb8c06a, 0x2c2f5c0)
	/home/circleci/project/project/terraform/node_resource_apply_instance.go:129 +0xbc
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc000668a80, 0x3460990, 0xc001bab110, 0x2ca746c45f8, 0xc000084640, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xc6
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2f7b460, 0xc000084640, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0xbb3
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000417980, 0x2f7b460, 0xc000084640, 0xc0011f8980)
	/home/circleci/project/project/dag/walk.go:381 +0x2a2
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:304 +0x1246
```

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
