### ISSUE TITLE
Disabling RBAC AAD makes terraform crash on apply

### ISSUE THREAD

**Issue by Mimetis** [hashicorp/terraform-provider-azurerm#6308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* terraform --version
Terraform v0.12.21
+ provider.azurerm v2.2.0
+ provider.helm v1.1.1
+ provider.kubernetes v1.11.1
+ provider.null v2.1.2
+ provider.random v2.2.1

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

The important part here, is the `dynamic "role_based_access_control"` block. Everything else is just here for information only 

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "${var.aks_cluster_prefix}-${var.environment}"
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name
  kubernetes_version  = var.aks_kubernetes_version
  dns_prefix          = "${var.aks_dns_prefix}-${var.unique_string}"

  service_principal {
    client_id     = var.aks_sp_client_id
    client_secret = var.aks_sp_client_secret
  }

  # Not ignoring these will unnecessary force cluster recreation
  lifecycle {
    ignore_changes = [windows_profile, tags]
  }

  dynamic "role_based_access_control" {
    iterator = rbac
    for_each = [true] # Using a dummy iterator on one value (true)
    content {
      enabled = rbac.value
      dynamic "azure_active_directory" {
        iterator = aad
        for_each = var.aad_enabled ? [{}] : [] # Using a dummy object for iterating on one value if true or no value if false
        content {
          client_app_id     = var.aad_client_application_id
          server_app_id     = var.aad_server_application_id
          server_app_secret = var.aad_server_application_secret
          tenant_id         = data.azurerm_client_config.current.tenant_id
        }
      }
    }
  }
}
```
### Starting poing

As you can see, the "role_base_access_control" block is `dynamic` 
It allows us to enable or disable quite easely the `azure_active_directory` integration.

So far, using `var.aad_enabled=true` give us this plan:

``` hcl
      ~ role_based_access_control {
            enabled = true

          + azure_active_directory {
              + client_app_id     = "AA*****-*****-****-*****" -> null
              + server_app_id     = "BB*****-*****-****-*****" -> null
              + server_app_secret = (sensitive value)
              + tenant_id         = "CC*****-*****-****-*****"" -> null
            }
        }
```

and then, going to `false` give us this update on the cluster:

``` hcl
      ~ role_based_access_control {
            enabled = true

          - azure_active_directory {
              - client_app_id     = "AA*****-*****-****-*****" -> null
              - server_app_id     = "BB*****-*****-****-*****" -> null
              - server_app_secret = (sensitive value)
              - tenant_id         = "CC*****-*****-****-*****"" -> null
            }
        }
```

The bug comes when you try to disable an in place aad integration.
Let's say:
- Step 1 : `aad_enabled=false` : Cluster is created with rbac enabled (hard coded in our config) but there is no AAD integration
- Step 2 : `aad_enabled=true` : Cluster is updated and the AAD configuration update is applied correctly
- Step 3 : `aad_enabled=false` : We want to revert back to "No AAD integration" : terraform apply crashes.

### Debug Output

I'm using the `TF_LOG` env variable to get more details. 

``` bash
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5: [DEBUG] Updating the RBAC AAD profile
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5:
Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x315d11b]
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5:
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5: goroutine 48 [running]:
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers.resourceArmKubernetesClusterUpdat
e(0xc0004b92d0, 0x3a14860, 0xc000934000, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/s
ervices/containers/resource_arm_kubernetes_cluster.go:708 +0x4cb
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0005c2e80, 0xc000ad05f0, 0xc00100ea80, 0x3a14860, 0
xc000934000, 0xc001821801, 0x2, 0x39f0b20)
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/
hashicorp/terraform-plugin-sdk/helper/schema/resource.go:311 +0x264
```

### Expected Behavior

terraform should apply successfully. 
The AAD integration should be updated correctly.
In that case, AAD integration should be removed / disabled

### Actual Behavior

terraform should crashes

### Steps to Reproduce

- Create a simple cluster with RBAC enabled
- Update this cluster with AAD Integration 
- Update this cluster by removing the AAD ingration

### Important Factoids

the debug output comes from the function `resourceArmKubernetesClusterUpdate`:

``` go
if d.HasChange("role_based_access_control") {
....
....
	log.Printf("[DEBUG] Updating the RBAC AAD profile")
	future, err := clusterClient.ResetAADProfile(ctx, id.ResourceGroup, id.Name, *props.AadProfile)
....
....
}
```
So far, the proble should comes from the function `ResetAADProfile` 
As I'm not a **Go** expert, but regarding the log, I guess there is a `null reference exception` somewhere.

**Comment by tombuildsstuff** [comment]
hey @Mimetis 

Thanks for opening this issue

Taking a quick look into this, it appears the line number is missing from the crash log here:

```
2020-03-31T13:21:21.415+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers.resourceArmKubernetesClusterUpdat
```

So that we can take a look into this would it be possible to provide a larger snippet of the debug log here?

Thanks!

**Comment by Mimetis** [comment]
Hey @tombuildsstuff 
Sorry, here is a more detailed log (I update the issue as well)

``` bash
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers.resourceArmKubernetesClusterUpdat
e(0xc0004b92d0, 0x3a14860, 0xc000934000, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/s
ervices/containers/resource_arm_kubernetes_cluster.go:708 +0x4cb
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0005c2e80, 0xc000ad05f0, 0xc00100ea80, 0x3a14860, 0
xc000934000, 0xc001821801, 0x2, 0x39f0b20)
[DEBUG] plugin.terraform-provider-azurerm_v2.2.0_x5:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/
hashicorp/terraform-plugin-sdk/helper/schema/resource.go:311 +0x264
```

**Comment by patpicos** [comment]
not sure if the issue i faced is similar:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/7325#issuecomment-655073523

**Comment by aaronjensen** [comment]
2.46.1 has this issue still:

```
2021-02-08T23:51:30.6220496Z panic: runtime error: invalid memory address or nil pointer dereference
2021-02-08T23:51:30.6222335Z 2021-02-08T23:51:30.383Z [DEBUG] plugin.terraform-provider-azurerm_v2.46.1_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3ed1062]
2021-02-08T23:51:30.6224123Z 2021-02-08T23:51:30.383Z [DEBUG] plugin.terraform-provider-azurerm_v2.46.1_x5: 
2021-02-08T23:51:30.6225682Z 2021-02-08T23:51:30.383Z [DEBUG] plugin.terraform-provider-azurerm_v2.46.1_x5: goroutine 124 [running]:
2021-02-08T23:51:30.6228498Z 2021-02-08T23:51:30.383Z [DEBUG] plugin.terraform-provider-azurerm_v2.46.1_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers.resourceKubernetesClusterUpdate(0xc0013881c0, 0x4bb0200, 0xc0017fd200, 0x0, 0x0)
2021-02-08T23:51:30.6230551Z 2021-02-08T23:51:30.384Z [DEBUG] plugin.terraform-provider-azurerm_v2.46.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers/kubernetes_cluster_resource.go:926 +0x542
...
```

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
